#
# Copyright (C) 2018 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

ifeq ($(CONFIG_MTK_CAM_CAL), m)
obj-$(CONFIG_MTK_CAM_CAL) += custom/
endif

obj-$(CONFIG_MTK_CAM_CAL) += isp4/
obj-$(CONFIG_MTK_CAM_CAL_ISP3_Z) += isp3_z/
obj-$(CONFIG_MTK_CAM_CAL_ISP3_M) += isp3_m/
obj-$(CONFIG_MTK_CAM_CAL_ISP4_C) += isp4_c/
