ccflags-y  += -I$(srctree)/drivers/misc/mediatek/include/mt-plat

obj-$(CONFIG_MTK_SOC_THERMAL)	+= soc_temp.o
obj-$(CONFIG_MTK_SOC_THERMAL_LVTS)	+= soc_temp_lvts.o

obj-$(CONFIG_MTK_MD_THERMAL)		+= md_cooling.o
obj-$(CONFIG_MTK_MD_THERMAL_MUTT)	+= md_cooling_mutt.o
