ccflags-y += -Idrivers/media/platform/msm/ais/cam_core
ccflags-y += -Idrivers/media/platform/msm/ais/ais_isp/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sync
ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cdm/

obj-$(CONFIG_MSM_AIS) += csid_hw/
obj-$(CONFIG_MSM_AIS) += vfe_hw/
obj-$(CONFIG_MSM_AIS) += utils/

obj-$(CONFIG_MSM_AIS) += ais_ife_dev.o
