ifeq ($(MODNAME),)
    KERNEL_BUILD := 1
    else
    KERNEL_BUILD := 0
endif

ifeq ($(KERNEL_BUILD), 1)
    AUDIO_BLD_DIR := $(shell pwd)/kernel/msm-5.4
    AUDIO_ROOT := $(AUDIO_BLD_DIR)/techpack/audio
endif

ifeq ($(KERNEL_BUILD), 0)
    ifeq ($(CONFIG_ARCH_SM6150), y)
        include $(AUDIO_ROOT)/config/sm6150auto.conf
        export
        INCS    +=  -include $(AUDIO_ROOT)/config/sm6150autoconf.h
    endif
    ifeq ($(CONFIG_ARCH_TRINKET), y)
        include $(AUDIO_ROOT)/config/sm6150auto.conf
        export
        INCS    +=  -include $(AUDIO_ROOT)/config/sm6150autoconf.h
    endif
    ifeq ($(CONFIG_ARCH_SM8150), y)
        include $(AUDIO_ROOT)/config/sm8150auto.conf
        export
        INCS    +=  -include $(AUDIO_ROOT)/config/sm8150autoconf.h
    endif
    ifeq ($(CONFIG_ARCH_SDMSHRIKE), y)
        include $(AUDIO_ROOT)/config/sm8150auto.conf
        export
        INCS    +=  -include $(AUDIO_ROOT)/config/sm8150autoconf.h
    endif
endif

# for miui sensorhal

ifdef CONFIG_MIUS_IIO
    MIUS_IIO_OBJS += us_prox.o
    MIUS_IIO_OBJS += kefifo_buf.o
endif

INCS += kernel/msm-5.4/drivers/iio

obj-$(CONFIG_MIUS_IIO) += us_prox_iio.o
us_prox_iio-y := $(MIUS_IIO_OBJS)


# inject some build related information
DEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
