#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-y += $(subst ",,$(CONFIG_MTK_PLATFORM))/

obj-$(CONFIG_ARCH_MT6570) += 2.0/
obj-$(CONFIG_ARCH_MT6580) += 2.0/
obj-$(CONFIG_ARCH_MT6735) += 2.0/
obj-$(CONFIG_ARCH_MT6735M) += 2.0/
obj-$(CONFIG_ARCH_MT6753) += 2.0/
obj-$(CONFIG_ARCH_MT6755) += 2.0/
obj-$(CONFIG_ARCH_MT6797) += 2.0/
obj-$(CONFIG_ARCH_MT6757) += 2.0/
obj-$(CONFIG_MACH_MT6758) += 2.4/
obj-$(CONFIG_MACH_MT3967) += 2.4/
obj-$(CONFIG_ARCH_ELBRUS) += 2.0/
obj-$(CONFIG_MACH_MT6765) += 2.0/
obj-$(CONFIG_MACH_MT6761) += 2.0/
obj-$(CONFIG_MACH_MT6779) += 3.2/
