subdir-ccflags-y += -Werror

# Core
obj-$(CONFIG_PINCTRL_MTK)       += pinctrl-mtk-common.o

obj-$(CONFIG_EINT_MTK)          += mtk-eint.o
obj-$(CONFIG_PINCTRL_MTK_MOORE) += pinctrl-moore.o pinctrl-mtk-common-v2.o
obj-$(CONFIG_PINCTRL_MTK_PARIS) += pinctrl-paris.o pinctrl-mtk-common-v2.o pinctrl-mtk-common-v2_debug.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_MT2701)	+= pinctrl-mt2701.o
obj-$(CONFIG_PINCTRL_MT2712)	+= pinctrl-mt2712.o
obj-$(CONFIG_PINCTRL_MT7623)	+= pinctrl-mt7623.o
obj-$(CONFIG_PINCTRL_MT8135)	+= pinctrl-mt8135.o
obj-$(CONFIG_PINCTRL_MT8127)	+= pinctrl-mt8127.o
obj-$(CONFIG_PINCTRL_MT8173)	+= pinctrl-mt8173.o
obj-$(CONFIG_PINCTRL_MT6397)	+= pinctrl-mt6397.o
obj-$(CONFIG_PINCTRL_MT6758)	+= pinctrl-mt6758.o
obj-$(CONFIG_PINCTRL_MT6765)	+= pinctrl-mt6765.o
obj-$(CONFIG_PINCTRL_MT6761)	+= pinctrl-mt6761.o
obj-$(CONFIG_PINCTRL_MT6757)	+= pinctrl-mt6757.o
obj-$(CONFIG_PINCTRL_MT6763)	+= pinctrl-mt6763.o
obj-$(CONFIG_PINCTRL_MT3967)	+= pinctrl-mt3967.o
obj-$(CONFIG_PINCTRL_MT8163)	+= pinctrl-mt8163.o
obj-$(CONFIG_PINCTRL_MT6779)	+= pinctrl-mt6779.o
