# SPDX-License-Identifier: GPL-2.0
# Core
obj-$(CONFIG_EINT_MTK)		+= mtk-eint.o
obj-$(CONFIG_PINCTRL_MTK)	+= pinctrl-mtk-common.o
obj-$(CONFIG_PINCTRL_MTK_V2)	+= pinctrl-mtk-common-v2.o
obj-$(CONFIG_PINCTRL_MTK_MOORE) += pinctrl-moore.o
obj-$(CONFIG_PINCTRL_MTK_PARIS) += pinctrl-paris.o pinctrl-mtk-common-v2_debug.o

# SoC Drivers
obj-$(CONFIG_PINCTRL_MT2701)	+= pinctrl-mt2701.o
obj-$(CONFIG_PINCTRL_MT2712)	+= pinctrl-mt2712.o
obj-$(CONFIG_PINCTRL_MT8135)	+= pinctrl-mt8135.o
obj-$(CONFIG_PINCTRL_MT8127)	+= pinctrl-mt8127.o
obj-$(CONFIG_PINCTRL_MT6761)	+= pinctrl-mt6761.o
obj-$(CONFIG_PINCTRL_MT6833)	+= pinctrl-mt6833.o
obj-$(CONFIG_PINCTRL_MT6739)	+= pinctrl-mt6739.o
obj-$(CONFIG_PINCTRL_MT6765)	+= pinctrl-mt6765.o
obj-$(CONFIG_PINCTRL_MT6771)	+= pinctrl-mt6771.o
obj-$(CONFIG_PINCTRL_MT6779)	+= pinctrl-mt6779.o
obj-$(CONFIG_PINCTRL_MT6797)	+= pinctrl-mt6797.o
obj-$(CONFIG_PINCTRL_MT7622)	+= pinctrl-mt7622.o
obj-$(CONFIG_PINCTRL_MT7623)	+= pinctrl-mt7623.o
obj-$(CONFIG_PINCTRL_MT7629)	+= pinctrl-mt7629.o
obj-$(CONFIG_PINCTRL_MT8173)	+= pinctrl-mt8173.o
obj-$(CONFIG_PINCTRL_MT8183)	+= pinctrl-mt8183.o
obj-$(CONFIG_PINCTRL_MT6397)	+= pinctrl-mt6397.o
obj-$(CONFIG_PINCTRL_MT6768)	+= pinctrl-mt6768.o
obj-$(CONFIG_PINCTRL_MT6781)	+= pinctrl-mt6781.o
obj-$(CONFIG_PINCTRL_MT6877)	+= pinctrl-mt6877.o
obj-$(CONFIG_PINCTRL_MT6885)	+= pinctrl-mt6885.o