#
# Makefile for the Imagis touch driver
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_IST3038C_C6LITE)  += ist30xxc.o ist30xxc_misc.o ist30xxc_sys.o ist30xxc_update.o ist30xxc_tracking.o ist30xxc_cmcs.o
