#
# Makefile for the Goodix gt9xx touchscreen driver.
#
#subdir-ccflags-y += -DDEBUG
obj-$(CONFIG_TOUCHSCREEN_GT9XX_ZQL6019)		+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_ZQL6019)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_ZQL6019)	+= goodix_tool.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_ZQL6019) += gt9xx_selftest.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_ZQL6019) += test_function.o
