obj-y +=  vdec_vp8_if.o vdec_vp8_vpu.o

ccflags-y += \
    -I$(srctree)/include/ \
    -I$(srctree)/drivers/media/platform/mtk-vcodec \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/include \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/vp8_dec \
    -I$(srctree)/drivers/media/platform/mtk-vpu
