# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -Idrivers/media/platform/msm/camera/cam_utils
ccflags-$(CONFIG_MSM_GLOBAL_SYNX) += -Idrivers/media/platform/msm/synx
ccflags-y += -I$(src)

obj-$(CONFIG_SPECTRA_CAMERA) += cam_sync.o cam_sync_util.o
