ccflags-y += -Idrivers/media/video/msmb
ccflags-y += -Idrivers/media/video/msmb/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_isp.o msm_buf_mgr.o msm_isp_util.o msm_isp_axi_util.o msm_isp_stats_util.o
obj-$(CONFIG_MSMB_CAMERA) += msm_isp40.o
