ccflags-y += -Werror

obj-$(CONFIG_VSERVICES_PROTOCOL_BLOCK_SERVER)	+= vservices_protocol_block_server.o
vservices_protocol_block_server-objs = server.o

obj-$(CONFIG_VSERVICES_PROTOCOL_BLOCK_CLIENT)	+= vservices_protocol_block_client.o
vservices_protocol_block_client-objs = client.o
