ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_core
ccflags-y += -Idrivers/media/platform/msm/ais/cam_icp
ccflags-y += -Idrivers/media/platform/msm/ais/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/include

obj-$(CONFIG_MSM_AIS) += icp_hw_mgr/ a5_hw/ ipe_hw/ bps_hw/
