#
# Makefile for MSM Broadcast subsystem drivers.
#

obj-$(CONFIG_TSPP) += tspp.o
obj-$(CONFIG_CI_BRIDGE_SPI) += ci-bridge-spi.o
obj-$(CONFIG_ENSIGMA_UCCP_330) += ensigma_uccp330.o
obj-$(CONFIG_DEMOD_WRAPPER) += demod_wrapper.o

