# SPDX-License-Identifier: GPL-2.0
LOCAL_PATH := $(srctree)/drivers/tee/gpapi

obj-$(CONFIG_MTK_TEE_GP_TESTS) += gpapi_tests.o
gpapi_tests-y := \
	main.o \

include $(LOCAL_PATH)/Makefile.client.include
