#
# Makefile for the FTS touchscreen driver.
#

obj-$(CONFIG_TOUCHSCREEN_ST) += ftsCompensation.o \
	ftsCrossCompile.o ftsError.o ftsFrame.o ftsIO.o ftsTest.o \
	ftsTime.o ftsTool.o ftsFlash.o ftsGesture.o

