/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021 MediaTek Inc.
 * Author: Ren-Ting Wang <ren-ting.wang@mediatek.com>
 */

#ifndef _CLK_MT6895_FMETER_H
#define _CLK_MT6895_FMETER_H

/* generate from clock_table.xlsx from TOPCKGEN DE */

/* CKGEN Part */
#define FM_AXI_CK				1
#define FMP_AXI_CK				2
#define FM_U_HAXI_CK				3
#define FM_B					4
#define FM_DISP0_CK				5
#define FM_DISP1_CK				6
#define FM_MDP0_CK				7
#define FM_MDP1_CK				8
#define FM_MMINFRA_CK				9
#define FM_MMUP_CK				10
#define FM_DSP_CK				11
#define FM_DSP1_CK				12
#define FM_DSP2_CK				13
#define FM_DSP3_CK				14
#define FM_DSP4_CK				15
#define FM_DSP5_CK				16
#define FM_DSP6_CK				17
#define FM_DSP7_CK				18
#define FM_IPU_IF_CK				19
#define FM_MFG_REF_CK				20
#define FM_MFGSC_REF_CK				21
#define FM_CAMTG_CK				22
#define FM_CAMTG2_CK				23
#define FM_CAMTG3_CK				24
#define FM_CAMTG4_CK				25
#define FM_CAMTG5_CK				26
#define FM_CAMTG6_CK				27
#define FM_CAMTG7_CK				28
#define FM_CAMTG8_CK				29
#define FM_UART_CK				30
#define FM_SPI_CK				31
#define FM_MSDC5HCLK_CK				32
#define FM_MSDC_MACRO_CK			33
#define FM_MSDC30_1_CK				34
#define FM_MSDC30_2_CK				35
#define FM_AUDIO_CK				36
#define FM_AUD_INTBUS_CK			37
#define FM_PWRAP_ULPOSC_CK			38
#define FM_ATB_CK				39
#define FM_DP_CK				40
#define FM_DISP_PWM_CK				41
#define FM_USB_CK				42
#define FM_USB_XHCI_CK				43
#define FM_USB_1P_CK				44
#define FM_USB_XHCI_1P_CK			45
#define FM_I2C_CK				46
#define FM_SENINF_CK				47
#define FM_SENINF1_CK				48
#define FM_SENINF2_CK				49
#define FM_SENINF3_CK				50
#define FM_SENINF4_CK				51
#define FM_SENINF5_CK				52
#define FM_DXCC_CK				53
#define FM_AUD_ENGEN1_CK			54
#define FM_AUD_ENGEN2_CK			55
#define FM_AES_UFSFDE_CK			56
#define FM_U_CK					57
#define FM_U_MBIST_CK				58
#define FM_PEXTP_MBIST_CK			59
#define FM_AUD_1_CK				60
#define FM_AUD_2_CK				61
#define FM_ADSP_CK				62
#define FM_DPMAIF_MAIN_CK			63
#define FM_VENC_CK				64
#define FM_VDEC_CK				65
#define FM_PWM_CK				66
#define FM_AUDIO_H_CK				67
#define FM_MCUPM_CK				68
#define FM_SPMI_P_CK				69
#define FM_SPMI_M_CK				70
#define FM_TL_CK				71
#define FM_MEM_SUB_CK				72
#define FMP_MEM_CK				73
#define FM_U_MEM_CK				74
#define FM_AES_MSDCFDE_CK			75
#define FM_EMI_N_CK				76
#define FM_EMI_S_CK				77
#define FM_DSI_OCC_CK				78
#define FM_DPTX_CK				79
#define FM_CCU_AHB_CK				80
#define FM_AP2CONN_HOST_CK			81
#define FM_IMG1_CK				82
#define FM_IPE_CK				83
#define FM_CAM_CK				84
#define FM_CCUSYS_CK				85
#define FM_CAMTM_CK				86
#define FM_SFLASH_CK				87
#define FM_MCU_ACP_CK				88
#define FM_TL_P1				89
/* ABIST Part */
#define FM_LVTS_CKMON_LM			2
#define FM_LVTS_CKMON_L9			3
#define FM_LVTS_CKMON_L8			4
#define FM_LVTS_CKMON_L7			5
#define FM_LVTS_CKMON_L6			6
#define FM_LVTS_CKMON_L5			7
#define FM_LVTS_CKMON_L4			8
#define FM_LVTS_CKMON_L3			9
#define FM_LVTS_CKMON_L2			10
#define FM_LVTS_CKMON_L1			11
#define FM_RCLRPLL_DIV4_CHD			12
#define FM_RPHYPLL_DIV4_CHD			13
#define FMEM_AFT_CHD				14
#define FMEM_BFE_CHD				15
#define FM_RCLRPLL_DIV4_CHC			16
#define FM_RPHYPLL_DIV4_CHC			17
#define FMEM_AFT_CHC				18
#define FMEM_BFE_CHC				19
#define FM_RCLRPLL_DIV4_CHB			20
#define FM_RPHYPLL_DIV4_CHB			21
#define FMEM_AFT_CHB				22
#define FMEM_BFE_CHB				23
#define FM_RCLRPLL_DIV4_CHA			24
#define FM_RPHYPLL_DIV4_CHA			25
#define FMEM_AFT_CHA				26
#define FMEM_BFE_CHA				27
#define FM_ADSPPLL_CK				28
#define FM_APLL1_CK				29
#define FM_APLL2_CK				30
#define FM_APPLLGP_MON_FM_CK			31
#define FM_ARMPLL_LL_CK				32
#define FM_ARMPLL_BL_CK				33
#define FM_ARMPLL_B_CK				34
#define FM_CCIPLL_CK				35
#define FM_CSI0A_CDPHY_DELAYCAL_CK		37
#define FM_CSI0B_CDPHY_DELAYCAL_CK		38
#define FM_CSI1A_DPHY_DELAYCAL_CK		39
#define FM_CSI1B_DPHY_DELAYCAL_CK		40
#define FM_CSI2A_DPHY_DELAYCAL_CK		41
#define FM_CSI2B_DPHY_DELAYCAL_CK		42
#define FM_CSI3A_DPHY_DELAYCAL_CK		43
#define FM_CSI3B_DPHY_DELAYCAL_CK		44
#define FM_CSI4A_DPHY_DELAYCAL_CK		45
#define FM_CSI4B_DPHY_DELAYCAL_CK		46
#define FM_DSI0_LNTC_DSICLK			49
#define FM_DSI0_MPPLL_TST_CK			50
#define FM_MAINPLL_CK				52
#define FM_MDPLL1_FS26M_GUIDE			53
#define FM_MMPLL_CK				55
#define FM_MMPLL_D3_CK				56
#define FM_MPLL_CK				57
#define FM_MSDCPLL_CK				58
#define FM_IMGPLL_CK				59
#define FM_EMIPLL_CK				60
#define FM_TVDPLL_CK				61
#define FM_ULPOSC2_MON_V_VCORE_CK		62
#define FM_ULPOSC_MON_VCROE_CK			63
#define FM_UNIVPLL_CK				64
#define FM_UNIVPLL_192M_CK			66
#define FM_U_CLK2FREQ				67
#define FM_WBG_DIG_BPLL_CK			68
#define FM_WBG_DIG_WPLL_CK960			69
#define FM_466M_FMEM_INFRASYS			70
#define FM_MCUSYS_ARM_OUT_ALL			71
#define FM_APPLLGP_MON_FM_CK_2			72
#define FM_F32K_VCORE_CK			79
#define FM_UNIVPLL_DIV3_CK			84
#define FM_APLL2_CKDIV_CK			85
#define FM_APLL1_CKDIV_CK			86
#define FM_ADSPPLL_CKDIV_CK			87
#define FM_TVDPLL_CKDIV_CK			88
#define FM_MPLL_CKDIV_CK			89
#define FM_MMPLL_CKDIV_CK			90
#define FM_MAINPLL_CKDIV_CK			91
#define FM_IMGPLL_CKDIV_CK			92
#define FM_EMIPLL_CKDIV_CK			93
#define FM_MSDCPLL_CKDIV_CK			94
#define FM_PLLGP_MON_FM_CK			95
/* ABIST2 Part */
#define FM_ROSC_OUT_FREQ			1
#define FM_MMPLL_D4_CK				2
#define FM_MMPLL_D3_CK_2			3
#define FM_UNIV_499M_CK				4
#define FM_UNIV_624M_CK				5
#define FM_UNIV_832M_CK				6
#define FM_MAIN_H436P8M_CK			7
#define FM_MAIN_H546M_CK			8
#define FM_MAIN_H728M_CK			9
#define FM_SPMI_MST_32K_CK			10
#define FM_SRCK_CK				11
#define FM_ULPOSC_CORE_CK			12
#define FM_ULPOSC_CK				13
#define FM_UNIPLL_SES_CK			14
#define FM_AUD_EDTM_OUT1_M_CK			15
#define FM_AUD_EDTM_IN1_M_CK			16
#define FM_APLL_I2S9_M_CK			17
#define FM_APLL_I2S8_M_CK			18
#define FM_APLL_I2S7_M_CK			19
#define FM_APLL_I2S6_M_CK			20
#define FM_APLL_I2S5_M_CK			21
#define FM_APLL_I2S4_B_CK			22
#define FM_APLL_I2S4_M_CK			23
#define FM_APLL_I2S3_M_CK			24
#define FM_APLL_I2S2_M_CK			25
#define FM_APLL_I2S1_M_CK			26
#define FM_APLL_I2S0_M_CK			27
#define FM_CKMON4_CK				28
#define FM_CKMON3_CK				29
#define FM_CKMON2_CK				30
#define FM_CKMON1_CK				31
/* VLPCK Part */
#define FM_SCP_CK				0
#define FM_SPM_CK				1
#define FM_PWRAP_ULPOSC_CK_2			2
#define FM_GPT_BCLK_CK				3
#define FM_DXCC_CK_2				4
#define FM_SPMI_P_CK_2				5
#define FM_SPMI_M_CK_2				6
#define FM_DVFSRC_CK				7
#define FM_PWM_VLP_CK				8
#define FM_AXI_VLP_CK				9
#define FM_DBGAO_26M_CK				10
#define FM_SYSTIMER_26M_CK			11
#define FM_SSPM_CK				12
#define FM_SSPM_F26M_CK				13
#define FM_APEINT_66M_CK			14
#define FM_SRCK_CK_2				15
#define FM_SRAMRC_CK				16
#define FM_SEJ_26M_CK				17
#define FM_MD_BUCK_26M_CK			18
#define FM_SSPM_ULPOSC_CK			19
#define FM_DBGAO_66M_CK				20
#define FM_RTC_CK				21
#define FM_ULPOSC_CORE_CK_2			22
#define FM_ULPOSC_CK_2				23
#define FM_SCP_SPI_CK				24
#define FM_SCP_IIC_CK				25
#define FM_OSC_SYNC_CK				26
#define FM_OSC_SYNC_CK2				27

enum fm_sys_id {
	FM_GPU_PLL_CTRL = 0,
	FM_MFG_PLL_CTRL,
	FM_MFGSC_PLL_CTRL,
	FM_APU_PLL_CTRL,
	FM_SYS_NUM,
};

#endif /* _CLK_MT6895_FMETER_H */
