# SPDX-License-Identifier: GPL-2.0

#
# Makefile for misc devices that really don't fit anywhere else.
#

ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/inc \

obj-y		+= ../../common/v1_1/camera_hw/regulator/
obj-y		+= ../../common/v1_1/camera_hw/gpio/
obj-y		+= ../../common/v1_1/camera_hw/mclk/
obj-y		+= ../../common/v1_1/camera_hw/imgsensor_cfg_table.o
#obj-y           += imgsensor_oc.o

