obj-y += \
        mtk_mdp_regs.o \
	mtk_mdp_vpu.o \
	mtk_mdp_core.o

ccflags-y += \
    -I$(srctree)/drivers \
    -I$(srctree)/include \
    -I$(srctree)/drivers/media/platform/mtk-vcodec \
    -I$(srctree)/drivers/media/platform/mtk-vpu

