ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/inc/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/

obj-y += mtk_lpm_platform.o
obj-y += mtk_lpm_irqremain.o
obj-y += mtk_lpm_resource_ctrl.o
obj-y += mtk_lpm_rc.o
obj-y += mtk_lpm_trace.o