#
# Copyright (C) 2019 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-y += pob_main.o

obj-y += bqd_notify.o
obj-y += fpsgo_notify.o
obj-y += rs_notify.o
obj-y += qos_notify.o
obj-y += nn_notify.o
obj-y += xpu_notify.o

obj-$(CONFIG_MACH_MT6768) += platform/mt6768/
obj-$(CONFIG_MACH_MT6785) += platform/mt6785/
