# common KOs
obj-$(CONFIG_MTK_SWPM_MODULE) += v1/

# platform dependent  KOs
ifeq ($(CONFIG_MTK_SWPM_MT6853),m)
obj-$(CONFIG_MTK_SWPM_MT6853) += v6853/
endif
ifeq ($(CONFIG_MTK_SWPM_MT6873),m)
obj-$(CONFIG_MTK_SWPM_MT6873) += v6873/
endif
ifeq ($(CONFIG_MTK_SWPM_MT6885),m)
obj-$(CONFIG_MTK_SWPM_MT6885) += v6885/
endif
ifeq ($(CONFIG_MTK_SWPM_MT6893),m)
obj-$(CONFIG_MTK_SWPM_MT6893) += v6893/
endif
ifeq ($(CONFIG_MTK_SWPM_MT6983),m)
obj-$(CONFIG_MTK_SWPM_MT6983) += v6983/
endif
