ifeq ($(CONFIG_MTK_SENSOR_SUPPORT),y)
obj-y += hwmsen/
obj-y += sensor_dts/
obj-y += sensor_attributes/
obj-y += sensor_event/
obj-y += sensor_performance/
obj-y += sensor_list/
else
obj-n := hwmsen/
endif
