$(info cam_cal: common makefile start!)
custom_cam_cal := $(addsuffix /, $(shell echo $(CONFIG_CUSTOM_KERNEL_CAM_CAL_DRV)))
obj-y += $(custom_cam_cal)
$(info cam_cal: common custom_cam_cal=$(custom_cam_cal))
$(info cam_cal: common makefile end!)



