ccflags-y += -Werror

obj-$(CONFIG_VSERVICES_SERVER) += vservices_protocol_core_server.o
vservices_protocol_core_server-objs = server.o

obj-$(CONFIG_VSERVICES_CLIENT) += vservices_protocol_core_client.o
vservices_protocol_core_client-objs = client.o
