#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-y += dip/
obj-y += src/
obj-y += owe/
obj-y += rsc/
obj-y += wpe/
obj-y += dpe/
obj-y += tsf/
obj-y += mfb/
obj-y += fdvt/
