#ifndef HQSYS_PCBA
#define HQSYS_PCBA

typedef enum {
	PCBA_UNKNOW = 0,
	PCBA_K19_P0_1_CN = 0x10,
	PCBA_K19_P0_1_GLOBAL,
	PCBA_K19P_P1_INDIA,
	PCBA_K19_P1_CN_NEW,
	PCBA_K19_P1_GLOBAL_NEW,
	PCBA_K19P_P1_1_INDIA,
	PCBA_K19_P1_1_CN_NEW,
	PCBA_K19_P1_1_GLOBAL_NEW,
	PCBA_K19P_P1_1_GLOBAL,
	PCBA_K19P_P2_INDIA,
	PCBA_K19_P2_INDIA,
	PCBA_K19_P2_CN_FINAL,
	PCBA_K19_P2_CN_NEW,
	PCBA_K19_P2_GLOBAL_NEW,
	PCBA_K19P_P2_GLOBAL,
	PCBA_K19P_MP_INDIA,
	PCBA_K19_MP_INDIA,
	PCBA_K19_MP_CN_FINAL,
	PCBA_K19_MP_CN_NEW,
	PCBA_K19_MP_GLOBAL_NEW,
	PCBA_K19P_MP_GLOBAL,
	PCBA_K19_END,
	PCBA_END,
} PCBA_CONFIG;

typedef enum {
	PCBA_K19_TYPE_UNKNOW = 0,
	PCBA_K19_TYPE_CN,
	PCBA_K19_TYPE_GLOBAL,
	PCBA_K19P_TYPE_INDIA,
	PCBA_K19_TYPE_INDIA,
	PCBA_K19_TYPE_CN_NEW,
	PCBA_K19_TYPE_GLOBAL_NEW,
	PCBA_K19P_TYPE_GLOBAL,
	PCBA_K19_TYPE_CN_FINAL,
	PCBA_K19_TYPE_END,
} PCBA_K19_TYPE_CONFIG;

extern PCBA_CONFIG huaqin_pcba_config;

struct pcba_info {
	PCBA_CONFIG pcba_config;
	char pcba_name[32];
};

PCBA_CONFIG get_huaqin_pcba_config(void);

#endif
