#
# Copyright (C) 2015 MediaTek Inc.
# Copyright (C) 2018 XiaoMi, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# obj-$(CONFIG_HQ_SYSFS_SUPPORT) := hqsysfs.o
obj-y := hqsysfs.o
obj-y += hqsys_misc.o
#obj-y += hqsys_emmc_info.o
#obj-y += hqsys_cam_info.o
