ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/situation
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/sensorHub/inc_v1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp
obj-$(CONFIG_MTK_SAR_ALGO_HUB)				+=  saralgo.o
obj-$(CONFIG_MTK_SAR_ALGO_HUB)              += saralgo_factory.o