obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_i2c_driver.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_core.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_sfctrlv2.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_spi_flash.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_firmware.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_test.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_charger_detect.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_earjack_detect.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_hostcomm.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_tcs.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_platform.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_tool.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_sysfs.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_strerror.o
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += cts_oem.o

