#
# Copyright (C) 2017 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/inc \

obj-y		+= ../../common/v1_1/camera_hw/regulator/
obj-y		+= ../../common/v1_1/camera_hw/gpio/
obj-y		+= ../../common/v1_1/camera_hw/mclk/
obj-y		+= imgsensor_cfg_table.o
#obj-y           += imgsensor_oc.o
