#drivers/input/touchscreen/mediatek/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder


obj-y += focaltech_test_config_ft5x46.o
obj-y += focaltech_test_ft5x46.o
obj-y += focaltech_test_supported_ic.o
