obj-$(CONFIG_MTK_SCHEDULER) += scheduler.o
scheduler-y += sched_main.o sched_sys_common.o eas_plus.o fair.o core.o
scheduler-$(CONFIG_MTK_CORE_PAUSE)+= core_pause.o
scheduler-$(CONFIG_MTK_SCHED_BIG_TASK_ROTATE)+= rotate.o

obj-$(CONFIG_MTK_CPUFREQ_SUGOV_EXT) += cpufreq_sugov_ext.o
cpufreq_sugov_ext-y += cpufreq_sugov_main.o

