#
# (C) COPYRIGHT 2012-2013, 2016-2017 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
# SPDX-License-Identifier: GPL-2.0
#
#

include $(src)/Kbuild-mtk-custom-env

mali_kbase-y += \
	$(MALI_PLATFORM_DIR)/mali_kbase_config_mt6768.o \
	$(MALI_PLATFORM_DIR)/mali_kbase_cpu_mt6768.o \
#	mali_kbase_platform_fake.o

ccflags-y += \
	-I$(srctree)/drivers/misc/mediatek/base/power/include