obj-$(CONFIG_USE_OF) += board-dt.o
obj-$(CONFIG_ARCH_MDM9640) += board-9640.o
obj-$(CONFIG_ARCH_MDM9607) += board-9607.o
obj-$(CONFIG_ARCH_MDMCALIFORNIUM) += board-californium.o
obj-$(CONFIG_ARCH_MSM8916) += board-8952.o
obj-$(CONFIG_ARCH_MSM8937) += board-8937.o
obj-$(CONFIG_ARCH_MSMTITANIUM) += board-titanium.o
