#
# Makefile for the QCOM spcific video device drivers
# based on V4L2.
#

obj-$(CONFIG_MSM_VIDC_V4L2)     += vidc/
obj-$(CONFIG_MSM_WFD) += wfd/
obj-$(CONFIG_DVB_MPQ) += dvb/
obj-$(CONFIG_MSM_CAMERA) += camera_v1/
obj-$(CONFIG_MSMB_CAMERA) += camera_v2/
obj-y += vcap/
obj-y += broadcast/
