#
# Makefile for the QCOM spcific video device drivers
# based on V4L2.
#

obj-$(CONFIG_MSM_VIDC_V4L2)     += vidc/
obj-$(CONFIG_MSM_WFD) += wfd/
obj-$(CONFIG_MSM_CAMERA) += camera_v1/
obj-$(CONFIG_MSM_DVB) += dvb/
obj-y += vcap/
