# Goodix Touchscreen Makefile
# This Makefile is only for tempory compiling use
# Use xxxproject/Makefile-release when release driver
#
obj-m += gt9916p.o

gt9916p-y := \
				goodix_brl_i2c.o \
				goodix_brl_spi.o \
				goodix_ts_core.o \
				goodix_brl_hw.o \
				goodix_cfg_bin.o \
				goodix_ts_utils.o \
				goodix_brl_fwupdate.o \
				goodix_ts_gesture.o \
				goodix_ts_inspect.o \
				goodix_ts_tools.o
