#
# (C) COPYRIGHT 2019-2020 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program, and can also be obtained
# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA  02110-1301, USA.
#
#

ifneq ($(CONFIG_XEN),)
obj-$(CONFIG_MALI_ARBITRATION) := mali_arbif_xenfront.o
endif

mali_arbif_xenfront-y := mali_arbif_xenfront_main.o mali_arbif_adapter.o

MALI_ARBIF_TEST_API ?= 0

# Set up our defines, which will be passed to gcc
DEFINES = \
	-DMALI_ARBIF_TEST_API=$(MALI_ARBIF_TEST_API)

# Use our defines when compiling
ccflags-y += $(DEFINES)
subdir-ccflags-y += $(DEFINES)