#
# Copyright (C) 2018 XiaoMi, Inc.
# Copyright (C) 2020 XiaoMi, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-y += s5k4h7sunnymipiraw_Sensor.o

