ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb_boost
ccflags-$(CONFIG_ARCH_MT6755) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6755/include/mach
ccflags-$(CONFIG_ARCH_MT6797) += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/mt6797/include/mach
obj-y := usb_boost_plat.o
