ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb_boost
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
ccflags-$(CONFIG_MACH_MT6877) += -I$(srctree)/drivers/devfreq
obj-y := usb_boost_plat.o
