obj-$(CONFIG_MILLET_BINDER_GKI)			+= binder_gki.o
obj-$(CONFIG_MILLET_CORE)			+= millet_core.o
obj-$(CONFIG_MILLET_PKG)			+= millet_pkg.o
obj-$(CONFIG_MILLET_HS)				+= millet_hs.o
obj-$(CONFIG_MILLET_BINDER)			+= millet_binder.o
obj-$(CONFIG_MILLET_SIG)			+= millet_sig.o
obj-$(CONFIG_MILLET_CGROUP)			+= millet_oem_cgroup.o
millet_oem_cgroup-$(CONFIG_MILLET_CGROUP)	+= oem_cgroup.o
