# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/usb/typec

obj-$(CONFIG_MTK_USB_TYPEC_MUX) += mux_switch.o
obj-$(CONFIG_TYPEC_MUX_FUSB304)	+= fusb304.o
obj-$(CONFIG_TYPEC_MUX_PTN36241G) += ptn36241g.o

