# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)   +=  focaltech_test/



obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)	+=  focaltech_flash.o



obj-$(CONFIG_TOUCHSCREEN_FTS_SPI)   +=  focaltech_spi.o
