#
# Makefile for the Goodix GT1151 touchscreen driver.
#


obj-m += gt1151.o
gt1151-y += gt1x_generic.o gt1x_update.o tpd_control.o \
	    tpd_button.o  gt1x_tpd.o tpd_default.o \
	    tpd_misc.o tpd_setting.o tpd_debug.o


