
# Copyright (C) 2016 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#-I$(srctree)/drivers/misc/mediatek/base/power/drcc_v1/$(CONFIG_MTK_PLATFORM)/inc/	\
#

ccflags-y += \
	-I$(srctree)/drivers/misc/mediatek/base/power/include/	\
	-I$(srctree)/drivers/misc/mediatek/mcupm/mt6877	\
	-I$(srctree)/drivers/misc/mediatek/base/power/eem_v2/mt6877/inc	\
	-I$(srctree)/include/linux/	\
	-I$(PTP3_ROOT_DIR)/mt6877/inc	\

obj-y += mtk_ptp3_main.o

