/*
 * Copyright (C) 2015 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

/****************************************************************
* Auto generated by DE, please DO NOT modify this file directly.
*****************************************************************/

#ifndef __MT_SPM_REG__H__
#define __MT_SPM_REG__H__

#if defined(CONFIG_ARCH_MT6755)

#include "mt_spm_reg_mt6755.h"

#define WAKE_SRC_CONN2AP R12_CONN2AP_SPM_WAKEUP_B

#elif defined(CONFIG_ARCH_MT6757)

#include "mt_spm_reg_mt6757.h"

#elif defined(CONFIG_ARCH_MT6797)

#include "mt_spm_reg_mt6797.h"

#define WAKE_SRC_CONN2AP R12_CONN2AP_SPM_WAKEUP_B

#endif

#endif /* __MT_SPM_REG__H__ */
