lpm_modules_debug_cflags += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
lpm_modules_debug_cflags += -I$(LPM_MODULES_FOLDER)/include/mt6873/

lpm_modules_debug_objs += mt6873_dbg_init.o
lpm_modules_debug_objs += mt6873_dbg_fs.o
lpm_modules_debug_objs += mt6873_dbg_spm_fs.o
lpm_modules_debug_objs += mt6873_lpm_logger.o
lpm_modules_debug_objs += mt6873_lpm_trace_event.o
