#drivers/input/touchscreen/mediatek/focaltech_ts/focaltech_test/src
#
# Makefile for test module
#
# Linux driver folder


obj-y += focaltech_test.o
obj-y += focaltech_test_main.o
obj-y += focaltech_test_ini.o
obj-y += focaltech_test_global.o
obj-y += focaltech_test_detail_threshold.o
