obj-$(CONFIG_VIDEO_S5K4H8) += s5k4h8drv.o

s5k4h8drv-objs := s5k4h8yx.o dw9761.o

obj-$(CONFIG_VIDEO_T4KA3) += t4ka3drv.o

t4ka3drv-objs := t4ka3.o dw9761.o

obj-$(CONFIG_VIDEO_OV5693) += ov5693.o

ccflags-y += -Werror
