/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (C) 2023, Unisoc Inc.
 */

#ifndef __DT_BINDINGS_SPRD_UDX710_RESET_H
#define __DT_BINDINGS_SPRD_UDX710_RESET_H


/* PMU APB resets*/
#define RESET_PMU_APB_V3_MODEM_SOFT_RST			0
#define RESET_PMU_APB_PSCP_SOFT_RST			1
#define RESET_PMU_APB_V3_MODEM_PS_SOFT_RST		2
#define RESET_PMU_APB_V3_MODEM_PHY_SOFT_RST		3
#define RESET_PMU_APB_GPU_SOFT_RST			4
#define RESET_PMU_APB_AP_SOFT_RST			5
#define RESET_PMU_APB_PUB_SOFT_RST			6
#define RESET_PMU_APB_APCPU_SOFT_RST			7
#define RESET_PMU_APB_SP_SYS_SOFT_RST			8
#define RESET_PMU_APB_AUDCP_SYS_SOFT_RST		9
#define RESET_PMU_APB_AUDCP_AUDDSP_SOFT_RST		10
#define RESET_PMU_APB_AP_VDSP_SOFT_RST			11
#define RESET_PMU_APB_V3_MODEM_AON_SOFT_RST		12
#define RESET_PMU_APB_NRCP_AON_SOFT_RST			13
#define RESET_PMU_APB_NRCP_DSP_0_SOFT_RST		14
#define RESET_PMU_APB_NRCP_DSP_1_SOFT_RST		15
#define RESET_PMU_APB_AP_VSP_SOFT_RST			16
#define RESET_PMU_APB_NRCP_SYS_SOFT_RST			17


/*AON APB resets*/
#define RESET_AON_APB_RC100M_CAL_SOFT_RST			0
#define RESET_AON_APB_AON_SPI_SOFT_RST				1
#define RESET_AON_APB_DCXO_LC_SOFT_RST				2
#define RESET_AON_APB_BB_CAL_SOFT_RST				3
#define RESET_AON_APB_AON_NR_SPI_SOFT_RST			4
#define RESET_AON_APB_DAP_MTX_SOFT_RST				5
#define RESET_AON_APB_SERDES_DPHY0_SOFT_RST			6
#define RESET_AON_APB_SERDES_DPHY0_APB_SOFT_RST			7
#define RESET_AON_APB_SERDES_DPHY1_SOFT_RST			8
#define RESET_AON_APB_SERDES_DPHY1_APB_SOFT_RST			9
#define RESET_AON_APB_SERDES_DPHY2_SOFT_RST			10
#define RESET_AON_APB_SERDES_DPHY2_APB_SOFT_RST			11
#define RESET_AON_APB_SERDES0_SOFT_RST				12
#define RESET_AON_APB_SERDES1_SOFT_RST				13
#define RESET_AON_APB_SERDES2_SOFT_RST				14
#define RESET_AON_APB_RTM_SOFT_RST				15
#define RESET_AON_APB_WCN_ADDA_TEST_SOFT_RST			16
#define RESET_AON_APB_V3PS_SIM0_AON_TOP_SOFT_RST		17
#define RESET_AON_APB_V3PS_SIM1_AON_TOP_SOFT_RST		18
#define RESET_AON_APB_V3PS_SIM2_AON_TOP_SOFT_RST		19
#define RESET_AON_APB_EFUSE_SOFT_RST				20
#define RESET_AON_APB_GPIO_SOFT_RST				21
#define RESET_AON_APB_MBOX_SOFT_RST				22
#define RESET_AON_APB_KPD_SOFT_RST				23
#define RESET_AON_APB_AON_SYST_SOFT_RST				24
#define RESET_AON_APB_AP_SYST_SOFT_RST				25
#define RESET_AON_APB_AON_TMR_SOFT_RST				26
#define RESET_AON_APB_DVFS_TOP_SOFT_RST				27
#define RESET_AON_APB_APCPU_CLK_RF_SOFT_RST			28
#define RESET_AON_APB_SPLK_SOFT_RST				29
#define RESET_AON_APB_PIN_SOFT_RST				30
#define RESET_AON_APB_ANA_SOFT_RST				31
#define RESET_AON_APB_CKG_SOFT_RST				32
#define RESET_AON_APB_SEC_32K_DET_SOFT_RST			33
#define RESET_AON_APB_APCPU_TS0_SOFT_RST			34
#define RESET_AON_APB_APB_DIRECT_ACC_PROT_SOFT_RST		35
#define RESET_AON_APB_SCC_SOFT_RST				36
#define RESET_AON_APB_APB_DIRECT_ACC_PROT_PMU_APB_SOFT_RST	37
#define RESET_AON_APB_APB_DIRECT_ACC_PROT_AON_APB_SOFT_RST	38
#define RESET_AON_APB_BSMTMR_SOFT_RST				39
#define RESET_AON_APB_CSSYS_SOFT_RST				40
#define RESET_AON_APB_AON_APB_BUSMON_SOFT_RST			41
#define RESET_AON_APB_PMU_APB_BUSMON_SOFT_RST			42
#define RESET_AON_APB_AON_RFSPI_SLV_V3_SOFT_RST			43
#define RESET_AON_APB_AON_RFSPI_SLV_NR_SOFT_RST			44
#define RESET_AON_APB_THM0_SOFT_RST				45
#define RESET_AON_APB_THM1_SOFT_RST				46
#define RESET_AON_APB_AP_SIM_AON_TOP_SOFT_RST			47
#define RESET_AON_APB_PSCP_SIM0_AON_TOP_SOFT_RST		48
#define RESET_AON_APB_PSCP_SIM1_AON_TOP_SOFT_RST		49
#define RESET_AON_APB_PSCP_SIM2_AON_TOP_SOFT_RST		50
#define RESET_AON_APB_I2C_SOFT_RST				51
#define RESET_AON_APB_PMU_SOFT_RST				52
#define RESET_AON_APB_ADI_SOFT_RST				53
#define RESET_AON_APB_EIC_SOFT_RST				54
#define RESET_AON_APB_AP_INTC0_SOFT_RST				55
#define RESET_AON_APB_AP_INTC1_SOFT_RST				56
#define RESET_AON_APB_AP_INIC2_SOFT_RST				57
#define RESET_AON_APB_AP_INTC3_SOFT_RST				58
#define RESET_AON_APB_AP_INTC4_CAL_SOFT_RST			59
#define RESET_AON_APB_AP_INTC5_CAL_SOFT_RST			60
#define RESET_AON_APB_AUDCP_INTC_SOFT_RST			61
#define RESET_AON_APB_PSCP_INTC_SOFT_RST			62
#define RESET_AON_APB_V3MODEM_INTC_SOFT_RST			63
#define RESET_AON_APB_V3PS_INTC_SOFT_RST			64
#define RESET_AON_APB_V3PHY_INTC_SOFT_RST			65
#define RESET_AON_APB_NR_CR8_INTC_SOFT_RST			66
#define RESET_AON_APB_NR_DSP0_INTC_SOFT_RST			67
#define RESET_AON_APB_NR_DSP1_INTC_SOFT_RST			68
#define RESET_AON_APB_NR_INTC_SOFT_RST				69
#define RESET_AON_APB_THM2_SOFT_RST				70
#define RESET_AON_APB_AP_TMR0_SOFT_RST				71
#define RESET_AON_APB_AP_TMR1_SOFT_RST				72
#define RESET_AON_APB_AP_TMR2_SOFT_RST				73
#define RESET_AON_APB_AP_WDG_SOFT_RST				74
#define RESET_AON_APB_APCPU_WDG_SOFT_RST			75
#define RESET_AON_APB_DJTAG_AP_SOFT_RST				76
#define RESET_AON_APB_DJTAG_APCPU_SOFT_RST			77
#define RESET_AON_APB_DJTAG_NRCP_SOFT_RST			78
#define RESET_AON_APB_DJTAG_PSCP_SOFT_RST			79
#define RESET_AON_APB_DJTAG_V3_SOFT_RST				80
#define RESET_AON_APB_DJTAG_AUDCP_SOFT_RST			81
#define RESET_AON_APB_DJTAG_AON_SOFT_RST			82
#define RESET_AON_APB_DJTAG_PUB0_SOFT_RST			83
#define RESET_AON_APB_DJTAG_SOFT_RST				84


/*ap ahb reset*/
#define RESET_AP_AHB_NANDC_SOFT_RST				0
#define RESET_AP_AHB_USB0_SOFT_RST				1
#define RESET_AP_AHB_DMA_SOFT_RST				2
#define RESET_AP_AHB_SDIO_MST_SOFT_RST				3
#define RESET_AP_AHB_EMMC_SOFT_RST				4


/*ap apb reset*/
#define RESET_AP_APB_UART0_SOFT_RST				0
#define RESET_AP_APB_I2C0_SOFT_RST				1
#define RESET_AP_APB_I2C1_SOFT_RST				2
#define RESET_AP_APB_I2C2_SOFT_RST				3
#define RESET_AP_APB_I2C3_SOFT_RST				4
#define RESET_AP_APB_I2C4_SOFT_RST				5
#define RESET_AP_APB_SPI0_SOFT_RST				6
#define RESET_AP_APB_SPI1_SOFT_RST				7
#define RESET_AP_APB_SPI2_SOFT_RST				8
#define RESET_AP_APB_PWM0_SOFT_RST				9
#define RESET_AP_APB_PWM1_SOFT_RST				10
#define RESET_AP_APB_PWM2_SOFT_RST				11
#define RESET_AP_APB_PWM3_SOFT_RST				12
#define RESET_AP_APB_SIM0_SOFT_RST				13


/*ipa reset*/
#define RESET_IPA_USB1_SOFT_RST					0
#define RESET_IPA_PCIE_BUT_SOFT_RST				1
#define RESET_IPA_SDIO_SLV_SOFT_RST				2
#define RESET_IPA_PCIE_SOFT_RST					3
#define RESET_IPA_IPA_SOFT_RST					4
#define RESET_IPA_USB_PAM_SOFT_RST				5


/*audcpapb reset*/
#define RESET_AUDCP_APB_WDG_SOFT_RST				0
#define RESET_AUDCP_APB_TMR0_SOFT_RST				1
#define RESET_AUDCP_APB_TMR1_SOFT_RST				2


/*audcpahb reset*/
#define RESET_AUDCP_AHB_VBC_24M_SOFT_RST			0
#define RESET_AUDCP_AHB_DMA_AP_SOFT_RST				1
#define RESET_AUDCP_AHB_SRC48K_SOFT_RST				2
#define RESET_AUDCP_AHB_MCDT_SOFT_RST				3
#define RESET_AUDCP_AHB_VBCIFD_SOFT_RST				4
#define RESET_AUDCP_AHB_VBC_SOFT_RST				5
#define RESET_AUDCP_AHB_SPINLOCK_SOFT_RST			6
#define RESET_AUDCP_AHB_DMA_CP_SOFT_RST				7
#define RESET_AUDCP_AHB_IIS0_SOFT_RST				8
#define RESET_AUDCP_AHB_IIS1_SOFT_RST				9
#define RESET_AUDCP_AHB_IIS2_SOFT_RST				10
#define RESET_AUDCP_AHB_UART_SOFT_RST				11
#define RESET_AUDCP_AHB_AUD_SOFT_RST				12
#define RESET_AUDCP_AHB_DVFS_SOFT_RST				13


/*spahb reset*/
#define RESET_SP_AHB_ARCH_SOFT_RST				0
#define RESET_SP_AHB_IMC_SOFT_RST				1
#define RESET_SP_AHB_EIC_SOFT_RST				2
#define RESET_SP_AHB_WDG_SOFT_RST				3
#define RESET_SP_AHB_SYST_SOFT_RST				4
#define RESET_SP_AHB_TMR_SOFT_RST				5
#define RESET_SP_AHB_UART0_SOFT_RST				6
#define RESET_SP_AHB_EIC1_SOFT_RST				7

#endif

