#ifndef __MTK_CHARGER_INTF_MI_H__
#define __MTK_CHARGER_INTF_MI_H__

enum {
	STEPCHG_FCC,
	JEITA_FCC,
	THERMAL_FCC,
	BQ_FCC,
	BAT_VERIFY_FCC,
	COOL_MODE_FCC,
	NIGHT_CHG_FCC,
	CHG_MAX,
};

#endif /* __MTK_CHARGER_INTF_MI_H__ */
