#for AWINIC AW87XXX Smart K PA
#obj-$(CONFIG_SND_SOC_AW87XXX) += aw87xxx/aw87xxx.o  aw87xxx/aw87xxx_device.o  aw87xxx/aw87xxx_monitor.o  aw87xxx/aw87xxx_bin_parse.o  aw87xxx/aw87xxx_dsp.o  aw87xxx/aw87xxx_acf_bin.o
snd-soc-aw87xx-objs := aw87xxx.o
snd-soc-aw87xx-objs += aw87xxx_device.o
snd-soc-aw87xx-objs += aw87xxx_monitor.o
snd-soc-aw87xx-objs += aw87xxx_bin_parse.o
snd-soc-aw87xx-objs += aw87xxx_dsp.o
snd-soc-aw87xx-objs += aw87xxx_acf_bin.o

obj-$(CONFIG_SND_SOC_AW87XXX) += snd-soc-aw87xx.o