# SPDX-License-Identifier: GPL-2.0-only
#
# Copyright 2023 Unisoc(Shanghai) Technologies Co.Ltd
# This program is free software; you can redistribute it and/or modify it under the terms of the
# GNU General Public License as published by the Free Software Foundation; version 2.
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program;
# if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.

obj-$(CONFIG_UNISOC_BINDER) += unisoc_binder.o
unisoc_binder-$(CONFIG_UNISOC_BINDER_SCHED) += unibinder.o
unisoc_binder-$(CONFIG_UNISOC_BINDER_NETLINK) += unibinder_netlink.o
