ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor/1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor/1.0/hwmon/include
#include $(srctree)/drivers/misc/mediatek/Makefile.custom
obj-y	:=  bmi160_acc.o

