subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc_pissarro/inc
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/misc/
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/charger_pissarro/

obj-y	+= sc8551.o
