
# Makefile for the MediaTek SoCs built-in ethernet macs
#

obj-$(CONFIG_NET_MEDIATEK_MT7623)              += mtk-eth.o
mtk-eth-objs := ralink_soc_eth.o ralink_ethtool.o
mtk-eth-objs += gsw_mt7620a.o mt7530.o soc_mt7620.o mdio.o eth_reg.o
