#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_MTK_PLAT_SRAM_FLAG) += plat_dbg_info/

obj-$(CONFIG_MTK_CACHE_PARITY_CHECK) += cache_parity/
obj-$(CONFIG_MTK_L2C_PARITY_CHECK) += l2c_parity/
obj-$(CONFIG_MTK_LASTBUS_INTERFACE) += lastbus/
