#
# (C) COPYRIGHT 2012-2013 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# A copy of the licence is included with the program.
#
#



obj-y += mali_kbase_config_mediatek.o
obj-y += mali_kbase_runtime_pm.o
ifeq ($(CONFIG_MALI_DEVFREQ),y)
obj-y += mali_kbase_devfreq_mediatek.o
endif

