obj-$(CONFIG_DEVFREQ_SPRD_DDR_DVFS)		+= sprd_ddr_dvfs.o
sprd_ddr_dvfs-$(CONFIG_DEVFREQ_SPRD_DDR_DVFS) := sprd_ddr_dvfs_core.o
sprd_ddr_dvfs-$(CONFIG_DEVFREQ_SPRD_DDR_DVFS_SP)	+= sprd_ddr_dvfs_sp.o
sprd_ddr_dvfs-$(CONFIG_DEVFREQ_GOV_SPRD_VOTE)		+= sprd_governor_vote.o
