#
# Makefile for tegra baseband support.
#

GCOV_PROFILE := y

subdir-ccflags-y := -Werror

obj-$(CONFIG_TEGRA_USB_MODEM_POWER)    += tegra_usb_modem_power.o
obj-$(CONFIG_TEGRA_BB_POWER)	+= bb-power.o
obj-$(CONFIG_TEGRA_BB_OEM1)	+= bb-oem1.o
obj-$(CONFIG_TEGRA_BB_OEM2)	+= bb-oem2.o
