
obj-$(CONFIG_MTK_MET) += met_drv/
obj-$(CONFIG_MMPROFILE) += mmp/
obj-$(CONFIG_TRUSTKERNEL_TEE_SUPPORT) += tkcore/
obj-$(CONFIG_MTK_CMDQ) += cmdq/
obj-$(CONFIG_MTK_LCM) += lcm/
obj-$(CONFIG_MTK_LCM) += ext_disp/
obj-$(CONFIG_MTK_FB) += video/
obj-$(CONFIG_MTK_SYNC) += sync/
obj-${CONFIG_MTK_ATF_LOGGER} += atf/
obj-$(CONFIG_MTPROF) += mtprof/
obj-${CONFIG_MTK_ICE_DEBUG} += ice_debug/
obj-$(CONFIG_MTK_TINYSYS_SSPM_SUPPORT) += sspm/
obj-$(CONFIG_MTK_SPMTWAM) += twam/
obj-$(CONFIG_MTK_DVFSRC) += dvfsrc/
obj-$(CONFIG_MTK_AEE_FEATURE) += aee/
obj-$(CONFIG_MTK_BASE_POWER) += base/

