
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXTS) += mxt.o
#mxt-objs := atmel_mxt_ts.o plugin_cal_t37.o plugin_ac_t72.o plugin_proci.o plugin_misc.o plugin_clip.o
#mxt-objs := atmel_mxt_ts.o plugin_cal_t37.o plugin_ac_t72.o plugin_proci.o
#mxt-objs := atmel_mxt_ts.o plugin_cal_t37.o plugin_ac_t72.o
#mxt-objs := atmel_mxt_ts.o plugin_proci.o
#mxt-objs := atmel_mxt_ts.o plugin_proci.o plugin_clip.o
#mxt-objs := atmel_mxt_ts.o plugin_clip.o
mxt-objs := atmel_mxt_ts.o plugin_misc.o plugin_wdg.o
#mxt-objs := atmel_mxt_ts.o

ifeq ($(CONFIG_TOUCHSCREEN_ATMEL_MXTS),y)
#CFLAGS_atmel_mxt_ts.o += -DDEBUG
endif
