
obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT) += mxt.o
mxt-objs := atmel_mxt_ts.o plugin_cal_t37.o plugin_ac_t72.o plugin_proci.o
#mxt-objs := atmel_mxt_ts.o plugin_cal_t37.o plugin_ac_t72.o
#mxt-objs := atmel_mxt_ts.o plugin_proci.o
#mxt-objs := atmel_mxt_ts.o

