# MTK Platform Support

obj-$(CONFIG_MT_SND_SOC_V1) += common/
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_audio_v1/
obj-$(CONFIG_MT_SND_SOC_V2) += mt_soc_audio_v2/
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_audio_v3/
