ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor_bio/sensorfusion
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor_bio/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor_bio/sensorHub/inc_v1
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp/$(CONFIG_MTK_PLATFORM)
obj-y	:=  gamerotvechub.o

