/*
 *  atom_pipes.h - Intel MID Platform pipes header file
 *
 *  Copyright (C) 2014 Intel Corp
 *  Author: Ramesh Babu <ramesh.babu@intel.com>
 *  Author: Omair M Abdullah <omair.m.abdullah@intel.com>
 *  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 2 of the License.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 */

#ifndef __ATOM_PIPES_H__
#define __ATOM_PIPES_H__

#define SST_DFW_PATH_ID_SHIFT		8
#define SST_DFW_DEFAULT_CELL_NBR	0xFF

/*
 * Audio DSP Path Ids. Specified by the audio DSP FW
 */
enum sst_dfw_path_index {
	SST_DFW_PATH_INDEX_MODEM_OUT	      = (0x00 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_BT_OUT	      = (0x01 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_CODEC_OUT0	      = (0x02 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_CODEC_OUT1	      = (0x03 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_SPROT_LOOP_OUT     = (0x04 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_MEDIA_LOOP1_OUT    = (0x05 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_MEDIA_LOOP2_OUT    = (0x06 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE_OUT	      = (0x07 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_HF_SNS_OUT	      = (0x08 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_VOICE_UPLINK_REF2  = (0x08 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_HF_OUT	      = (0x09 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_VOICE_UPLINK_REF1  = (0x09 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_SPEECH_OUT	      = (0x0A << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_VOICE_UPLINK	      = (0x0A << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_RX_SPEECH_OUT      = (0x0B << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_VOICE_DOWNLINK     = (0x0B << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_VOIP_OUT	      = (0x0C << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PCM0_OUT	      = (0x0D << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PCM1_OUT	      = (0x0E << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PCM2_OUT	      = (0x0F << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PCM3_OUT	      = (0x10 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PCM4_OUT	      = (0x11 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_AWARE_OUT	      = (0x12 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_VAD_OUT	      = (0x13 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_MEDIA0_OUT	      = (0x14 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_MEDIA1_OUT	      = (0x15 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_MEDIA2_OUT	      = (0x16 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_MEDIA3_OUT	      = (0x17 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_FM_OUT	      = (0x18 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_PROBE1_PIPE_OUT    = (0x19 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE2_PIPE_OUT    = (0x1A << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE3_PIPE_OUT    = (0x1B << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE4_PIPE_OUT    = (0x1C << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE5_PIPE_OUT    = (0x1D << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE6_PIPE_OUT    = (0x1E << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE7_PIPE_OUT    = (0x1F << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE8_PIPE_OUT    = (0x20 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_SIDETONE_OUT	      = (0x21 << SST_DFW_PATH_ID_SHIFT),

	/* Start of input paths */
	SST_DFW_PATH_INDEX_MODEM_IN	      = (0x80 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_BT_IN	      = (0x81 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_CODEC_IN0	      = (0x82 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_CODEC_IN1	      = (0x83 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_SPROT_LOOP_IN      = (0x84 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_MEDIA_LOOP1_IN     = (0x85 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_MEDIA_LOOP2_IN     = (0x86 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_PROBE_IN	      = (0x87 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_SIDETONE_IN	      = (0x88 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_TX_SPEECH_IN	      = (0x89 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_SPEECH_IN	      = (0x8A << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_TONE_IN	      = (0x8B << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_VOIP_IN	      = (0x8C << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_PCM0_IN	      = (0x8D << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PCM1_IN	      = (0x8E << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PCM2_IN	      = (0x9E << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_MEDIA0_IN	      = (0x8F << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_MEDIA1_IN	      = (0x90 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_MEDIA2_IN	      = (0x91 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_FM_IN	      = (0x92 << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_PROBE1_PIPE_IN     = (0x93 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE2_PIPE_IN     = (0x94 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE3_PIPE_IN     = (0x95 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE4_PIPE_IN     = (0x96 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE5_PIPE_IN     = (0x97 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE6_PIPE_IN     = (0x98 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE7_PIPE_IN     = (0x99 << SST_DFW_PATH_ID_SHIFT),
	SST_DFW_PATH_INDEX_PROBE8_PIPE_IN     = (0x9A << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_LOW_PCM0_IN	      = (0x9D << SST_DFW_PATH_ID_SHIFT),

	SST_DFW_PATH_INDEX_RESERVED	      = (0xFF << SST_DFW_PATH_ID_SHIFT),
};

/*
 * switch matrix input path IDs
 */
enum sst_dfw_swm_inputs {
	SST_DFW_SWM_IN_MODEM		= (SST_DFW_PATH_INDEX_MODEM_IN	    |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_BT		= (SST_DFW_PATH_INDEX_BT_IN	    |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_CODEC0		= (SST_DFW_PATH_INDEX_CODEC_IN0	    |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_CODEC1		= (SST_DFW_PATH_INDEX_CODEC_IN1     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_SPROT_LOOP	= (SST_DFW_PATH_INDEX_SPROT_LOOP_IN |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_MEDIA_LOOP1	= (SST_DFW_PATH_INDEX_MEDIA_LOOP1_IN |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_MEDIA_LOOP2	= (SST_DFW_PATH_INDEX_MEDIA_LOOP2_IN |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_PROBE		= (SST_DFW_PATH_INDEX_PROBE_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_SIDETONE		= (SST_DFW_PATH_INDEX_SIDETONE_IN    |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_TXSPEECH		= (SST_DFW_PATH_INDEX_TX_SPEECH_IN   |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_SPEECH		= (SST_DFW_PATH_INDEX_SPEECH_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_TONE		= (SST_DFW_PATH_INDEX_TONE_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_VOIP		= (SST_DFW_PATH_INDEX_VOIP_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_PCM0		= (SST_DFW_PATH_INDEX_PCM0_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_PCM1		= (SST_DFW_PATH_INDEX_PCM1_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_PCM2		= (SST_DFW_PATH_INDEX_PCM2_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_MEDIA0		= (SST_DFW_PATH_INDEX_MEDIA0_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_MEDIA1		= (SST_DFW_PATH_INDEX_MEDIA1_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_MEDIA2		= (SST_DFW_PATH_INDEX_MEDIA2_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_FM		= (SST_DFW_PATH_INDEX_FM_IN	     |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_LOW_PCM0		= (SST_DFW_PATH_INDEX_LOW_PCM0_IN    |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_IN_END		= (SST_DFW_PATH_INDEX_RESERVED	     |
						SST_DFW_DEFAULT_CELL_NBR)
};

/*
 * switch matrix output path IDs
 */
enum sst_dfw_swm_outputs {
	SST_DFW_SWM_OUT_MODEM		= (SST_DFW_PATH_INDEX_MODEM_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_BT		= (SST_DFW_PATH_INDEX_BT_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_CODEC0		= (SST_DFW_PATH_INDEX_CODEC_OUT0      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_CODEC1		= (SST_DFW_PATH_INDEX_CODEC_OUT1      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_SPROT_LOOP	= (SST_DFW_PATH_INDEX_SPROT_LOOP_OUT  |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_MEDIA_LOOP1	= (SST_DFW_PATH_INDEX_MEDIA_LOOP1_OUT |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_MEDIA_LOOP2	= (SST_DFW_PATH_INDEX_MEDIA_LOOP2_OUT |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_PROBE		= (SST_DFW_PATH_INDEX_PROBE_OUT       |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_HF_SNS		= (SST_DFW_PATH_INDEX_HF_SNS_OUT      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_HF		= (SST_DFW_PATH_INDEX_HF_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_SPEECH		= (SST_DFW_PATH_INDEX_SPEECH_OUT      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_RXSPEECH	= (SST_DFW_PATH_INDEX_RX_SPEECH_OUT   |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_VOIP		= (SST_DFW_PATH_INDEX_VOIP_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_PCM0		= (SST_DFW_PATH_INDEX_PCM0_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_PCM1		= (SST_DFW_PATH_INDEX_PCM1_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_PCM2		= (SST_DFW_PATH_INDEX_PCM2_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_PCM3		= (SST_DFW_PATH_INDEX_PCM3_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_PCM4		= (SST_DFW_PATH_INDEX_PCM4_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_AWARE		= (SST_DFW_PATH_INDEX_AWARE_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_VAD		= (SST_DFW_PATH_INDEX_VAD_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_MEDIA0		= (SST_DFW_PATH_INDEX_MEDIA0_OUT      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_MEDIA1		= (SST_DFW_PATH_INDEX_MEDIA1_OUT      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_FM		= (SST_DFW_PATH_INDEX_FM_OUT	      |
						SST_DFW_DEFAULT_CELL_NBR),
	SST_DFW_SWM_OUT_END		= (SST_DFW_PATH_INDEX_RESERVED	      |
						SST_DFW_DEFAULT_CELL_NBR),
};

/*
 * Audio DSP module IDs specified by FW spec
 * TODO: Update with all modules
 */
enum sst_dfw_module_id {
	SST_DFW_MODULE_ID_PCM		  = 0x0001,
	SST_DFW_MODULE_ID_MP3		  = 0x0002,
	SST_DFW_MODULE_ID_MP24		  = 0x0003,
	SST_DFW_MODULE_ID_AAC		  = 0x0004,
	SST_DFW_MODULE_ID_AACP		  = 0x0005,
	SST_DFW_MODULE_ID_EAACP		  = 0x0006,
	SST_DFW_MODULE_ID_WMA9		  = 0x0007,
	SST_DFW_MODULE_ID_WMA10		  = 0x0008,
	SST_DFW_MODULE_ID_WMA10P	  = 0x0009,
	SST_DFW_MODULE_ID_RA		  = 0x000A,
	SST_DFW_MODULE_ID_DDAC3		  = 0x000B,
	SST_DFW_MODULE_ID_TRUE_HD	  = 0x000C,
	SST_DFW_MODULE_ID_HD_PLUS	  = 0x000D,

	SST_DFW_MODULE_ID_SRC		  = 0x0064,
	SST_DFW_MODULE_ID_DOWNMIX	  = 0x0066,
	SST_DFW_MODULE_ID_GAIN_CELL	  = 0x0067,
	SST_DFW_MODULE_ID_SPROT		  = 0x006D,
	SST_DFW_MODULE_ID_BASS_BOOST	  = 0x006E,
	SST_DFW_MODULE_ID_STEREO_WDNG	  = 0x006F,
	SST_DFW_MODULE_ID_AV_REMOVAL	  = 0x0070,
	SST_DFW_MODULE_ID_MIC_EQ	  = 0x0071,
	SST_DFW_MODULE_ID_SPL		  = 0x0072,
	SST_DFW_MODULE_ID_ALGO_VTSV	  = 0x0073,
	SST_DFW_MODULE_ID_NR		  = 0x0076,
	SST_DFW_MODULE_ID_BWX		  = 0x0077,
	SST_DFW_MODULE_ID_DRP		  = 0x0078,
	SST_DFW_MODULE_ID_MDRP		  = 0x0079,

	SST_DFW_MODULE_ID_ANA		  = 0x007A,
	SST_DFW_MODULE_ID_AEC		  = 0x007B,
	SST_DFW_MODULE_ID_NR_SNS	  = 0x007C,
	SST_DFW_MODULE_ID_SER		  = 0x007D,
	SST_DFW_MODULE_ID_AGC		  = 0x007E,

	SST_DFW_MODULE_ID_CNI		  = 0x007F,
	SST_DFW_MODULE_ID_CONTEXT_ALGO_AWARE  = 0x0080,
	SST_DFW_MODULE_ID_FIR_24	  = 0x0081,
	SST_DFW_MODULE_ID_IIR_24	  = 0x0082,

	SST_DFW_MODULE_ID_ASRC		  = 0x0083,
	SST_DFW_MODULE_ID_TONE_GEN	  = 0x0084,
	SST_DFW_MODULE_ID_BMF		  = 0x0086,
	SST_DFW_MODULE_ID_EDL		  = 0x0087,
	SST_DFW_MODULE_ID_GLC		  = 0x0088,

	SST_DFW_MODULE_ID_FIR_16	  = 0x0089,
	SST_DFW_MODULE_ID_IIR_16	  = 0x008A,
	SST_DFW_MODULE_ID_DNR		  = 0x008B,

	SST_DFW_MODULE_ID_VIRTUALIZER	  = 0x008C,
	SST_DFW_MODULE_ID_VISUALIZATION	  = 0x008D,
	SST_DFW_MODULE_ID_LOUDNESS_OPTIMIZER  = 0x008E,
	SST_DFW_MODULE_ID_REVERBERATION	  = 0x008F,

	SST_DFW_MODULE_ID_CNI_TX	  = 0x0090,
	SST_DFW_MODULE_ID_REF_LINE	  = 0x0091,
	SST_DFW_MODULE_ID_VOLUME	  = 0x0092,
	SST_DFW_MODULE_ID_FILT_DCR	  = 0x0094,
	SST_DFW_MODULE_ID_SLV		  = 0x009A,
	SST_DFW_MODULE_ID_NLF		  = 0x009B,
	SST_DFW_MODULE_ID_TNR		  = 0x009C,
	SST_DFW_MODULE_ID_WNR		  = 0x009D,

	SST_DFW_MODULE_ID_LOG		  = 0xFF00,

	SST_DFW_MODULE_ID_TASK		  = 0xFFFF,
};
#endif /* __ATOM_PIPES_H__ */
