ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/

ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/inc/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/mtk_lpm_trace_event/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/modules/include/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/modules/include/mt6779/

obj-y += mt6779.o
obj-y += mtk_lp_plat_apmcu.o
obj-y += mtk_lp_plat_apmcu_mbox.o
obj-y += mt6779_ipi_sspm.o

obj-y += idles/mt6779_mcusys.o
obj-y += suspend/mt6779_suspend.o
