# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/

obj-$(CONFIG_MTK_PMIC_PROTECT) += mt63xx-oc-debug.o
obj-$(CONFIG_MTK_PMIC_PROTECT) += mtk-pmic-oc-debug.o
