ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_cpas/cpas_top
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_cpas/camss_top

obj-$(CONFIG_SPECTRA_CAMERA) += cpas_top/
obj-$(CONFIG_SPECTRA_CAMERA) += camss_top/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_cpas_soc.o cam_cpas_intf.o cam_cpas_hw.o