// SPDX-License-Identifier: GPL-2.0
#ifeq ($(CONFIG_MTK_SND_SOC_NEW_ARCH),y)
#subdir-ccflags-y += -DAUDIO_USING_WRAP
#endif
snd-mtk-soc-codec-6357-objs += mtk-soc-codec-6357.o mtk-auddrv-ana.o
obj-$(CONFIG_SND_SOC_CODEC_MT6357) += snd-mtk-soc-codec-6357.o