#
# Makefile for the Qualcomm Technologies, Inc. EMAC Gigabit Ethernet driver
#

obj-$(CONFIG_QCOM_EMAC) += qcom_emac.o

qcom_emac-objs := emac_main.o emac_hw.o emac_ethtool.o emac_ptp.o
qcom_emac-objs += emac_phy.o emac_rgmii.o emac_sgmii.o
