# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for USB Power Delivery drivers
#

obj-$(CONFIG_USB_PD_POLICY)	+= policy_engine.o
obj-$(CONFIG_USB_PD_POLICY_MUNCH)	+= policy_engine_munch.o
obj-$(CONFIG_USB_PD_POLICY_DAGU)	+= policy_engine_dagu.o
obj-$(CONFIG_QPNP_USB_PDPHY)	+= qpnp-pdphy.o
obj-$(CONFIG_PS5169)			+= ps5169.o
