subdir-ccflags-y += -Werror

obj-$(CONFIG_MTK_CMDQ) += mtk-cmdq-helper.o
obj-$(CONFIG_MTK_INFRACFG) += mtk-infracfg.o
obj-$(CONFIG_MTK_PMIC_WRAP) += mtk-pmic-wrap.o
obj-$(CONFIG_MTK_SCPSYS) += mtk-scpsys.o mtk-scpsys-bringup.o
obj-$(CONFIG_MTK_SCPSYS_MT8163) += mtk-scpsys-mt8163.o
