#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/mt8173

obj-$(CONFIG_MTK_INFRACFG) += mtk-infracfg.o
obj-$(CONFIG_MTK_SCPSYS_MT8173) += mtk-scpsys.o
obj-$(CONFIG_MTK_SCPSYS_MT8163) += mtk-scpsys-mt8163.o
obj-$(CONFIG_MTK_SCPSYS_MT2701) += mtk-scpsys-mt2701.o mtk-scpsys-bringup.o
obj-$(CONFIG_MTK_SCPSYS_MT8127) += mtk-scpsys-mt8127.o mtk-scpsys-bringup.o
obj-$(CONFIG_MTK_PMIC_WRAP_COMMON) += mtk-pmic-wrap.o
