# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_MTK_EMI)	+= emi-cen.o
obj-$(CONFIG_MTK_EMI)  += emi-mpu.o
obj-$(CONFIG_MTK_EMI)  += emi-dbg.o
obj-$(CONFIG_MTK_EMI)  += emi-isu.o
obj-$(CONFIG_MTK_EMI_MPU_TEST) += emi-mpu-test.o
obj-$(CONFIG_MTK_DRAMC)    += mtk_dramc.o
mtk_dramc-objs	+= dramc.o dramc_bin.o
