#
# Makefile for misc devices that really don't fit anywhere else.
#
ifeq ($(CONFIG_MTK_PLATFORM), "mt6873")
obj-$(CONFIG_MTK_LENS)   += main_6873/
else
obj-$(CONFIG_MTK_LENS)   += main/
endif
obj-$(CONFIG_MTK_LENS)   += main2/
obj-$(CONFIG_MTK_LENS)   += main3/
obj-$(CONFIG_MTK_LENS)   += sub/
obj-$(CONFIG_MTK_LENS)   += sub2/
