subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc


obj-m += xmc_main.o xmc_voter.o xmc_ops.o
xmc_main-objs := xmc_core.o xmc_sysfs.o xmc_monitor.o xmc_detection.o xmc_adapter.o xmc_pdm.o bq27z561.o max77932.o sc8561.o
