lpm_modules_debug_cflags += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
lpm_modules_debug_cflags += -I$(LPM_MODULES_FOLDER)/include/mt6853/

lpm_modules_debug_objs += mt6853_dbg_init.o
lpm_modules_debug_objs += mt6853_dbg_fs.o
lpm_modules_debug_objs += mt6853_dbg_spm_fs.o
lpm_modules_debug_objs += mt6853_lpm_logger.o
lpm_modules_debug_objs += mt6853_lpm_trace_event.o
