include $(srctree)/drivers/misc/mediatek/Makefile.custom


ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

#target
obj-y   +=  RefCode_CustomerImplementation.o
obj-y   +=  RefCode_F54_FullRawCap.o
obj-y   +=  RefCode_F54_HighResistance.o
obj-y   +=  RefCode_F54_RxOpenReport.o
obj-y   +=  RefCode_F54_RxToRxReport.o
obj-y   +=  RefCode_F54_TxOpenReport.o
obj-y   +=  RefCode_F54_TxToGndReport.o
obj-y   +=  RefCode_F54_TxToTxReport.o
obj-y   +=  RefCode_FWCheck.o
obj-y   +=  RefCode_PDTScan.o
obj-y   +=  s2200_driver.o
obj-y   +=  s2200_fw_update.o