# UAPI Header export list
header-y += lsm_params.h
header-y += audio_slimslave.h
header-y += audio_effects.h
header-y += devdep_params.h
header-y += msmcal-hwdep.h
header-y += wcd-dsp-glink.h
header-y += voice_params.h
