ccflags-$(CONFIG_DRM_MEDIATEK_V2) += -I$(srctree)/drivers/gpu/drm/mediatek/mediatek_v2/
obj-m += icnl9916_spi.o
icnl9916_spi-y += cts_driver.o
icnl9916_spi-y += cts_core.o
icnl9916_spi-y += cts_sfctrlv2.o
icnl9916_spi-y += cts_spi_flash.o
icnl9916_spi-y += cts_firmware.o
icnl9916_spi-y += cts_test.o
icnl9916_spi-y += cts_charger_detect.o
icnl9916_spi-y += cts_earjack_detect.o
icnl9916_spi-y += cts_tcs.o
icnl9916_spi-y += cts_platform.o
icnl9916_spi-y += cts_tool.o
icnl9916_spi-y += cts_sysfs.o
icnl9916_spi-y += cts_strerror.o
icnl9916_spi-y += cts_oem.o

