obj-$(CONFIG_QRTR) := qrtr.o

obj-$(CONFIG_QRTR_SMD) += qrtr-smd.o
qrtr-smd-y	:= smd.o
obj-$(CONFIG_QRTR_TUN) += qrtr-tun.o
qrtr-tun-y	:= tun.o
obj-$(CONFIG_QRTR_MHI) += qrtr-mhi.o
qrtr-mhi-y	:= mhi.o

obj-$(CONFIG_QRTR_USB) += qrtr-usb.o
qrtr-usb-y      := usb.o

obj-$(CONFIG_QRTR_FIFO) += qrtr-fifo.o
qrtr-fifo-y	:= fifo.o
