# Makefile for intel vlv display driver

ccflags-y := -Idrivers/staging/ -Iinclude/adf -Iinclude/uapi/adf -Idrivers/video/adf/intel/include -Werror

obj-y := vlv_dc_config.o \
	vlv_pri_plane.o \
	vlv_sp_plane.o \
	vlv_mode_set.o \
	vlv_dpst.o \
	vlv_debugfs.o \
	vlv_pipe.o \
	vlv_pll.o \
	vlv_dsi_pll.o \
	vlv_pm.o \
	vlv_dsi_port.o \
	vlv_dsi_port_cmd.o
