#
# Makefile for the Novatek NT36xxx touchscreen driver.
#
# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_NT36672C_SPI) += nvt_36672c.o
nvt_36672c-y += nt36xxx.o 
nvt_36672c-y += nt36xxx_fw_update.o 
nvt_36672c-y += nt36xxx_ext_proc.o
nvt_36672c-y += nt36xxx_mp_ctrlram.o
