# SPDX-License-Identifier: GPL-2.0
#
# USB peripheral controller drivers
#

ccflags-y += -I$(srctree)/drivers/usb/gadget
ccflags-y += -I$(srctree)/drivers/usb/gadget/function

obj-$(CONFIG_MTK_USB_META)	+= meta.o
