obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC) += vdec_mpeg4_if.o vdec_mpeg4_vpu.o

ccflags-y += \
    -I$(srctree)/include \
    -I$(srctree)/drivers/media/platform/mtk-vcodec \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/include \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/mpeg4_dec \
    -I$(srctree)/drivers/media/platform/mtk-vpu
