# SPDX-License-Identifier: GPL-2.0

#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/inc \

obj-y		+= regulator/
obj-y		+= gpio/
obj-y		+= mclk/
obj-y		+= imgsensor_cfg_table.o
