// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2019 MediaTek Inc.
 */


/* This file is generated by GenLP_setting.pl v1.5.7 */

#include <linux/init.h>
#include <linux/module.h>
#include <linux/kernel.h>

const unsigned int AP_PMIC_REG_MT6319_gs_suspend_32kless_data[] = {
	/*  Address     Mask        Golden Setting Value */
	0x13, 0x2, 0x2,/* TOP_CON */
	0x15, 0x1F, 0x1F,/* TEST_CON0 */
	0x22, 0x12, 0x12,/* SMT_CON0 */
	0x10B, 0x3, 0x3,/* TOP_CKPDN_CON0 */
	0x193, 0x3, 0x3,/* PMRC_CON1 */
	0x196, 0x4, 0x4,/* VDIG18_CON0 */
	0x1440, 0xF, 0xD,/* BUCK_TOP_CON0 */
	0x1443, 0x4, 0x4,/* BUCK_TOP_CON1 */
	0x148D, 0x1, 0x1,/* BUCK_VBUCK1_OP_EN_0 */
	0x1493, 0x1, 0x1,/* BUCK_VBUCK1_OP_CFG_0 */
	0x1496, 0x1, 0x1,/* BUCK_VBUCK1_OP_MODE_0 */
	0x160D, 0x1, 0x1,/* BUCK_VBUCK4_OP_EN_0 */
	0x1613, 0x1, 0x1,/* BUCK_VBUCK4_OP_CFG_0 */
	0x1616, 0x1, 0x1,/* BUCK_VBUCK4_OP_MODE_0 */
};

const unsigned int *AP_PMIC_REG_6319_gs_suspend_32kless =
				AP_PMIC_REG_MT6319_gs_suspend_32kless_data;

unsigned int AP_PMIC_REG_6319_gs_suspend_32kless_len = 42;

const unsigned int AP_PMIC_REG_MT6319_gs_deepidle___lp_mp3_32kless_data[] = {
	/*  Address     Mask        Golden Setting Value */
	0x13, 0x2, 0x0,/* TOP_CON */
	0x15, 0x1F, 0x1F,/* TEST_CON0 */
	0x22, 0x12, 0x12,/* SMT_CON0 */
	0x10B, 0x3, 0x3,/* TOP_CKPDN_CON0 */
	0x193, 0x3, 0x3,/* PMRC_CON1 */
	0x196, 0x4, 0x4,/* VDIG18_CON0 */
	0x1440, 0xF, 0xD,/* BUCK_TOP_CON0 */
	0x1443, 0x4, 0x4,/* BUCK_TOP_CON1 */
	0x148D, 0x1, 0x1,/* BUCK_VBUCK1_OP_EN_0 */
	0x1493, 0x1, 0x1,/* BUCK_VBUCK1_OP_CFG_0 */
	0x1496, 0x1, 0x1,/* BUCK_VBUCK1_OP_MODE_0 */
	0x160D, 0x1, 0x1,/* BUCK_VBUCK4_OP_EN_0 */
	0x1613, 0x1, 0x1,/* BUCK_VBUCK4_OP_CFG_0 */
	0x1616, 0x1, 0x1,/* BUCK_VBUCK4_OP_MODE_0 */
	0x170B, 0x1, 0x1,/* BUCK_VBUCK1_OP_CFG_2 */
	0x170E, 0x1, 0x1,/* BUCK_VBUCK1_OP_MODE_2 */
	0x1711, 0x1, 0x0,/* BUCK_VBUCK2_OP_EN_2 */
	0x1714, 0x1, 0x1,/* BUCK_VBUCK2_OP_CFG_2 */
	0x1717, 0x1, 0x1,/* BUCK_VBUCK2_OP_MODE_2 */
	0x171A, 0x1, 0x0,/* BUCK_VBUCK3_OP_EN_2 */
	0x171D, 0x1, 0x1,/* BUCK_VBUCK3_OP_CFG_2 */
	0x1720, 0x1, 0x1,/* BUCK_VBUCK3_OP_MODE_2 */
	0x1723, 0x1, 0x0,/* BUCK_VBUCK4_OP_EN_2 */
	0x1726, 0x1, 0x1,/* BUCK_VBUCK4_OP_CFG_2 */
	0x1729, 0x1, 0x1 /* BUCK_VBUCK4_OP_MODE_2 */
};

const unsigned int *AP_PMIC_REG_6319_gs_deepidle___lp_mp3_32kless =
			AP_PMIC_REG_MT6319_gs_deepidle___lp_mp3_32kless_data;

unsigned int AP_PMIC_REG_6319_gs_deepidle___lp_mp3_32kless_len = 75;

const unsigned int AP_PMIC_REG_MT6319_gs_sodi3p0_32kless_data[] = {
	/*  Address     Mask        Golden Setting Value */
	0x13, 0x2, 0x2,/* TOP_CON */
	0x15, 0x1F, 0x1F,/* TEST_CON0 */
	0x22, 0x12, 0x12,/* SMT_CON0 */
	0x10B, 0x3, 0x3,/* TOP_CKPDN_CON0 */
	0x193, 0x3, 0x3,/* PMRC_CON1 */
	0x196, 0x4, 0x4,/* VDIG18_CON0 */
	0x1440, 0xF, 0xD,/* BUCK_TOP_CON0 */
	0x1443, 0x4, 0x4,/* BUCK_TOP_CON1 */
	0x148D, 0x1, 0x1,/* BUCK_VBUCK1_OP_EN_0 */
	0x1493, 0x1, 0x1,/* BUCK_VBUCK1_OP_CFG_0 */
	0x1496, 0x1, 0x1,/* BUCK_VBUCK1_OP_MODE_0 */
	0x160D, 0x1, 0x1,/* BUCK_VBUCK4_OP_EN_0 */
	0x1613, 0x1, 0x1,/* BUCK_VBUCK4_OP_CFG_0 */
	0x1616, 0x1, 0x1,/* BUCK_VBUCK4_OP_MODE_0 */
};

const unsigned int *AP_PMIC_REG_6319_gs_sodi3p0_32kless =
				AP_PMIC_REG_MT6319_gs_sodi3p0_32kless_data;

unsigned int AP_PMIC_REG_6319_gs_sodi3p0_32kless_len = 42;
