ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/ais/cam_core

obj-$(CONFIG_MSM_AIS) += cam_eeprom_dev.o cam_eeprom_core.o cam_eeprom_soc.o
