# Makefile for Intel display driver based on ADF framework
ccflags-y := -Idrivers/staging/ -Iinclude/adf -Iinclude/uapi/adf -Idrivers/video/adf/intel/include -Werror

obj-y = gen_dp_pipe.o \
	dp_panel.o
