# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

subdir-ccflags-y += -D SUPPORT_SPEED_SCREEN_UNBLANK

obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_SILEAD_FP) += silead/

