# SPDX-License-Identifier: GPL-2.0
# Generic UNISOC MAILBOX API
obj-$(CONFIG_UNISOC_MAILBOX)			+= unisoc-mailbox.o
unisoc-mailbox-y				:= unisoc-mailbox-hal.o
unisoc-mailbox-$(CONFIG_UNISOC_MAILBOX_R1)	+= unisoc-mailbox-phy-r1.o
unisoc-mailbox-$(CONFIG_UNISOC_MAILBOX_R2)	+= unisoc-mailbox-phy-r2.o
