ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor/2.0/core
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor/2.0/sensorhub

obj-y += test.o
obj-y += test1.o
obj-y += test2.o
obj-y += test3.o
obj-y += test4.o
