ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_cdm
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_fd
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_fd/fd_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_fd/fd_hw_mgr/fd_hw
ccflags-y += -Idrivers/media/platform/msm/camera_v3
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += fd_hw_mgr/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_fd_dev.o cam_fd_context.o
