ccflags-y += -I$(srctree)/drivers/media/platform/msm/vidc/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/vidc/vmem/

msm-vidc-vmem-objs := vmem.o \
                      vmem_debugfs.o

obj-$(CONFIG_MSM_VIDC_VMEM) := msm-vidc-vmem.o
