#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC_FOD)	+= fpc_fod/
obj-$(CONFIG_FINGERPRINT_GOODIX_FOD)	+= goodix_fod/
obj-$(CONFIG_FINGERPRINT_GOODIX_FOD_LMI)	+= goodix_fod_lmi/
