#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_XIAOMI_FP)     += xiaomi_fp/
obj-$(CONFIG_FINGERPRINT_FPC_TEE)       += fpc_1553/
