#
# Makefile for the fingerprint drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_XIAOMI_FP)     += xiaomi_fp/
obj-$(CONFIG_FINGERPRINT_GOODIX_3626)    += goodix_3626/
