# In case the platform does NOT support this type of sensors
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include

obj-y += uncali_gyro.o
obj-$(CONFIG_MTK_UNCALI_GYROHUB)		+=	uncali_gyrohub/

