// SPDX-License-Identifier: GPL-2.0
#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#


# To handle circular dependency between common_int and mt6765 APIS
# module ko is combined with mtk-soc-sound-cycle-dependent inside
# sound/soc/mediatek/common_int/Makefile

# AP object
#obj-$(CONFIG_SND_SOC_MT6765) += mtk-auddrv-clk.o