#
# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2019 MediaTek Inc.
#
obj-$(CONFIG_MTK_ATF_LOGGER) := atf_logger.o
atf_logger-$(CONFIG_MTK_ATF_LOGGER) := tfa_debug.o
atf_logger-$(CONFIG_MTK_ATF_LOGGER) += atf_log.o
