#
# Makefile for the keyboard drivers.
#

obj-$(CONFIG_KEYBOARD_NANO_8030_V2) += nanosic_driver_v2.o
nanosic_driver_v2-y += nano_chardev.o nano_sysfs.o nano_workqueue.o nano_driver.o nano_i2c.o nano_input.o nano_timer.o nano_gpio.o nano_cache.o nano_pm.o

