# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XM_POWER_SUPPLY)	+= xm_charger.o
xm_charger-objs := xm_charger_core.o xm_charger_votable.o xm_charger_ffc.o \
		xm_charger_thermal.o step-chg-jeita.o xm_charger_feature.o
