ccflags-y += -Idrivers/media/platform/msm/camera_v3
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_hyp_intf
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_utils
obj-$(CONFIG_SPECTRA_CAMERA) += cam_hyp_intf.o
