# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Unisoc WCN sdio configuration
#

obj-y += sdiohal_main.o
obj-y += sdiohal_common.o
obj-y += sdiohal_tx.o
obj-y += sdiohal_rx.o
obj-y += sdiohal_if.o

# obj-$(CONFIG_DEBUG_FS) += sdiohal_ctl.o
