# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/dma-buf/heaps
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cameraisp/src/common

obj-$(CONFIG_MTK_CAMERA_MEM_SUPPORT) += camera_mem.o
