ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/

ccflags-y += -I$(srctree)/drivers/misc/mediatek/lpm/inc/

obj-y += mtk_lp_plat_apmcu.o
obj-y += mtk_lp_plat_apmcu_mbox.o

obj-y += mtk_lp_platform.o
