# SPDX-License-Identifier: GPL-2.0
#
#  Copyright (C) 2017 MediaTek Inc.
#

ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include/power_gs_v1/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include/power_gs_v1/$(MTK_PLATFORM)/

obj-y += mtk_power_gs_6359_array.o
obj-y += mtk_cg_array.o
obj-y += mtk_dcm_array.o
obj-y += mtk_power_gs_sp.o
obj-y += mtk_power_gs_compare.o
obj-y += mtk_power_gs_dump_pmic.o
