obj-$(CONFIG_VIDEO_OV5648)     += ov5648.o
obj-$(CONFIG_VIDEO_OV2680)     += ov2680.o
obj-$(CONFIG_VIDEO_GC2155)     += gc2155.o
obj-$(CONFIG_VIDEO_GC0310)     += gc0310.o

obj-$(CONFIG_VCM_WV511)      += wv511.o
obj-$(CONFIG_VCM_DW9714)     += dw9714.o
