# MTK Platform Support

include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MT_SND_SOC_V1) += AudDrv_Afe.o AudDrv_Ana.o AudDrv_Clk.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_afe_control.o mt_soc_afe_connection.o mt_soc_pcm_common.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_capture.o mt_soc_pcm_dl1.o mt_soc_pcm_dummy.o mt_soc_pcm_routing.o mt_soc_pcm_capture2.o mt_soc_pcm_mod_adci2s.o mt_soc_pcm_adc2_adci2s2.o mt_soc_pcm_io2_awb.o 
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_voice.o mt_soc_pcm_voice_ext.o mt_soc_pcm_voice_extint.o mt_soc_pcm_voice_bt.o mt_soc_pcm_voice_ext_bt.o mt_soc_pcm_voice_extint_bt.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_hdmi.o mt_soc_pcm_dl1_i2s0.o mt_soc_pcm_dl1_i2s0Dl1.o mt_soc_pcm_i2s0_awb.o 
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_uldlloopback.o 
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_mrgrx.o mt_soc_pcm_mrgrx_awb.o 
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_dl1_awb.o mt_soc_pcm_dl1_bt.o mt_soc_pcm_bt_dai.o mt_soc_pcm_mod_dai.o 
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_dai_stub.o mt_soc_dai_routing.o mt_soc_codec_dummy.o mt_soc_codec_63xx.o mt_soc_pcm_fmtx.o mt_soc_tdm_capture.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_pcm_hp_impedance.o
obj-$(CONFIG_MT_SND_SOC_V1) += mt_soc_machine.o
obj-$(CONFIG_MTK_SPEAKER) += mt_soc_codec_speaker_63xx.o
