include $(srctree)/drivers/misc/mediatek/Makefile.custom

# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/atmel336t/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/

obj-y	+=  atmel_mxt_ts.o
obj-y	+=  plugin_misc.o
obj-y	+=  plugin_wdg.o

