#
# Makefile for the FT5X46 touchscreen driver.
#

obj-$(CONFIG_TOUCHSCREEN_FT5X46)	+= ft5x46_ts.o
obj-$(CONFIG_TOUCHSCREEN_FT5X46_I2C)	+= ft5x46_ts_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FT5X46_SPI)	+= ft5x46_ts_spi.o
