snd-soc-sdm660-cdc-objs := msm-analog-cdc.o msm-digital-cdc.o sdm660-regmap.o
obj-$(CONFIG_SND_SOC_SDM660_CDC) += snd-soc-sdm660-cdc.o sdm660-cdc-irq.o
snd-soc-tas2557-objs := tas2557-core.o tas2557-regmap.o tas2557-codec.o tas2557-misc.o tiload.o
obj-$(CONFIG_SND_SOC_TAS2557) += snd-soc-tas2557.o
snd-soc-dbmdx-objs := dbmdx.o dbmdx-spi.o dbmdx-i2c.o dbmdx-i2c-d2.o dbmdx-i2c-d4.o dbmdx-spi-d2.o dbmdx-spi-d4.o dbmdx-uart-d2.o dbmdx-uart-d4.o dbmdx-uart.o dbmdx-i2s.o dbmdx-customer.o dbmdx-cdev.o
obj-$(CONFIG_SND_SOC_DBMDX) += snd-soc-dbmdx.o
snd-soc-dbmdx-snd-capture-objs := dbmdx-snd.o dbmdx-snd-pcm.o
obj-$(CONFIG_SND_SOC_DBMDX_SND_CAPTURE) += snd-soc-dbmdx-snd-capture.o
