subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/misc/
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/charger_pissarro/

obj-y	+= xmusb350.o
obj-y	+= pd_cp_manager.o
obj-y	+= qc_cp_manager.o
