/*
 * Copyright (C) 2019 MediaTek Inc.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 */

#ifndef __APUSYS_CMD_FORMAT_H__
#define __APUSYS_CMD_FORMAT_H__

#define APUSYS_MAGIC_NUMBER 0x3d2070ece309c231
#define APUSYS_CMD_VERSION 0x1

/* header column size */
#define TYPE_APUSYS_MAGIC                   uint64_t
#define TYPE_APUSYS_CMD_ID                  uint64_t
#define TYPE_APUSYS_CMD_VERSION             uint8_t
#define TYPE_PRIORITY                       uint8_t
#define TYPE_TARGET_TIME                    uint16_t
#define TYPE_DEADLINE                       uint32_t
#define TYPE_NUM_OF_SUBGRAPH                uint32_t
#define TYPE_OFFSET_TO_DEPENDENCY_INFO_LIST uint32_t
#define TYPE_SUBGRAPH_INFO_POINTER          uint32_t

#define TYPE_DEPENDENCY_ELEMENT             uint32_t

#define SIZE_APUSYS_MAGIC \
	(sizeof(TYPE_APUSYS_MAGIC))
#define SIZE_APUSYS_CMD_ID \
	(sizeof(TYPE_APUSYS_CMD_ID))
#define SIZE_APUSYS_CMD_VERSION \
	(sizeof(TYPE_APUSYS_CMD_VERSION))
#define SIZE_PRIORITY \
	(sizeof(TYPE_PRIORITY))
#define SIZE_TARGET_TIME \
	(sizeof(TYPE_TARGET_TIME))
#define SIZE_DEADLINE \
	(sizeof(TYPE_DEADLINE))
#define SIZE_NUM_OF_SUBGRAPH \
	(sizeof(TYPE_NUM_OF_SUBGRAPH))
#define SIZE_OFFSET_TO_DEPENDENCY_INFO_LIST \
	(sizeof(TYPE_OFFSET_TO_DEPENDENCY_INFO_LIST))

#define SIZE_APUSYS_HEADER \
	(SIZE_APUSYS_MAGIC + SIZE_APUSYS_CMD_ID +\
	SIZE_APUSYS_CMD_VERSION + SIZE_PRIORITY +\
	SIZE_TARGET_TIME + SIZE_DEADLINE + SIZE_NUM_OF_SUBGRAPH +\
	SIZE_OFFSET_TO_DEPENDENCY_INFO_LIST)

#define SIZE_DEPENDENCY_ELEMENT \
	(sizeof(TYPE_DEPENDENCY_ELEMENT))
#define SIZE_SUBGRAPH_INFO_POINTER \
	(sizeof(TYPE_SUBGRAPH_INFO_POINTER))

/* header offset */
#define OFFSET_APUSYS_MAGIC \
	(0)
#define OFFSET_APUSYS_CMD_ID \
	(OFFSET_APUSYS_MAGIC + SIZE_APUSYS_MAGIC)
#define OFFSET_APUSYS_CMD_VERSION \
	(OFFSET_APUSYS_CMD_ID + SIZE_APUSYS_CMD_ID)
#define OFFSET_PRIORITY \
	(OFFSET_APUSYS_CMD_VERSION + SIZE_APUSYS_CMD_VERSION)
#define OFFSET_TARGET_TIME \
	(OFFSET_PRIORITY + SIZE_PRIORITY)
#define OFFSET_DEADLINE \
	(OFFSET_TARGET_TIME + SIZE_TARGET_TIME)
#define OFFSET_NUM_OF_SUBGRAPH \
	(OFFSET_DEADLINE + SIZE_DEADLINE)
#define OFFSET_OFFSET_TO_DEPENDENCY_INFO_LIST \
	(OFFSET_NUM_OF_SUBGRAPH + SIZE_NUM_OF_SUBGRAPH)
#define OFFSET_SUBGRAPH_INFO_OFFSET_LIST \
	(OFFSET_OFFSET_TO_DEPENDENCY_INFO_LIST \
	+ SIZE_OFFSET_TO_DEPENDENCY_INFO_LIST)

/* specific subgratph size */
#define TYPE_SUBGRAPH_TYPE              uint32_t
#define TYPE_SUBGRAPH_TARGET_TIME       uint32_t
#define TYPE_SUBGRAPH_UP_TURNAROUND     uint64_t
#define TYPE_SUBGRAPH_DRIVER_TURNAROUND uint64_t
#define TYPE_SUBGRAPH_TCM_USAGE         uint32_t
#define TYPE_SUBGRAPH_TCM_FORCE         uint32_t
#define TYPE_SUBGRAPH_CTX_ID            uint32_t
#define TYPE_SUBGRAPH_SIZE              uint32_t
#define TYPE_SUBGRAPH_ADDR              uint64_t
/* vpu/sample specific */
#define TYPE_SUBGRAPH_PACK              uint32_t

#define VALUE_SUBGAPH_PACK_ID_NONE      0xFFFFFFFF
#define VALUE_SUBGAPH_CTX_ID_NONE       0xFFFFFFFF

#define SIZE_SUBGRAPH_TYPE \
	(sizeof(TYPE_SUBGRAPH_TYPE))
#define SIZE_SUBGRAPH_TARGET_TIME \
	(sizeof(TYPE_SUBGRAPH_TARGET_TIME))
#define SIZE_SUBGRAPH_UP_TURNAROUND \
	(sizeof(TYPE_SUBGRAPH_UP_TURNAROUND))
#define SIZE_SUBGRAPH_DRIVER_TURNAROUND \
	(sizeof(TYPE_SUBGRAPH_DRIVER_TURNAROUND))
#define SIZE_SUBGRAPH_TCM_USAGE \
	(sizeof(TYPE_SUBGRAPH_TCM_USAGE))
#define SIZE_SUBGRAPH_TCM_FORCE \
	(sizeof(TYPE_SUBGRAPH_TCM_FORCE))
#define SIZE_SUBGRAPH_CTX_ID \
	(sizeof(TYPE_SUBGRAPH_CTX_ID))
#define SIZE_SUBGRAPH_SIZE \
	(sizeof(TYPE_SUBGRAPH_SIZE))
#define SIZE_SUBGRAPH_ADDR \
	(sizeof(TYPE_SUBGRAPH_ADDR))
/* vpu/sample specific */
#define SIZE_SUBGRAPH_PACK \
	(sizeof(TYPE_SUBGRAPH_PACK))

#define SIZE_SUBGRAPH_ELEMENT \
	(SIZE_SUBGRAPH_TYPE + SIZE_SUBGRAPH_TARGET_TIME +\
	SIZE_SUBGRAPH_UP_TURNAROUND + SIZE_SUBGRAPH_DRIVER_TURNAROUND +\
	SIZE_SUBGRAPH_TCM_USAGE + SIZE_SUBGRAPH_TCM_FORCE +\
	SIZE_SUBGRAPH_CTX_ID + SIZE_SUBGRAPH_SIZE + SIZE_SUBGRAPH_ADDR)

/* spcific subgraph offset */
#define OFFSET_SUBGRAPH_TYPE \
	(0)
#define OFFSET_SUBGRAPH_TARGET_TIME \
	(OFFSET_SUBGRAPH_TYPE + SIZE_SUBGRAPH_TYPE)
#define OFFSET_SUBGRAPH_UP_TURNAROUND \
	(OFFSET_SUBGRAPH_TARGET_TIME + SIZE_SUBGRAPH_TARGET_TIME)
#define OFFSET_SUBGRAPH_DRIVER_TURNAROUND \
	(OFFSET_SUBGRAPH_UP_TURNAROUND + SIZE_SUBGRAPH_UP_TURNAROUND)
#define OFFSET_SUBGRAPH_TCM_USAGE \
	(OFFSET_SUBGRAPH_DRIVER_TURNAROUND + SIZE_SUBGRAPH_DRIVER_TURNAROUND)
#define OFFSET_SUBGRAPH_TCM_FORCE \
	(OFFSET_SUBGRAPH_TCM_USAGE + SIZE_SUBGRAPH_TCM_USAGE)
#define OFFSET_SUBGRAPH_CTX_ID \
	(OFFSET_SUBGRAPH_TCM_FORCE + SIZE_SUBGRAPH_TCM_FORCE)
#define OFFSET_SUBGRAPH_SIZE \
	(OFFSET_SUBGRAPH_CTX_ID + SIZE_SUBGRAPH_CTX_ID)
#define OFFSET_SUBGRAPH_ADDR \
	(OFFSET_SUBGRAPH_SIZE + SIZE_SUBGRAPH_SIZE)
/* vpu/sample specific */
#define OFFSET_SUBGRAPH_PACK \
	(OFFSET_SUBGRAPH_ADDR + SIZE_SUBGRAPH_ADDR)


#endif
