# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MTK_USB_META)	+= usb_meta/
obj-$(CONFIG_MTK_ECCCI_C2K_USB) += c2k_usb/
obj-$(CONFIG_MTK_USB_F_RNDIS)	+= usb_rndis/
obj-$(CONFIG_MTK_USB_BOOST)	+= usb_boost/
obj-$(CONFIG_MTK_USB_OFFLOAD)	+= usb_offload/
