#
# Makefile for MHL Sii9244 chip drivers.

obj-$(CONFIG_TEGRA_HDMI_MHL_9244)	+= si_drv_mhl_tx.o
obj-$(CONFIG_TEGRA_HDMI_MHL_9244)	+= si_mhl_tx.o
obj-$(CONFIG_TEGRA_HDMI_MHL_9244)	+= si_mhl_tx_rcp_table.o
obj-$(CONFIG_TEGRA_HDMI_MHL_9244)	+= sii_reg_access.o


obj-$(CONFIG_TEGRA_HDMI_MHL_9244)	+= sii_9244_api.o

#ccflags-$(CONFIG_I2C_DEBUG_BUS) := -DDEBUG
