#
# Makefile for the Linux Kernel SOC specific device drivers.
#

subdir-ccflags-y += -Werror

obj-$(CONFIG_SOC_MEDIATEK)	+= mediatek/
obj-$(CONFIG_ARCH_QCOM)		+= qcom/
obj-$(CONFIG_ARCH_TEGRA)	+= tegra/
obj-$(CONFIG_SOC_TI)		+= ti/
obj-$(CONFIG_PLAT_VERSATILE)	+= versatile/
