# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MI_IORAP)     += iorap2.o

iorap2-y := launch_boost_com.o
iorap2-y += launch_boost.o
iorap2-y += launch_boost_collect.o
iorap2-y += launch_boost_preread.o
iorap2-y += launch_boost_clear.o
iorap2-y += launch_boost_flush.o
iorap2-y += launch_boost_dbg.o
iorap2-y += pte_hot_preread.o
