ccflags-y += -I$(srctree)/drivers/misc/mediatek/pmic \
             -I$(srctree)/drivers/misc/mediatek/usb_c/inc

# Mediatek PMIC MT63XX specific files
obj-$(CONFIG_MTK_PMIC_CHIP_MT6353)          += pmic.o pmic_irq.o upmu_common.o pmic_regulator.o pmic_api.o pmic_api_buck.o pmic_api_ldo.o regulator_codegen.o pmic_auxadc.o pmic_chr_type_det.o pmic_initial_setting.o pmic_efuse.o pmic_throttling_dlpt.o pmic_pinctl.o
