# SPDX-License-Identifier: GPL-2.0
#Makefile for the WUSB3801X drivers
# (the ones that don't fit into any other categories)
#
#ccflags-$(CONFIG_USB_DEBUG) := -DDEBUG
#ccflags-y := -DDEBUG
#obj-y           += wusb3801x.o
obj-$(CONFIG_WUSB3801_DEBUG)  += wusb3801x.o