#
# Makefile for kernel SPMI Simulator.
#
obj-$(CONFIG_SPMI_SIMULATOR)	+= spmi-sim.o
obj-$(CONFIG_PM855_PMIC_SIMULATOR)	+= pm855-sim.o
obj-$(CONFIG_PM855B_PMIC_SIMULATOR)	+= pm855b-sim.o
obj-$(CONFIG_PM855L_PMIC_SIMULATOR)	+= pm855l-sim.o
