#
# Makefile for kernel SPMI Simulator.
#
obj-$(CONFIG_SPMI_SIMULATOR)	+= spmi-sim.o
obj-$(CONFIG_PM8150_PMIC_SIMULATOR)	+= pm8150-sim.o
obj-$(CONFIG_PM8150B_PMIC_SIMULATOR)	+= pm8150b-sim.o
obj-$(CONFIG_PM8150L_PMIC_SIMULATOR)	+= pm8150l-sim.o
