# SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note OR MIT
#
# (C) COPYRIGHT 2019-2021 Arm Limited or its affiliates. All rights reserved.
#
#

obj-$(CONFIG_MALI_ARBITRATION) := mali_arbiter.o

mali_arbiter-y := mali_arbiter_main.o mali_arbiter_sysfs.o

# Set up defaults if not defined by build system
MALI_ARBITER_TEST_API ?= 0

# Set up our defines, which will be passed to gcc
DEFINES = \
	-DMALI_ARBITER_TEST_API=$(MALI_ARBITER_TEST_API)

# Use our defines when compiling
ccflags-y += $(DEFINES)
ccflags-y += -I$(src)/../include
ccflags-y += -I$(src)/../ptm/include
subdir-ccflags-y += $(DEFINES)
