#drivers/input/touchscreen/focaltech_ts/focaltech_test
#
# Makefile for test module
#
# Linux driver folder
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_ft8716.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_config_ft8716.o
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_test_supported_ic.o

