obj-$(CONFIG_HUAQIN_ADAPTER_CLASS)	+= hq_adapter_class.o

obj-$(CONFIG_HUAQIN_CHARGER_CLASS)	+= hq_charger_class.o hq_fg_class.o hq_batt_class.o

obj-$(CONFIG_HUAQIN_CP_CLASS)		+= hq_cp_class.o

obj-$(CONFIG_HUAQIN_CP_CLASS)		+= hq_led_class.o

obj-$(CONFIG_PD_BATTERY_SECRET)		+=xm_adapter_class.o
