
# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/

obj-y   +=  gsl_point_id_point_active_pen_no_gesture.o
obj-y	+=  mtk_gslX680.o
