# test core code
#
ccflags-y += -I$(srctree)/drivers/input/touchscreen/normandy_unified_protocol

obj-y += board_opr_interface_kernel.o
obj-y += public_fun.o
obj-y += simple_mem_manager_mach.o
obj-y += test_proc.o
obj-y += tp_additional_option.o
obj-y += tp_dev_control.o
obj-y += tp_item_permutation.o
obj-y += tp_normandy_control.o
obj-y += tp_open_test.o
obj-y += normandy_short_test.o
obj-y += tp_short_test.o
obj-y += tp_test_item_buf_mem.o
obj-y += tp_test_item_mem.o
obj-y += tp_version_test.o
obj-y += memory_override.o

#comm
obj-y += crc_decrypt.o
obj-y += extra_tp_control.o
obj-y += generic_func.o
obj-y += save_test_data.o
obj-y += test_item_init.o
obj-y += test_order.o
obj-y += test_param_init.o

# xml lib
obj-y += mxml-attr.o
obj-y += mxml-entity.o
obj-y += mxml-file.o
obj-y += mxml-get.o
obj-y += mxml-index.o
obj-y += mxml-node.o
obj-y += mxml-private.o
obj-y += mxml-search.o
obj-y += mxml-set.o
obj-y += mxml-string.o
