#
# Copyright (C) 2017 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

ccflags-y += \
	-I$(srctree)/drivers/misc/mediatek/base/power/include/ \
	-I$(srctree)/drivers/misc/mediatek/base/power/include/leakage_table_v2/ \

# MT6759
obj-$(CONFIG_MACH_MT6759) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6759) += mtk_static_power_mt6759.o

# MT6763
obj-$(CONFIG_MACH_MT6763) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6763) += mtk_static_power_mt6763.o

# MT6758
obj-$(CONFIG_MACH_MT6758) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6758) += mtk_static_power_mt6758.o

# MT6739
obj-$(CONFIG_MACH_MT6739) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6739) += mtk_static_power_mt6739.o

# MT6765
obj-$(CONFIG_MACH_MT6765) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6765) += mtk_static_power_mt6765.o

# MT6761
obj-$(CONFIG_MACH_MT6761) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6761) += mtk_static_power_mt6761.o

# MT3967
obj-$(CONFIG_MACH_MT3967) += mtk_static_power.o

obj-$(CONFIG_MACH_MT3967) += mtk_static_power_mt3967.o

# MT6779
obj-$(CONFIG_MACH_MT6779) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6779) += mtk_static_power_mt6779.o

#MT6781
obj-$(CONFIG_MACH_MT6781) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6781) += mtk_static_power_mt6781.o

#MT6768
obj-$(CONFIG_MACH_MT6768) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6768) += mtk_static_power_mt6768.o
# MT6877
obj-$(CONFIG_MACH_MT6877) += mtk_static_power.o
obj-$(CONFIG_MACH_MT6877) += mtk_static_power_mt6877.o

# MT6833
obj-$(CONFIG_MACH_MT6833) += mtk_static_power.o
obj-$(CONFIG_MACH_MT6833) += mtk_static_power_mt6833.o
# MT6893
obj-$(CONFIG_MACH_MT6893) += mtk_static_power.o

obj-$(CONFIG_MACH_MT6893) += mtk_static_power_mt6893.o
