subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc_agate/inc

obj-$(CONFIG_AGATE_CHARGER) += bq25980_charger.o bq2597x_charger.o bq25790_charger.o max77932.o pd_policy_manager.o cp_qc30.o ln8000_charger.o
