# SPDX-License-Identifier: GPL-2.0

qnoc-holi-objs			:= holi.o
qnoc-qcs404-objs			:= qcs404.o
qnoc-sdm845-objs			:= sdm845.o
qnoc-lahaina-objs			:= lahaina.o
qnoc-sdxlemur-objs			:= sdxlemur.o
qnoc-shima-objs				:= shima.o
icc-smd-rpm-objs			:= smd-rpm.o
icc-bcm-voter-objs			:= bcm-voter.o
icc-rpmh-obj				:= icc-rpmh.o
icc-rpm-obj			:= icc-rpm.o
qnoc-qos-obj			:= qnoc-qos.o

obj-$(CONFIG_INTERCONNECT_QCOM_HOLI) += qnoc-holi.o
obj-$(CONFIG_INTERCONNECT_QCOM_QCS404) += qnoc-qcs404.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDM845) += qnoc-sdm845.o
obj-$(CONFIG_INTERCONNECT_QCOM_LAHAINA) += qnoc-lahaina.o
obj-$(CONFIG_INTERCONNECT_QCOM_SHIMA) += qnoc-shima.o
obj-$(CONFIG_INTERCONNECT_QCOM_SDXLEMUR) += qnoc-sdxlemur.o
obj-$(CONFIG_INTERCONNECT_QCOM_RPM) += icc-rpm.o
obj-$(CONFIG_INTERCONNECT_QCOM_SMD_RPM) += icc-smd-rpm.o
obj-$(CONFIG_INTERCONNECT_QCOM_BCM_VOTER) += icc-bcm-voter.o
obj-$(CONFIG_INTERCONNECT_QCOM_RPMH) += icc-rpmh.o
obj-$(CONFIG_INTERCONNECT_QCOM_QOS) += qnoc-qos.o
obj-$(CONFIG_INTERCONNECT_QCOM_EPSS_L3) += epss-l3.o
obj-$(CONFIG_INTERCONNECT_QCOM_CPUCP_L3) += cpucp-l3.o
