ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_core
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/cpas_top
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/camss_top

obj-$(CONFIG_MSM_AIS) += cpas_top/
obj-$(CONFIG_MSM_AIS) += camss_top/
obj-$(CONFIG_MSM_AIS) += cam_cpas_soc.o cam_cpas_intf.o cam_cpas_hw.o