TARGET=ispv3_mfd_dev
obj-$(CONFIG_ISPV3)+=$(TARGET).o
$(TARGET)-objs:=ispv3_dev.o ispv3_power.o
obj-$(CONFIG_ISPV3)+=ispv3_cam_dev.o
#obj-$(CONFIG_ISPV3) += ispv3_dev.o ispv3_power.o ispv3_cam_dev.o

