obj-$(CONFIG_LC_BATTERY_SECRET) += battery_secret_manager.o
battery_secret_manager-objs := battery_secret_class.o battery_secret_logic.o

obj-$(CONFIG_LC_BATTERY_SECRET) += acl16_slg2.o
acl16_slg2-objs := acl16_slg2_drv.o secret_common.o
obj-$(CONFIG_LC_BATTERY_SECRET) += ds28e30.o
ds28e30-objs := ds28e30_drv.o secret_common.o
