/* SPDX-License-Identifier: GPL-2.0-only */
/* Copyright (c) 2018, The Linux Foundation. All rights reserved. */

#ifndef _DT_BINDINGS_CLK_QCOM_DISP_CC_KONA_H
#define _DT_BINDINGS_CLK_QCOM_DISP_CC_KONA_H

#define DISP_CC_DEBUG_CLK					0
#define DISP_CC_MDSS_AHB_CLK					1
#define DISP_CC_MDSS_AHB_CLK_SRC				2
#define DISP_CC_MDSS_BYTE0_CLK					3
#define DISP_CC_MDSS_BYTE0_CLK_SRC				4
#define DISP_CC_MDSS_BYTE0_DIV_CLK_SRC				5
#define DISP_CC_MDSS_BYTE0_INTF_CLK				6
#define DISP_CC_MDSS_BYTE1_CLK					7
#define DISP_CC_MDSS_BYTE1_CLK_SRC				8
#define DISP_CC_MDSS_BYTE1_DIV_CLK_SRC				9
#define DISP_CC_MDSS_BYTE1_INTF_CLK				10
#define DISP_CC_MDSS_DP_AUX1_CLK				11
#define DISP_CC_MDSS_DP_AUX1_CLK_SRC				12
#define DISP_CC_MDSS_DP_AUX_CLK					13
#define DISP_CC_MDSS_DP_AUX_CLK_SRC				14
#define DISP_CC_MDSS_DP_CRYPTO1_CLK				15
#define DISP_CC_MDSS_DP_CRYPTO1_CLK_SRC				16
#define DISP_CC_MDSS_DP_CRYPTO_CLK				17
#define DISP_CC_MDSS_DP_CRYPTO_CLK_SRC				18
#define DISP_CC_MDSS_DP_LINK1_CLK				19
#define DISP_CC_MDSS_DP_LINK1_CLK_SRC				20
#define DISP_CC_MDSS_DP_LINK1_DIV_CLK_SRC			21
#define DISP_CC_MDSS_DP_LINK1_INTF_CLK				22
#define DISP_CC_MDSS_DP_LINK_CLK				23
#define DISP_CC_MDSS_DP_LINK_CLK_SRC				24
#define DISP_CC_MDSS_DP_LINK_DIV_CLK_SRC			25
#define DISP_CC_MDSS_DP_LINK_INTF_CLK				26
#define DISP_CC_MDSS_DP_PIXEL1_CLK				27
#define DISP_CC_MDSS_DP_PIXEL1_CLK_SRC				28
#define DISP_CC_MDSS_DP_PIXEL2_CLK				29
#define DISP_CC_MDSS_DP_PIXEL2_CLK_SRC				30
#define DISP_CC_MDSS_DP_PIXEL_CLK				31
#define DISP_CC_MDSS_DP_PIXEL_CLK_SRC				32
#define DISP_CC_MDSS_EDP_AUX_CLK				33
#define DISP_CC_MDSS_EDP_AUX_CLK_SRC				34
#define DISP_CC_MDSS_EDP_GTC_CLK				35
#define DISP_CC_MDSS_EDP_GTC_CLK_SRC				36
#define DISP_CC_MDSS_EDP_LINK_CLK				37
#define DISP_CC_MDSS_EDP_LINK_CLK_SRC				38
#define DISP_CC_MDSS_EDP_LINK_DIV_CLK_SRC			39
#define DISP_CC_MDSS_EDP_LINK_INTF_CLK				40
#define DISP_CC_MDSS_EDP_PIXEL_CLK				41
#define DISP_CC_MDSS_EDP_PIXEL_CLK_SRC				42
#define DISP_CC_MDSS_ESC0_CLK					43
#define DISP_CC_MDSS_ESC0_CLK_SRC				44
#define DISP_CC_MDSS_ESC1_CLK					45
#define DISP_CC_MDSS_ESC1_CLK_SRC				46
#define DISP_CC_MDSS_MDP_CLK					47
#define DISP_CC_MDSS_MDP_CLK_SRC				48
#define DISP_CC_MDSS_MDP_LUT_CLK				49
#define DISP_CC_MDSS_NON_GDSC_AHB_CLK				50
#define DISP_CC_MDSS_PCLK0_CLK					51
#define DISP_CC_MDSS_PCLK0_CLK_SRC				52
#define DISP_CC_MDSS_PCLK1_CLK					53
#define DISP_CC_MDSS_PCLK1_CLK_SRC				54
#define DISP_CC_MDSS_ROT_CLK					55
#define DISP_CC_MDSS_ROT_CLK_SRC				56
#define DISP_CC_MDSS_RSCC_AHB_CLK				57
#define DISP_CC_MDSS_RSCC_VSYNC_CLK				58
#define DISP_CC_MDSS_SPDM_DEBUG_CLK				59
#define DISP_CC_MDSS_SPDM_DP_CRYPTO_CLK				60
#define DISP_CC_MDSS_SPDM_DP_CRYPTO_DIV_CLK_SRC			61
#define DISP_CC_MDSS_SPDM_DP_PIXEL1_CLK				62
#define DISP_CC_MDSS_SPDM_DP_PIXEL1_DIV_CLK_SRC			63
#define DISP_CC_MDSS_SPDM_DP_PIXEL_CLK				64
#define DISP_CC_MDSS_SPDM_DP_PIXEL_DIV_CLK_SRC			65
#define DISP_CC_MDSS_SPDM_MDP_CLK				66
#define DISP_CC_MDSS_SPDM_MDP_DIV_CLK_SRC			67
#define DISP_CC_MDSS_SPDM_PCLK0_CLK				68
#define DISP_CC_MDSS_SPDM_PCLK0_DIV_CLK_SRC			69
#define DISP_CC_MDSS_SPDM_PCLK1_CLK				70
#define DISP_CC_MDSS_SPDM_PCLK1_DIV_CLK_SRC			71
#define DISP_CC_MDSS_SPDM_ROT_CLK				72
#define DISP_CC_MDSS_SPDM_ROT_DIV_CLK_SRC			73
#define DISP_CC_MDSS_VSYNC_CLK					74
#define DISP_CC_MDSS_VSYNC_CLK_SRC				75
#define DISP_CC_PLL0						76
#define DISP_CC_PLL1						77
#define DISP_CC_PLL_TEST_CLK					78
#define DISP_CC_PLL_TEST_DIV_CLK_SRC				79
#define DISP_CC_SLEEP_CLK					80
#define DISP_CC_SLEEP_CLK_SRC					81
#define DISP_CC_XO_CLK						82
#define DISP_CC_XO_CLK_SRC					83

#define MDSS_CORE_GDSC						0

#define DISP_CC_MDSS_CORE_BCR					0
#define DISP_CC_MDSS_RSCC_BCR					1
#define DISP_CC_MDSS_SPDM_BCR					2

#endif
