ccflags-y += -DATOMISP_POSTFIX=\"css2401a0_v21\" -DATOMISP_FWNAME=\"shisp_2401a0_v21.bin\" -DISP2401 -DISP2401_NEW_INPUT_SYSTEM
ISP2401 := y
ISP2401_NEW_INPUT_SYSTEM := y
postfix := css2401a0_v21

include $(srctree)/$(src)/../Makefile.common
