ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/v1/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/mt6853/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/twam/
obj-$(CONFIG_MTK_PMSR) += pmsr.o

