# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS_BBB)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_BBB)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_BBB)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_BBB)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_BBB)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_BBB)   +=  focaltech_point_report_check.o


obj-$(CONFIG_TOUCHSCREEN_FTS_BBB)   +=  focaltech_spi.o
obj-$(CONFIG_TOUCHSCREEN_FTS_BBB)	+=  focaltech_flash.o

obj-$(CONFIG_TOUCHSCREEN_FTS_BBB)	+=  focaltech_test/

