# MSM Machine Support

snd-soc-hostless-pcm-objs := msm-pcm-hostless.o
obj-$(CONFIG_SND_SOC_MSM_HOSTLESS_PCM) += snd-soc-hostless-pcm.o

obj-$(CONFIG_SND_SOC_MSM_QDSP6V2_INTF) += qdsp6v2/

snd-soc-qdsp6v2-objs := msm-dai-fe.o
obj-$(CONFIG_SND_SOC_QDSP6V2) += snd-soc-qdsp6v2.o

#for APQ8084 sound card driver
snd-soc-apq8084-objs := apq8084.o
obj-$(CONFIG_SND_SOC_APQ8084) += snd-soc-apq8084.o

#for CPE drivers
snd-soc-cpe-objs := msm-cpe-lsm.o
obj-$(CONFIG_SND_SOC_CPE) += snd-soc-cpe.o

# for MSM 8994 sound card driver
snd-soc-msm8994-objs := msm8994.o
obj-$(CONFIG_SND_SOC_MSM8994) += snd-soc-msm8994.o

# for MSM8996 sound card driver
snd-soc-msm8996-objs := msm8996.o
obj-$(CONFIG_SND_SOC_MSM8996) += snd-soc-msm8996.o

# for MSM 8x16/8952 sound card driver
snd-soc-msm8x16-objs := msm8952.o msm-audio-pinctrl.o
snd-soc-msm8x16-objs += msm8952-slimbus.o msm8952-dai-links.o
obj-$(CONFIG_SND_SOC_MSM8X16) += snd-soc-msm8x16.o

# for MDM Californium sound card driver
snd-soc-mdmcalifornium-objs := mdmcalifornium.o
obj-$(CONFIG_SND_SOC_MDMCALIFORNIUM) += snd-soc-mdmcalifornium.o

# for MDM FERMIUM sound card driver
snd-soc-mdmfermium-objs := mdmfermium.o
obj-$(CONFIG_SND_SOC_MDMFERMIUM) += snd-soc-mdmfermium.o
