#
# Makefile for the Synaptics DSX touchscreen driver.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX) += synaptics_dsx.o

synaptics_dsx-y := synaptics_dsx_i2c.o synaptics_dsx_core.o
