ifeq ($(CONFIG_MACH_MT6768),y)
obj-y += mt6768/
else
ifeq ($(CONFIG_MACH_MT6893),y)
obj-y += mt6893/
else
ifeq ($(CONFIG_MACH_MT6833),y)
obj-y += mt6833/
else
ifeq ($(CONFIG_MACH_MT6877),y)
obj-y += mt6877/
else
ifeq ($(CONFIG_MACH_MT6781),y)
obj-y += mt6781/
else
obj-y += $(subst ",,$(CONFIG_MTK_PLATFORM))/
endif
endif
endif
endif
endif
