# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_IPA_USB) += ipausbm.o
ipausbm-objs := ipa_usb.o

obj-$(CONFIG_RNDIS_IPA) += rndisipam.o
rndisipam-objs := rndis_ipa.o

obj-$(CONFIG_ECM_IPA) += ecmipam.o
ecmipam-objs := ecm_ipa.o
