#
# arch/arm/mach-tegra/p852/Makefile
#
# Copyright (c) 2010-2011, NVIDIA Corporation.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
#

obj-${CONFIG_MACH_P852}                += board-p852.o
obj-${CONFIG_MACH_P852}                += board-p852-sdhci.o
obj-${CONFIG_MACH_P852}                += board-p852-i2c.o
obj-${CONFIG_MACH_P852}                += board-p852-power.o
obj-${CONFIG_MACH_P852}                += board-p852-pinmux.o
obj-${CONFIG_MACH_P852}                += board-p852-gpio.o
obj-${CONFIG_MACH_P852}                += board-p852-panel.o

obj-${CONFIG_P852_SKU1}           += board-p852-sku1.o
obj-${CONFIG_P852_SKU1_B00}       += board-p852-sku1-b00.o
obj-${CONFIG_P852_SKU1_C0x}       += board-p852-sku1-c0x.o
obj-${CONFIG_P852_SKU3}           += board-p852-sku3.o
obj-${CONFIG_P852_SKU5_B00}       += board-p852-sku5-b00.o
obj-${CONFIG_P852_SKU5_C01}       += board-p852-sku5-c01.o
obj-${CONFIG_P852_SKU8_B00}       += board-p852-sku8-b00.o
obj-${CONFIG_P852_SKU8_C01}       += board-p852-sku8-c01.o
obj-${CONFIG_P852_SKU9_B00}       += board-p852-sku9-b00.o
obj-${CONFIG_P852_SKU9_C01}       += board-p852-sku9-c01.o
obj-${CONFIG_P852_SKU13}          += board-p852-sku13.o
obj-${CONFIG_P852_SKU13_B00}      += board-p852-sku13-b00.o
obj-${CONFIG_P852_SKU23}          += board-p852-sku23.o
obj-${CONFIG_P852_SKU23_B00}      += board-p852-sku23-b00.o
obj-${CONFIG_P852_SKU23_C01}      += board-p852-sku23-c01.o
