GCC_VERSION      := $(shell $(CONFIG_SHELL) $(PWD)/scripts/gcc-version.sh $(CROSS_COMPILE)gcc)
EXTRA_CFLAGS += -Idrivers/media/platform/msm/camera_v1
EXTRA_CFLAGS += -Idrivers/media/platform/msm/camera_v1/io
obj-$(CONFIG_MSM_ACTUATOR) += msm_actuator.o
