ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_jpeg/jpeg_hw/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_jpeg/jpeg_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_cpas/include/

obj-$(CONFIG_SPECTRA_CAMERA) += jpeg_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_jpeg_dev.o cam_jpeg_context.o
