#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FT5446)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FT5446)   +=  focaltech_i2c.o
