obj-$(CONFIG_UNISOC_SIPC)			+= sipc-core.o
sipc-core-y := sipc.o smsg.o smem.o sbuf.o sblock.o sprd_actions_queue.o
obj-$(CONFIG_UNISOC_SIPC_SPIPE)		+= spipe.o
obj-$(CONFIG_UNISOC_SIPC_SPOOL)		+= spool.o
obj-$(CONFIG_UNISOC_SIPC_SLOG_BRIDGE)	+= slog_bridge.o
obj-$(CONFIG_UNISOC_SIPC_SBUF_BRIDGE)	+= sbuf_bridge.o
obj-$(CONFIG_UNISOC_SIPC_SBLOCK_BRIDGE)	+= sblock_bridge.o

obj-$(CONFIG_UNISOC_SIPC_ZERO_COPY_SIPX)	+= sipx.o
