obj-$(CONFIG_USE_OF) += board-dt.o
obj-$(CONFIG_SMP)	+= platsmp.o
obj-$(CONFIG_ARCH_SDXPOORWILLS) += board-poorwills.o
obj-$(CONFIG_ARCH_MSM8953) += board-msm8953.o
obj-$(CONFIG_ARCH_SDM450) += board-sdm450.o
