obj-$(CONFIG_USE_OF) += board-dt.o
obj-$(CONFIG_SMP)	+= platsmp.o
obj-$(CONFIG_ARCH_QCS405) += board-qcs405.o
obj-$(CONFIG_ARCH_QCS403) += board-qcs403.o
obj-$(CONFIG_ARCH_TRINKET) += board-trinket.o
obj-$(CONFIG_ARCH_SDXPRAIRIE) += board-sdxprairie.o
