ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_core
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_jpeg
ccflags-y += -Idrivers/media/platform/msm/ais/cam_jpeg/jpeg_hw/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_jpeg/jpeg_hw/
ccflags-y += -Idrivers/media/platform/msm/ais/cam_jpeg/jpeg_hw/jpeg_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_jpeg/jpeg_hw/jpeg_dma_hw

obj-$(CONFIG_MSM_AIS) += jpeg_dma_dev.o jpeg_dma_core.o jpeg_dma_soc.o
