# SPDX-License-Identifier: GPL-2.0-only

ccflags-y := -I$(srctree)/drivers/clk/qcom/

obj-$(CONFIG_QCOM_MDSS_PLL) += pll_util.o
obj-$(CONFIG_QCOM_MDSS_PLL) += pll_drv.o
obj-$(CONFIG_QCOM_MDSS_PLL) += dsi_pll_10nm.o
obj-$(CONFIG_QCOM_MDSS_PLL) += dsi_pll_7nm.o
obj-$(CONFIG_QCOM_MDSS_PLL) += dsi_pll_28lpm.o
obj-$(CONFIG_QCOM_MDSS_PLL) += dsi_pll_28nm_util.o
obj-$(CONFIG_QCOM_MDSS_PLL) += dsi_pll_14nm.o
obj-$(CONFIG_QCOM_MDSS_PLL) += dsi_pll_14nm_util.o
obj-$(CONFIG_QCOM_MDSS_PLL) += hdmi_pll_28lpm.o
obj-$(CONFIG_QCOM_MDSS_DP_PLL) += dp_pll_7nm.o \
	dp_pll_7nm_util.o \
	dp_pll_10nm.o \
	dp_pll_10nm_util.o \
	dp_pll_14nm.o \
