obj-$(CONFIG_ONEWIRE_GPIO_PIPA) += onewire_gpio_master.o onewire_gpio_slave.o
obj-$(CONFIG_BATT_VERIFY_BY_DS28E16_PIPA) += onewire_gpio_master.o onewire_gpio_slave.o ucl_sha3.o sha384_software.o ds28e16_master.o ds28e16_slave.o
