# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_XM_POWER_SUPPLY)	+= battery/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= battmngr_iio/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= charger/
obj-$(CONFIG_XM_POWER_SUPPLY)	+= init/
