#
# Makefile for industrial I/O Light sensors
#
GCOV_PROFILE := y

#ccflags-y := -Werror

obj-$(CONFIG_SENSORS_CM3218)	+= cm3218.o
obj-$(CONFIG_SENSORS_ISL29018)	+= isl29018.o
obj-$(CONFIG_SENSORS_ISL29028)	+= isl29028.o
obj-$(CONFIG_TSL2583)	+= tsl2583.o
obj-$(CONFIG_TSL2x7x)	+= tsl2x7x_core.o
obj-$(CONFIG_SENSORS_JSA1127)	+= jsa1127.o
obj-$(CONFIG_SENSORS_LTR558)	+= ltr558als.o
obj-$(CONFIG_SENSORS_MAX44005)	+= max44005.o
obj-$(CONFIG_SENSORS_STM8T143)	+= stm8t143.o
obj-$(CONFIG_SENSORS_TCS3772)	+= tcs3772.o
obj-$(CONFIG_SENSORS_TSL2563)	+= tsl2563.o
obj-$(CONFIG_TSL2583)		+= tsl2583.o
obj-$(CONFIG_SENSORS_CM3217)	+= cm3217.o
obj-$(CONFIG_LS_SYSFS)	+= ls_sysfs.o
obj-$(CONFIG_LS_OF)	+= ls_dt.o
obj-$(CONFIG_SENSORS_IQS253)	+= iqs253.o
