obj-$(CONFIG_VIDEO_MEDIATEK_VCODEC) += venc_h264_if.o venc_h264_vpu.o

ccflags-y += \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/ \
    -I$(srctree)/drivers/media/platform/mtk-vcodec/h264_enc \
    -I$(srctree)/drivers/media/platform/mtk-vpu
