
# Makefile for the power golden setting.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y += mt_power_gs.o
obj-y += mt_power_gs_cg_array.o
obj-y += mt_power_gs_dcm_array.o
obj-y += mt_power_gs_6331_array.o
obj-y += mt_power_gs_6332_array.o
obj-y += mt_power_gs_analog_array.o
obj-y += mt_power_gs_suspend.o
obj-y += mt_power_gs_dpidle.o
obj-y += mt_power_gs_idle.o
obj-y += mt_power_gs_audio_playback.o
