/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */

#ifndef __SENINF_CAMMUX_H__
#define __SENINF_CAMMUX_H__

#define SENINF_TOP_N3D_A_CTRL 0x0080
#define RG_N3D_SENINF1_VSYNC_SRC_SEL_A_SHIFT 0
#define RG_N3D_SENINF1_VSYNC_SRC_SEL_A_MASK (0xF << 0)
#define RG_N3D_SENINF2_VSYNC_SRC_SEL_A_SHIFT 8
#define RG_N3D_SENINF2_VSYNC_SRC_SEL_A_MASK (0xF << 8)

#define SENINF_TOP_N3D_B_CTRL 0x0084
#define RG_N3D_SENINF1_VSYNC_SRC_SEL_B_SHIFT 0
#define RG_N3D_SENINF1_VSYNC_SRC_SEL_B_MASK (0xF << 0)
#define RG_N3D_SENINF2_VSYNC_SRC_SEL_B_SHIFT 8
#define RG_N3D_SENINF2_VSYNC_SRC_SEL_B_MASK (0xF << 8)

#endif

