#gt915 touchpanel driver


obj-$(CONFIG_MSG28XX_TOUCHPANEL_DRIVER)	+= mstar_drv_common.o mstar_drv_ic_fw_porting_layer.o mstar_drv_jni_interface.o mstar_drv_main.o mstar_drv_mutual_fw_control.o mstar_drv_mutual_mp_test.o mstar_drv_platform_interface.o mstar_drv_platform_porting_layer.o mstar_drv_qcom.o mstar_drv_utility_adaption.o  mstar_drv_hotknot.o mstar_drv_hotknot_queue.o


