#MTK port custom Kbuild
#To Add 1.environment variable
include $(src)/Kbuild-mtk-custom-env

curr := platform/mtk_platform_common

obj-y += $(curr)/mtk_platform_common.o
obj-y += $(curr)/mtk_mfg_counter.o

obj-y += $(curr)/mtk_gpu_power_sspm_ipi.o

ccflags-y += -I$(srctree)/drivers/devfreq/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/swpm_v1/$(MTK_PLATFORM)/
#ifdef CONFIG_MTK_PERF_TRACKER
ccflags-y += -I$(srctree)/drivers/misc/mediatek/perf/
#endif