ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp/icp_hw/icp_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp/icp_hw/bps_hw
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp/fw_inc
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += bps_dev.o bps_core.o bps_soc.o
