#drivers/input/touchscreen/focaltech_touch/focaltech_test/src
#
# Makefile for test module
#
# Linux driver folder

obj-$(CONFIG_TOUCHSCREEN_FT8006M) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_FT8006M) += focaltech_test_main.o
obj-$(CONFIG_TOUCHSCREEN_FT8006M) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_FT8006M) += focaltech_test_global.o
obj-$(CONFIG_TOUCHSCREEN_FT8006M) += focaltech_test_detail_threshold.o
obj-$(CONFIG_TOUCHSCREEN_FT8006M) += focaltech_ic_table.o
