ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_core/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_utils

obj-$(CONFIG_SPECTRA_CAMERA) += cam_req_mgr_core.o\
				cam_req_mgr_dev.o \
				cam_req_mgr_util.o \
				cam_req_mgr_workq.o \
				cam_mem_mgr.o \
				cam_req_mgr_timer.o \
				cam_req_mgr_debug.o
