
obj-$(CONFIG_UNISOC_PCIE_EP_DEVICE) += sprd_pcie_ep_device.o
obj-$(CONFIG_UNISOC_PCIE_EP_DEVICE) += pcie_host_resource.o
obj-$(CONFIG_PCIE_EPF_SPRD) += pcie_client_resource.o
obj-$(CONFIG_SPRD_SIPA) += pcie_sipa_res.o
