#
# Makefile for external connector class (extcon) devices
#

obj-$(CONFIG_OF_EXTCON)		+= of_extcon.o

obj-$(CONFIG_EXTCON)		+= extcon-class.o
obj-$(CONFIG_EXTCON_GPIO)	+= extcon-gpio.o
obj-$(CONFIG_EXTCON_ADC_JACK)	+= extcon-adc-jack.o
obj-$(CONFIG_EXTCON_MAX14577)	+= extcon-max14577.o
obj-$(CONFIG_EXTCON_MAX77693)	+= extcon-max77693.o
obj-$(CONFIG_EXTCON_MAX8997)	+= extcon-max8997.o
obj-$(CONFIG_EXTCON_ARIZONA)	+= extcon-arizona.o
obj-$(CONFIG_EXTCON_PALMAS)	+= extcon-palmas.o
obj-$(CONFIG_EXTCON_SMSC375X)	+= extcon-smsc375x.o
obj-$(CONFIG_INTEL_SOC_PMIC)	+= extcon-crc-pwrsrc.o
obj-$(CONFIG_INTEL_SOC_PMIC)	+= extcon-dc-pwrsrc.o
obj-$(CONFIG_EXTCON_3GPIO_OTG)	+= extcon-3gpio_otg.o
