ifeq ($(CONFIG_MTK_PMIC_CHIP_MT6357),y)
	ifeq ($(CONFIG_MACH_MT6739),y)
		obj-$(CONFIG_MACH_MT6739) += v1/
	endif
	ifeq ($(CONFIG_MACH_MT6765),y)
		obj-$(CONFIG_MACH_MT6765) += v1/
	endif
	ifeq ($(CONFIG_MACH_MT6761),y)
		obj-$(CONFIG_MACH_MT6761) += v1/
	endif
endif
