# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_ION) += ion.o ion_heap.o
obj-$(CONFIG_ION_MSM_HEAPS) += msm_ion_heaps.o
msm_ion_heaps-objs += msm_ion_of.o msm_ion_dma_buf.o ion_page_pool.o \
		ion_system_heap.o ion_carveout_heap.o ion_system_secure_heap.o \
		ion_cma_heap.o ion_secure_util.o
