# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/

obj-$(CONFIG_MTK_EMI_LEGACY_V0) += emi_legacy.o
emi_legacy-objs := emi_ctrl.o emi_mbw.o emi_elm.o emi_mpu.o
