
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hdmi/inc	\
						 -I$(srctree)/drivers/misc/mediatek/ext_disp/$(MTK_PLATFORM)/	\
						 -I$(srctree)/drivers/misc/mediatek/video/$(MTK_PLATFORM)/	\
						 -I$(srctree)/drivers/misc/mediatek/video/$(MTK_PLATFORM)/dispsys/


obj-y	+= slimport_drv.o slimport.o slimport_tx_drv.o slimport_platform.o slimport_edid_3d.o

ccflags-y += 	-DCONFIG_SLIMPORT_ANX7808
