# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_utils
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_req_mgr
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_core
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_cdm
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_sync
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_ope
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_ope/ope_hw_mgr
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_ope/ope_hw_mgr/ope_hw
ccflags-y += -I$(srctree)/techpack/camera/drivers
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_cpas/include
ccflags-y += -I$(srctree)/techpack/camera/drivers/cam_smmu/

obj-$(CONFIG_SPECTRA_CAMERA) += ope_hw/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_ope_hw_mgr.o


