ccflags-y += -Idrivers/media/platform/msm/ais/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_core
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr

obj-$(CONFIG_MSM_AIS) += cam_cdm_soc.o cam_cdm_util.o cam_cdm_intf.o \
				cam_cdm_core_common.o cam_cdm_virtual_core.o \
				cam_cdm_hw_core.o
