ccflags-y += -Idrivers/media/platform/msm/ais/
ccflags-y += -Idrivers/media/platform/msm/ais/common
ccflags-y += -Idrivers/media/platform/msm/ais/sensor
ccflags-y += -Idrivers/media/platform/msm/ais/sensor/cci
ccflags-y += -Idrivers/misc/
obj-$(CONFIG_MSM_AIS)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o msm_camera_tz_i2c.o
