# UAPI Header export list
header-y += audio.h
header-y += cdc.h
header-y += cdc-wdm.h
header-y += ch11.h
header-y += ch9.h
header-y += functionfs.h
header-y += g_printer.h
header-y += gadgetfs.h
header-y += midi.h
header-y += msm_ext_chg.h
header-y += tmc.h
header-y += video.h
header-y += ccid_bridge.h
