ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_core

obj-$(CONFIG_SPECTRA_CAMERA) += cam_ois_dev.o cam_ois_core.o cam_ois_soc.o
