#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-$(CONFIG_MTK_V4L2_LENS)   += media/
obj-$(CONFIG_MTK_V4L2_LENS)   += dw9718/
obj-$(CONFIG_MTK_V4L2_LENS)   += lc898229/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9764/
obj-$(CONFIG_MTK_V4L2_LENS)   += gt9772/
obj-$(CONFIG_MTK_V4L2_LENS)   += ak7377a/