
obj-$(CONFIG_REGMAP_SWR) += regmap-swr.o
obj-$(CONFIG_PINCTRL_WCD)	+= pinctrl-wcd.o
obj-$(CONFIG_PINCTRL_LPI)	+= pinctrl-lpi.o
obj-$(CONFIG_SOUNDWIRE)			+= soundwire.o
obj-$(CONFIG_SOUNDWIRE_WCD_CTRL)	+= swr-wcd-ctrl.o

wcd-spi-acc-ctl-objs	+= wcd-spi-ac.o wcd_spi_ctl_v01.o
obj-$(CONFIG_WCD_SPI_AC)	+= wcd-spi-acc-ctl.o
