obj-$(CONFIG_QTI_PDC)			+= pdc.o
obj-$(CONFIG_QTI_PDC_SDM845)		+= pdc-sdm845.o
obj-$(CONFIG_QTI_PDC_SDM670)		+= pdc-sdm670.o
obj-$(CONFIG_QTI_PDC_SDXPOORWILLS)	+= pdc-sdxpoorwills.o
obj-$(CONFIG_QTI_MPM)			+= mpm.o mpm-8909.o mpm-8953.o mpm-8937.o
