#
# Copyright (C) 2016 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-$(CONFIG_MTK_APUSYS_SUPPORT) += power/
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += reviser/
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += mnoc/
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += midware/
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += sample/
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += debug/
obj-$(CONFIG_MTK_APUSYS_MDLA_SUPPORT) += mdla/
obj-$(CONFIG_MTK_APUSYS_VPU) += vpu/
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += edma/
obj-$(CONFIG_MTK_APUSYS_SUPPORT) += devapc/
