# SPDX-License-Identifier: GPL-2.0
#
# Makefile for mi memory info
#
obj-${CONFIG_MI_MEMORY_SYSFS}	+= mi_memory.o
obj-${CONFIG_MI_MEMORY_SYSFS} += mmc_hr_ops.o
obj-${CONFIG_MI_MEMORY_SYSFS} += mmc_sysfs.o
obj-y += mv.o
obj-y += memory_type.o
