#drivers/input/touchscreen/focaltech_touch/focaltech_test
#
#Makefile for test module
#

obj-$(CONFIG_TOUCHSCREEN_FTS_BBB) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_FTS_BBB) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_FTS_BBB) += supported_ic/

