ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp/icp_hw/icp_hw_mgr/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp/fw_inc/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_req_mgr/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp/icp_hw/icp_hw_mgr/include/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_icp/icp_hw/a5_hw/
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_cpas/include

obj-$(CONFIG_SPECTRA_CAMERA) += cam_icp_hw_mgr.o
