# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft3427_zaw875/include/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft5346/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft3427_zaw875/include/$(CONFIG_FT5X0X_FIRMWARE)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/ft5346/include/


obj-y += Config_FT5822.o
obj-y += Config_FT5X46.o
obj-y += Config_FT8606.o
obj-y += Config_FT6X36.o
obj-y += Config_FT3C47.o
obj-y += DetailThreshold.o
obj-y += Global.o ini.o
obj-y += Test_FT5822.o
obj-y += Test_FT5X46.o
obj-y += Test_FT8606.o
obj-y += Test_FT6X36.o
obj-y += Test_FT3C47.o
obj-y += test_lib.o

