# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2021 MediaTek Inc.
#

ccflags-y += -I$(srctree)/drivers/misc/mediatek/hifi4dsp_spi
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mmp

obj-y += cmdq-bdg-mailbox.o
