
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/usb_c/inc

obj-$(CONFIG_USB_C_SWITCH_FUSB302) += fusb302/
obj-$(CONFIG_USB_C_SWITCH_SII70XX) += sii7033/
obj-$(CONFIG_USB_C_SWITCH_ANX7418) += anx7418/
obj-$(CONFIG_USB_C_SWITCH_MT6353)  += mt6353/
