# Linux driver folder
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/SOLOMOM/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
# ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT1151/include/$(CONFIG_GT1151_FIRMWARE)/
# ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT1151/include/$(CONFIG_GT1151_CONFIG)/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  atmel_mxt_ts.o



