ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/bmi160_acc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/step_counter
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
obj-y	:=  bmi160_stc.o

