#
# Makefile for the Goodix gt9xx touchscreen driver.
#

obj-$(CONFIG_TOUCHSCREEN_GT9XX)		+= gt9xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_UPDATE)	+= gt9xx_update.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_DEBUG)	+= goodix_tool.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX_SELFTEST)	+= gt9xx_selftest.o
