obj-$(CONFIG_MODS)        := mods.o
mods-y                    := mods_krnl.o
mods-y                    += mods_mem.o
mods-y                    += mods_irq.o
mods-$(CONFIG_PCI)        += mods_pci.o
mods-$(CONFIG_ACPI)       += mods_acpi.o
mods-$(CONFIG_ARCH_TEGRA) += mods_clock.o
