ccflags-y += -Idrivers/media/platform/msm/ais/cam_core/
ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr/
ccflags-y += -Idrivers/media/platform/msm/ais/cam_smmu/

obj-$(CONFIG_MSM_AIS) += cam_soc_util.o cam_io_util.o cam_packet_util.o cam_debug_util.o cam_trace.o cam_common_util.o
