# common KOs
obj-$(CONFIG_MTK_LOW_POWER_MODULE) += v1/

# platform dependent  KOs
ifeq ($(CONFIG_MTK_LPM_MT6873),m)
obj-$(CONFIG_MTK_LPM_MT6873) += mt6873/
endif
ifeq ($(CONFIG_MTK_LPM_MT6853),m)
obj-$(CONFIG_MTK_LPM_MT6853) += mt6853/
endif


