ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/

mtk-dvfsrc-help-objs = dvfsrc.o dvfsrc-opp.o dvfsrc-sysfs.o dvfsrc-ipi.o
mtk-dvfsrc-help-objs += dvfsrc-v79.o dvfsrc-v79-met.o
mtk-dvfsrc-help-objs += dvfsrc-v61.o dvfsrc-v61-met.o

obj-$(CONFIG_MTK_DVFSRC) += mtk-dvfsrc-help.o
obj-$(CONFIG_MTK_DVFSRC) += dvfsrc-boost.o
