/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */
#ifndef __CONN_INFRA_RGU_REGS_H__
#define __CONN_INFRA_RGU_REGS_H__

#define CONN_INFRA_RGU_BASE                                    0x18000000

#define CONN_INFRA_RGU_BGFYS_ON_TOP_PWR_CTL_ADDR               (CONN_INFRA_RGU_BASE + 0x0008)
#define CONN_INFRA_RGU_BGFSYS_ON_TOP_PWR_ACK_ST_ADDR           (CONN_INFRA_RGU_BASE + 0x0114)


#define CONN_INFRA_RGU_BGFYS_ON_TOP_PWR_CTL_BGFSYS_ON_TOP_PWR_ON_ADDR CONN_INFRA_RGU_BGFYS_ON_TOP_PWR_CTL_ADDR
#define CONN_INFRA_RGU_BGFYS_ON_TOP_PWR_CTL_BGFSYS_ON_TOP_PWR_ON_MASK 0x00000080
#define CONN_INFRA_RGU_BGFYS_ON_TOP_PWR_CTL_BGFSYS_ON_TOP_PWR_ON_SHFT 7

#define CONN_INFRA_RGU_BGFSYS_ON_TOP_PWR_ACK_ST_AN_BGFSYS_ON_TOP_PWR_ACK_S_ADDR \
	CONN_INFRA_RGU_BGFSYS_ON_TOP_PWR_ACK_ST_ADDR
#define CONN_INFRA_RGU_BGFSYS_ON_TOP_PWR_ACK_ST_AN_BGFSYS_ON_TOP_PWR_ACK_S_MASK 0x02000000
#define CONN_INFRA_RGU_BGFSYS_ON_TOP_PWR_ACK_ST_AN_BGFSYS_ON_TOP_PWR_ACK_S_SHFT 25
#define CONN_INFRA_RGU_BGFSYS_ON_TOP_PWR_ACK_ST_BGFSYS_ON_TOP_PWR_ACK_ADDR CONN_INFRA_RGU_BGFSYS_ON_TOP_PWR_ACK_ST_ADDR
#define CONN_INFRA_RGU_BGFSYS_ON_TOP_PWR_ACK_ST_BGFSYS_ON_TOP_PWR_ACK_MASK 0x01000000
#define CONN_INFRA_RGU_BGFSYS_ON_TOP_PWR_ACK_ST_BGFSYS_ON_TOP_PWR_ACK_SHFT 24

#endif /* __CONN_INFRA_RGU_REGS_H__ */

