ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_core
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sync
ccflags-y += -Idrivers/media/platform/msm/ais/cam_icp
ccflags-y += -Idrivers/media/platform/msm/ais/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_icp/icp_hw/icp_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_icp/fw_inc
ccflags-y += -Idrivers/media/platform/msm/ais
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_smmu/

obj-$(CONFIG_MSM_AIS) += icp_hw/
obj-$(CONFIG_MSM_AIS) += cam_icp_subdev.o cam_icp_context.o hfi.o
