#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += r63319_qxga_dsi_vdo_truly.o lcm_drv_r63319_qxga_dsi_vdo_truly.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
