# SPDX-License-Identifier: GPL-2.0-only
# bus types
obj-$(CONFIG_NEURON) += channel_bus.o
obj-$(CONFIG_NEURON) += protocol_bus.o
obj-$(CONFIG_NEURON) += application_bus.o

# platform device
obj-$(CONFIG_NEURON_SERVICE) += neuron_service.o

# drivers
obj-y	+= channel/
obj-y	+= protocol/
