/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018 MediaTek Inc.
 *
 * Author: Frederic Chen <frederic.chen@mediatek.com>
 *
 */
#ifndef _MTK_IMGSYS_VNODE_ID_H_
#define _MTK_IMGSYS_VNODE_ID_H_

/*
 * TODO: register module pipeline desc in module order
 */
enum imgsys_video_nodes_id {
	/* IMGSYS_MODULE_TRAW */
	MTK_IMGSYS_VIDEO_NODE_ID_TIMGI_OUT = 0,
	MTK_IMGSYS_VIDEO_NODE_ID_METAI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_PDC_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_TYUVO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TYUV2O_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TYUV3O_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TYUV4O_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TYUV5O_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_FEO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TIMGO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_IMGSTATO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_XTMEO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_XTFDO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_XTADLDBGO_CAPTURE,
	/* IMGSYS_MODULE_DIP */
	MTK_IMGSYS_VIDEO_NODE_ID_IMGI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_VIPI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_REC_DSI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_REC_DPI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_CNR_BLURMAPI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_LFEI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_RFEI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_TNRSI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_TNRWI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_TNRMI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_TNRCI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_TNRLI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_TNRVBI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_IMG2O_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_IMG3O_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_IMG4O_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_FMO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TNRSO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TNRWO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TNRMO_CAPTURE,
	/* IMGSYS_MODULE_PQDIP */
	MTK_IMGSYS_VIDEO_NODE_ID_PIMGI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_WROT_A_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_WROT_B_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TCCSO_A_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_TCCSO_B_CAPTURE,
	/* IMGSYS_MODULE_ME */
	MTK_IMGSYS_VIDEO_NODE_ID_MEL0IMG0_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL0IMG1_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL1IMG0_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL1IMG1_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEIMGSTATS_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL0RMV_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL1RMV_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL0FMB_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL1FMB_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEMIL_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_MEMMGMIL_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL0WMV_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL1WMV_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_MECONF_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_MEWMAP_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_MEFMV_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_MEFST_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_MELMI_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL0WFMB_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_MEL1WFMB_CAPTURE,
	/* IMGSYS_MODULE_WPE */
	MTK_IMGSYS_VIDEO_NODE_ID_WWPEI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_WVECI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_WPSP_COEFI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_WWPEO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_WMSKO_CAPTURE,
	/* IMGSYS_MODULE_WPE_TNR */
	MTK_IMGSYS_VIDEO_NODE_ID_WTWPEI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_WTVECI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_WTPSP_COEFI_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_WTWPEO_CAPTURE,
	MTK_IMGSYS_VIDEO_NODE_ID_WTMSKO_CAPTURE,
	/* other module video nodes to be added */
	MTK_IMGSYS_VIDEO_NODE_ID_TUNING_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_CTRLMETA_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_SIGDEV_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_SIGDEV_NORM_OUT,
	MTK_IMGSYS_VIDEO_NODE_ID_TOTAL_NUM,
};


#endif
