ccflags-y += -Idrivers/media/video/msmb
ccflags-y += -Idrivers/media/video/msmb/sensor
ccflags-y += -Idrivers/media/video/msmb/codecs
ccflags-y += -Idrivers/media/video/msmb/isps
ccflags-y += -Idrivers/media/video/msmb/pps
ccflags-y += -Idrivers/media/video/msmb/msm_vb2
ccflags-y += -Idrivers/media/video/msmb/camera

obj-$(CONFIG_ARCH_MSM8974) += msm.o
obj-$(CONFIG_ARCH_MSM8974) += camera/
obj-$(CONFIG_ARCH_MSM8974) += msm_vb2/
