ccflags-y += -Idrivers/media/video/msmb
ccflags-y += -Idrivers/media/video/msmb/sensor
ccflags-y += -Idrivers/media/video/msmb/codecs
ccflags-y += -Idrivers/media/video/msmb/isps
ccflags-y += -Idrivers/media/video/msmb/pps
ccflags-y += -Idrivers/media/video/msmb/msm_vb2
ccflags-y += -Idrivers/media/video/msmb/camera

obj-$(CONFIG_MSMB_CAMERA) += msm.o
obj-$(CONFIG_MSMB_CAMERA) += camera/
obj-$(CONFIG_MSMB_CAMERA) += msm_vb2/
obj-$(CONFIG_MSMB_CAMERA) += sensor/
obj-$(CONFIG_MSMB_CAMERA) += isp/
obj-$(CONFIG_MSMB_CAMERA) += ispif/
