
ccflags-y += -I$(srctree)/drivers/media/platform/mtk-isp \
	     -I$(srctree)/drivers/media/platform/mtk-isp/camsys/isp7_1

cam-ut-objs := mtk_cam_ut-cam.o \
	       mtk_cam_ut-seninf.o \
	       mtk_cam_ut.o \
	       mtk_cam_ut-camsv.o

obj-y += cam-ut.o
