#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# In case the platform does NOT support this type of sensors

obj-$(CONFIG_MTK_SCP_SENSORHUB) += SCP_sensorHub/
obj-$(CONFIG_MTK_SENSOR_HUB_SUPPORT) += SCP_shf/
obj-$(CONFIG_MTK_SCP_SENSORHUB_V1) += SCP_sensorHub_v1/
obj-$(CONFIG_NANOHUB) += SCP_nanoHub/
