# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/misc/mediatek/tinysys_scmi/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/smi/

obj-$(CONFIG_MTK_MMINFRA) += mtk-mminfra-debug.o
