# SPDX-License-Identifier: GPL-2.0
#
# Copyright (c) 2017 MediaTek Inc.
#

ccflags-y += \
	-I$(srctree)/drivers/misc/mediatek/base/power/include/	\
	-I$(srctree)/drivers/misc/mediatek/base/power/$(CONFIG_MTK_PLATFORM)\
	-I$(srctree)/drivers/misc/mediatek/include/mt-plat/	\
	-I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(CONFIG_MTK_PLATFORM)/include/mach	\
	-I$(srctree)/include/linux/	\
	-I$(DRCC_ROOT_DIR)/$(CONFIG_MTK_PLATFORM)/inc	\

obj-y += mtk_drcc.o

