include $(src)/Kbuild-mtk-custom-env

curr := platform/mtk_platform_common

mali_kbase-y += $(curr)/mtk_platform_common.o
mali_kbase-y += $(curr)/mtk_gpu_dvfs.o

ccflags-y += -I$(srctree)/drivers/devfreq/
