# MTK Platform Support

include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MT_SND_SOC_V3) += AudDrv_Afe.o AudDrv_Ana.o AudDrv_Clk.o
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_afe_control.o mt_soc_afe_connection.o mt_soc_pcm_common.o
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_pcm_capture.o mt_soc_pcm_dl1.o mt_soc_pcm_dummy.o mt_soc_pcm_routing.o mt_soc_pcm_capture2.o 
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_pcm_voice_md1.o mt_soc_pcm_voice_md2.o mt_soc_pcm_voice_md1_bt.o mt_soc_pcm_voice_md2_bt.o
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_pcm_hdmi.o mt_soc_pcm_dl1_i2s0.o mt_soc_pcm_dl1_i2s0Dl1.o mt_soc_pcm_i2s0_awb.o 
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_pcm_uldlloopback.o 
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_pcm_mrgrx.o mt_soc_pcm_mrgrx_awb.o mt_soc_pcm_fm_i2s.o mt_soc_pcm_fm_i2s_awb.o 
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_pcm_dl1_awb.o mt_soc_pcm_dl1_bt.o mt_soc_pcm_bt_dai.o
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_dai_stub.o mt_soc_dai_routing.o mt_soc_codec_dummy.o mt_soc_codec_63xx.o mt_soc_pcm_fmtx.o mt_soc_tdm_capture.o
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_pcm_hp_impedance.o
obj-$(CONFIG_MT_SND_SOC_V3) += mt_soc_machine.o
obj-$(CONFIG_MTK_SPEAKER) += mt_soc_codec_speaker_63xx.o
