# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_QPNP_SMB5)			+= step-chg-jeita.o battery.o qpnp-smb5.o smb5-lib.o pmic-voter.o storm-watch.o schgm-flash.o
obj-$(CONFIG_SMB1390_CHARGE_PUMP_PSY)	+= smb1390-charger-psy.o pmic-voter.o
obj-$(CONFIG_SMB1398_COMBO_CHARGE_PSY)	+= smb1398-charger-psy.o pmic-voter.o
obj-$(CONFIG_SMB1355_SLAVE_CHARGER)	+= smb1355-charger.o pmic-voter.o
obj-$(CONFIG_QPNP_QNOVO5)		+= qpnp-qnovo5.o battery.o pmic-voter.o
obj-$(CONFIG_QPNP_FG_GEN4)		+= qpnp-fg-gen4.o fg-memif.o fg-util.o fg-alg.o pmic-voter.o
obj-$(CONFIG_QPNP_QG)			+= qpnp-qg.o pmic-voter.o qg-util.o qg-soc.o qg-sdam.o qg-battery-profile.o qg-profile-lib.o fg-alg.o
obj-$(CONFIG_HL6111R)			+= hl6111r.o
obj-$(CONFIG_FUEL_GAUGE_BQ27Z561)       += bq27z561_fg.o
obj-$(CONFIG_IDT_P9415)			+= idtp9415.o
obj-$(CONFIG_RX1619_TRIM)	+= rx1619_trim.o
obj-$(CONFIG_RX1619)		+= rx1619.o
obj-$(CONFIG_LN8282)			+= ln8282.o
