# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2020 MediaTek Inc.

imgsensor_isp6s-objs += \
	../common/v1_1/camera_hw/imgsensor_cfg_table.o \
	../common/v1_1/camera_hw/regulator/regulator.o \
	../common/v1_1/camera_hw/gpio/gpio.o \
	../common/v1_1/camera_hw/mclk/mclk.o
# N17 code for HQ-293742 by miaozhongshu at 2023/05/08 start
imgsensor_isp6s-objs +=  ../common/v1_1/camera_hw/smartldo/smartldo.o
# N17 code for HQ-293742 by miaozhongshu at 2023/05/08 end 