ccflags-y += -Idrivers/media/platform/msm/ais/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/ais/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/ais/cam_sync
ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils

obj-$(CONFIG_MSM_AIS) += cam_context.o cam_context_utils.o cam_node.o cam_subdev.o
