ccflags-y += -Idrivers/media/video/msmb/
ccflags-y += -Idrivers/media/video/msmb/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_io_util.o msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_i2c_mux.o
