#
# (C) COPYRIGHT 2012-2013, 2016-2017 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
# SPDX-License-Identifier: GPL-2.0
#
#

include $(src)/Kbuild-mtk-custom-env

# MTK bring-up setting, set to 1 when bring-up
MT_GPUFREQ_BRINGUP ?= 0

mali_kbase-y += \
	$(MALI_PLATFORM_DIR)/mali_kbase_config_mt6785.o \
	$(MALI_PLATFORM_DIR)/mali_kbase_cpu_mt6785.o \
#	mali_kbase_platform_fake.o

ifeq ($(CONFIG_MTK_TINYSYS_SSPM_SUPPORT), y)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sspm/$(CONFIG_MTK_PLATFORM)
endif

ccflags-y += \
	-I$(srctree)/drivers/misc/mediatek/base/power/include \
	-I$(srctree)/drivers/misc/mediatek/gpu/gpu_bm \
	-I$(srctree)/drivers/misc/mediatek/gpu/hal \
	-I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM) \
	-DMT_GPUFREQ_BRINGUP=$(MT_GPUFREQ_BRINGUP) \
