# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_QCOM_HGSL) += hgsl.o \
                           hgsl_sync.o \
                           hgsl_memory.o \
                           hgsl_hyp.o \
                           hgsl_hyp_socket.o
obj-$(CONFIG_QCOM_HGSL_TCSR_SIGNAL) += hgsl_tcsr.o
