# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_HH_CTRL)		+= hh_ctrl.o
obj-$(CONFIG_HH_MSGQ)		+= hh_msgq.o
obj-$(CONFIG_HH_RM_DRV)		+= hh_rm_drv.o
hh_rm_drv-y 			:= hh_rm_core.o hh_rm_iface.o
obj-$(CONFIG_HH_DBL)		+= hh_dbl.o
obj-$(CONFIG_HH_IRQ_LEND)	+= hh_irq_lend.o
obj-$(CONFIG_HH_MEM_NOTIFIER)	+= hh_mem_notifier.o
obj-$(CONFIG_HH_VIRT_WATCHDOG)+= hh_virt_wdt.o