subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/misc
subdir-ccflags-y += -I$(srctree)/drivers/power/supply

obj-$(CONFIG_MT6360_PMIC)	+= mt6360_pmic_i2c.o mt6360_pmic_regmap.o
