# SPDX-License-Identifier: GPL-2.0
#
# Makefile for physical layer USB drivers
#
obj-$(CONFIG_USB_PHY)			+= phy.o
obj-$(CONFIG_OF)			+= of.o

# transceiver drivers, keep the list sorted

obj-$(CONFIG_AB8500_USB)		+= phy-ab8500-usb.o
obj-$(CONFIG_FSL_USB2_OTG)		+= phy-fsl-usb.o
obj-$(CONFIG_ISP1301_OMAP)		+= phy-isp1301-omap.o
obj-$(CONFIG_NOP_USB_XCEIV)		+= phy-generic.o
obj-$(CONFIG_TAHVO_USB)			+= phy-tahvo.o
obj-$(CONFIG_AM335X_CONTROL_USB)	+= phy-am335x-control.o
obj-$(CONFIG_AM335X_PHY_USB)		+= phy-am335x.o
obj-$(CONFIG_OMAP_OTG)			+= phy-omap-otg.o
obj-$(CONFIG_TWL6030_USB)		+= phy-twl6030-usb.o
obj-$(CONFIG_USB_TEGRA_PHY)		+= phy-tegra-usb.o
obj-$(CONFIG_USB_GPIO_VBUS)		+= phy-gpio-vbus-usb.o
obj-$(CONFIG_USB_ISP1301)		+= phy-isp1301.o
obj-$(CONFIG_USB_MV_OTG)		+= phy-mv-usb.o
obj-$(CONFIG_USB_MXS_PHY)		+= phy-mxs-usb.o
obj-$(CONFIG_USB_ULPI)			+= phy-ulpi.o
obj-$(CONFIG_USB_ULPI_VIEWPORT)		+= phy-ulpi-viewport.o
obj-$(CONFIG_KEYSTONE_USB_PHY)		+= phy-keystone.o
obj-$(CONFIG_JZ4770_PHY)		+= phy-jz4770.o
obj-$(CONFIG_SPRD_REDRIVER_PTN38003A)	+= ptn38003a-i2c.o
obj-$(CONFIG_USB_SPRD_UMS512_PHY)	+= phy-sprd-ums512.o
obj-$(CONFIG_SPRD_USB_DUMMY_PHY)	+= phy-sprd-dummy.o
obj-$(CONFIG_SPRD_BC1P2)		+= sprd-bc1p2.o
obj-$(CONFIG_SPRD_QOGIRN6PRO_USB2_PHY)	+= phy-sprd-qogirn6pro.o
obj-$(CONFIG_SPRD_QOGIRN6PRO_USB31_PHY)	+=phy-sprd-usb31-qogirn6pro.o
obj-$(CONFIG_SPRD_QOGIRN6LITE_USB2_PHY)	+= phy-sprd-qogirn6lite.o
obj-$(CONFIG_SPRD_QOGIRL6_USB2_PHY)	+= phy-sprd-qogirl6.o
obj-$(CONFIG_SPRD_PIKE2_USB2_PHY)       += phy-sprd-pike2.o
obj-$(CONFIG_SPRD_SHARKL5_USB2_PHY)	+= phy-sprd-sharkl5.o
obj-$(CONFIG_SPRD_SHARKL3_USB2_PHY)	+= phy-sprd-sharkl3.o
obj-$(CONFIG_SPRD_SHARKLE_USB2_PHY)     += phy-sprd-sharkle.o
obj-$(CONFIG_SPRD_COMMONPHY)		+= phy-sprd-commonphy.o
