/*
 * Copyright (C) 2020 UNISOC Technologies Co., Ltd.
 *
 * This file is dual-licensed: you can use it either under the terms
 * of the GPL or the X11 license, at your option. Note that this dual
 * licensing only applies to this file, and not this project as a
 * whole.
 *
 ********************************************************************
 * Auto generated c code from ASIC Documentation, PLEASE DONOT EDIT *
 ********************************************************************
 */

#ifndef __DT_BINDINGS_UNISOC_UMP9620_MASK_H
#define __DT_BINDINGS_UNISOC_UMP9620_MASK_H

#define MASK_ANA_CHIP_ID_LOW                                0xFFFF
#define MASK_ANA_CHIP_ID_HIGH                               0xFFFF
#define MASK_ANA_TYPEC_EN                                   0x4000
#define MASK_ANA_PD_EN                                      0x2000
#define MASK_ANA_TMR_EN                                     0x1000
#define MASK_ANA_FAST_CHG_EN                                0x0800
#define MASK_ANA_BLTC_EN                                    0x0200
#define MASK_ANA_PINREG_EN                                  0x0100
#define MASK_ANA_FGU_EN                                     0x0080
#define MASK_ANA_EFS_EN                                     0x0040
#define MASK_ANA_ADC_EN                                     0x0020
#define MASK_ANA_AUD_EN                                     0x0010
#define MASK_ANA_EIC_EN                                     0x0008
#define MASK_ANA_WDG_EN                                     0x0004
#define MASK_ANA_RTC_EN                                     0x0002
#define MASK_ANA_CLK_PD_SEL                                 0x0400
#define MASK_ANA_CLK_PD_EN                                  0x0200
#define MASK_ANA_CLK_AUD_SCLK_EN                            0x0080
#define MASK_ANA_CLK_AUXAD_EN                               0x0040
#define MASK_ANA_CLK_AUXADC_EN                              0x0020
#define MASK_ANA_CLK_AUD_IF_6P5M_EN                         0x0002
#define MASK_ANA_CLK_AUD_IF_EN                              0x0001
#define MASK_ANA_RTC_PD_EN                                  0x8000
#define MASK_ANA_RTC_TYPEC_EN                               0x4000
#define MASK_ANA_RTC_TMR_EN                                 0x2000
#define MASK_ANA_RTC_EFS_EN                                 0x0800
#define MASK_ANA_RTC_BLTC_EN                                0x0080
#define MASK_ANA_RTC_FGU_EN                                 0x0040
#define MASK_ANA_RTC_FAST_CHG_EN                            0x0010
#define MASK_ANA_RTC_EIC_EN                                 0x0008
#define MASK_ANA_RTC_WDG_EN                                 0x0004
#define MASK_ANA_RTC_RTC_EN                                 0x0002
#define MASK_ANA_RTC_ARCH_EN                                0x0001
#define MASK_ANA_AUDRX_SOFT_RST                             0x2000
#define MASK_ANA_AUDTX_SOFT_RST                             0x1000
#define MASK_ANA_BLTC_SOFT_RST                              0x0200
#define MASK_ANA_AUD_SOFT_RST                               0x0100
#define MASK_ANA_EFS_SOFT_RST                               0x0080
#define MASK_ANA_ADC_SOFT_RST                               0x0040
#define MASK_ANA_FGU_SOFT_RST                               0x0010
#define MASK_ANA_EIC_SOFT_RST                               0x0008
#define MASK_ANA_WDG_SOFT_RST                               0x0004
#define MASK_ANA_RTC_SOFT_RST                               0x0002
#define MASK_ANA_TYPEC_SOFT_RST                             0x0008
#define MASK_ANA_PD_SOFT_RST                                0x0004
#define MASK_ANA_TMR_SOFT_RST                               0x0002
#define MASK_ANA_FAST_CHG_SOFT_RST                          0x0001
#define MASK_ANA_LDO_VDD18_DCXO_PD                          0x4000
#define MASK_ANA_DCDC_SRAM0_PD                              0x2000
#define MASK_ANA_DCDC_MEMQ_PD                               0x1000
#define MASK_ANA_DCDC_PUB_PD                                0x0800
#define MASK_ANA_DCDC_CPU1_PD                               0x0400
#define MASK_ANA_LDO_EMM_PD                                 0x0200
#define MASK_ANA_DCDC_GEN0_PD                               0x0100
#define MASK_ANA_DCDC_GEN1_PD                               0x0080
#define MASK_ANA_DCDC_MEM_PD                                0x0040
#define MASK_ANA_DCDC_CORE_PD                               0x0020
#define MASK_ANA_DCDC_CPU2_PD                               0x0010
#define MASK_ANA_DCDC_GPU_PD                                0x0008
#define MASK_ANA_LDO_AVDD18_PD                              0x0004
#define MASK_ANA_LDO_VDD28_PD                               0x0002
#define MASK_ANA_BG_PD                                      0x0001
#define MASK_ANA_PWR_OFF_SEQ_EN                             0x0001
#define MASK_ANA_REG_SOFT_RST                               0x0001
#define MASK_ANA_AUXAD_VSS_SEL                              0x0001
#define MASK_ANA_ACK_BIT_OPT                                0x0001
#define MASK_ANA_DCDC_CPU2_DEADTIME                         0xC000
#define MASK_ANA_DCDC_CPU2_PDRSLOW                          0x00F0
#define MASK_ANA_DCDC_CPU2_PFMB                             0x0004
#define MASK_ANA_DCDC_CPU2_DCMB                             0x0002
#define MASK_ANA_DCDC_CPU2_CF                               0x0030
#define MASK_ANA_DCDC_CPU2_CL_CTRL                          0x0003
#define MASK_ANA_DCDC_CPU2_STBOP                            0x1FC0
#define MASK_ANA_DCDC_CPU2_ZCD                              0x0030
#define MASK_ANA_DCDC_CPU2_PFMAD                            0x000F
#define MASK_ANA_FRACTION_DIV_CPU2                          0x7800
#define MASK_ANA_INTEGER_DIV_CPU2                           0x0600
#define MASK_ANA_DCDC_CPU2_CTRL                             0x01FF
#define MASK_ANA_DCDC_GPU_DEADTIME                          0xC000
#define MASK_ANA_DCDC_GPU_PDRSLOW                           0x00F0
#define MASK_ANA_DCDC_GPU_PFMB                              0x0004
#define MASK_ANA_DCDC_GPU_DCMB                              0x0002
#define MASK_ANA_DCDC_GPU_CF                                0x0030
#define MASK_ANA_DCDC_GPU_CL_CTRL                           0x0003
#define MASK_ANA_DCDC_GPU_STBOP                             0x1FC0
#define MASK_ANA_DCDC_GPU_ZCD                               0x0030
#define MASK_ANA_DCDC_GPU_PFMAD                             0x000F
#define MASK_ANA_FRACTION_DIV_GPU                           0x7800
#define MASK_ANA_INTEGER_DIV_GPU                            0x0600
#define MASK_ANA_DCDC_GPU_CTRL                              0x01FF
#define MASK_ANA_DCDC_CORE_DEADTIME                         0xC000
#define MASK_ANA_DCDC_CORE_PDRSLOW                          0x00F0
#define MASK_ANA_DCDC_CORE_PFMB                             0x0004
#define MASK_ANA_DCDC_CORE_DCMB                             0x0002
#define MASK_ANA_DCDC_CORE_CF                               0x0030
#define MASK_ANA_DCDC_CORE_CL_CTRL                          0x0003
#define MASK_ANA_DCDC_CORE_STBOP                            0x1FC0
#define MASK_ANA_DCDC_CORE_ZCD                              0x0030
#define MASK_ANA_DCDC_CORE_PFMAD                            0x000F
#define MASK_ANA_FRACTION_DIV_CORE                          0x7800
#define MASK_ANA_INTEGER_DIV_CORE                           0x0600
#define MASK_ANA_DCDC_CORE_CTRL                             0x01FF
#define MASK_ANA_DCDC_PUB_DEADTIME                          0xC000
#define MASK_ANA_DCDC_PUB_PDRSLOW                           0x00F0
#define MASK_ANA_DCDC_PUB_PFMB                              0x0004
#define MASK_ANA_DCDC_PUB_DCMB                              0x0002
#define MASK_ANA_DCDC_PUB_CF                                0x0030
#define MASK_ANA_DCDC_PUB_CL_CTRL                           0x0003
#define MASK_ANA_DCDC_PUB_STBOP                             0x1FC0
#define MASK_ANA_DCDC_PUB_ZCD                               0x0030
#define MASK_ANA_DCDC_PUB_PFMAD                             0x000F
#define MASK_ANA_FRACTION_DIV_PUB                           0x7800
#define MASK_ANA_INTEGER_DIV_PUB                            0x0600
#define MASK_ANA_DCDC_PUB_CTRL                              0x01FF
#define MASK_ANA_DCDC_MEM_DEADTIME                          0xC000
#define MASK_ANA_DCDC_MEM_PDRSLOW                           0x00F0
#define MASK_ANA_DCDC_MEM_PFMB                              0x0004
#define MASK_ANA_DCDC_MEM_DCMB                              0x0002
#define MASK_ANA_DCDC_MEM_CF                                0x0030
#define MASK_ANA_DCDC_MEM_CL_CTRL                           0x0003
#define MASK_ANA_DCDC_MEM_STBOP                             0x1FC0
#define MASK_ANA_DCDC_MEM_ZCD                               0x0030
#define MASK_ANA_DCDC_MEM_PFMAD                             0x000F
#define MASK_ANA_DCDC_MEM_CTRL                              0x00FF
#define MASK_ANA_DCDC_MEMQ_DEADTIME                         0xC000
#define MASK_ANA_DCDC_MEMQ_PDRSLOW                          0x00F0
#define MASK_ANA_DCDC_MEMQ_PFMB                             0x0004
#define MASK_ANA_DCDC_MEMQ_DCMB                             0x0002
#define MASK_ANA_DCDC_MEMQ_CF                               0x0030
#define MASK_ANA_DCDC_MEMQ_CL_CTRL                          0x0003
#define MASK_ANA_DCDC_MEMQ_STBOP                            0x1FC0
#define MASK_ANA_DCDC_MEMQ_ZCD                              0x0030
#define MASK_ANA_DCDC_MEMQ_PFMAD                            0x000F
#define MASK_ANA_DCDC_MEMQ_CTRL                             0x01FF
#define MASK_ANA_DCDC_GEN0_DEADTIME                         0xC000
#define MASK_ANA_DCDC_GEN0_PDRSLOW                          0x00F0
#define MASK_ANA_DCDC_GEN0_PFMB                             0x0004
#define MASK_ANA_DCDC_GEN0_DCMB                             0x0002
#define MASK_ANA_DCDC_GEN0_CF                               0x0030
#define MASK_ANA_DCDC_GEN0_CL_CTRL                          0x0003
#define MASK_ANA_DCDC_GEN0_STBOP                            0x1FC0
#define MASK_ANA_DCDC_GEN0_ZCD                              0x0030
#define MASK_ANA_DCDC_GEN0_PFMAD                            0x000F
#define MASK_ANA_DCDC_GEN0_CTRL                             0x00FF
#define MASK_ANA_DCDC_GEN1_DEADTIME                         0xC000
#define MASK_ANA_DCDC_GEN1_PDRSLOW                          0x00F0
#define MASK_ANA_DCDC_GEN1_PFMB                             0x0004
#define MASK_ANA_DCDC_GEN1_DCMB                             0x0002
#define MASK_ANA_DCDC_GEN1_CF                               0x0030
#define MASK_ANA_DCDC_GEN1_CL_CTRL                          0x0003
#define MASK_ANA_DCDC_GEN1_STBOP                            0x1FC0
#define MASK_ANA_DCDC_GEN1_ZCD                              0x0030
#define MASK_ANA_DCDC_GEN1_PFMAD                            0x000F
#define MASK_ANA_DCDC_GEN1_CTRL                             0x00FF
#define MASK_ANA_DCDC_WPA_DEADTIME                          0xC000
#define MASK_ANA_DCDC_WPA_PDRSLOW                           0x00F0
#define MASK_ANA_DCDC_WPA_CF                                0x000C
#define MASK_ANA_DCDC_WPA_CL_CTRL                           0x0003
#define MASK_ANA_DCDC_WPA_OS_DET_EN                         0x8000
#define MASK_ANA_DCDC_WPA_VBAT_DIV                          0x7000
#define MASK_ANA_DCDC_WPA_BPEN                              0x0800
#define MASK_ANA_DCDC_WPA_BPMODE                            0x0400
#define MASK_ANA_DCDC_WPA_DEGEN                             0x0200
#define MASK_ANA_DCDC_WPA_APTEN                             0x0100
#define MASK_ANA_DCDC_WPA_DEBC_SEL                          0x00C0
#define MASK_ANA_DCDC_WPA_FRTHRD                            0x0030
#define MASK_ANA_DCDC_WPA_FREN                              0x0008
#define MASK_ANA_DCDC_WPA_DEG_CUR_SEL                       0x0004
#define MASK_ANA_DCDC_WPA_PFMB                              0x0002
#define MASK_ANA_DCDC_WPA_APT2P5XEN                         0x0001
#define MASK_ANA_DCDC_WPA_PD                                0x0020
#define MASK_ANA_DCDC_WPA_VREF_CAL                          0x001F
#define MASK_ANA_DCDC_WPA_STBOP                             0x1FC0
#define MASK_ANA_DCDC_WPA_ZCD                               0x0030
#define MASK_ANA_DCDC_WPA_PFMAD                             0x000F
#define MASK_ANA_DCDC_WPA_FR_CUR_CTRL                       0x0C00
#define MASK_ANA_DCDC_WPA_FR_EMI_CTRL                       0x0300
#define MASK_ANA_DCDC_WPA_CTRL                              0x00FF
#define MASK_ANA_DCDC_WPA_DCMB                              0x0001
#define MASK_ANA_DCDC_SRAM0_DEADTIME                        0xC000
#define MASK_ANA_DCDC_SRAM0_PDRSLOW                         0x00F0
#define MASK_ANA_DCDC_SRAM0_PFMB                            0x0004
#define MASK_ANA_DCDC_SRAM0_DCMB                            0x0002
#define MASK_ANA_DCDC_SRAM0_CF                              0x0030
#define MASK_ANA_DCDC_SRAM0_CL_CTRL                         0x0003
#define MASK_ANA_DCDC_SRAM0_STBOP                           0x1FC0
#define MASK_ANA_DCDC_SRAM0_ZCD                             0x0030
#define MASK_ANA_DCDC_SRAM0_PFMAD                           0x000F
#define MASK_ANA_FRACTION_DIV_SRAM0                         0x7800
#define MASK_ANA_INTEGER_DIV_SRAM0                          0x0600
#define MASK_ANA_DCDC_SRAM0_CTRL                            0x01FF
#define MASK_ANA_DCDC_CAL_SEL                               0x000F
#define MASK_ANA_DCDC_OSCCLK_OPTION                         0x1800
#define MASK_ANA_DCDC_6MCLKOUT_EN                           0x2000
#define MASK_ANA_DCDC_6MFRECAL_SW                           0x1F00
#define MASK_ANA_CLK6M_AUTOGATE_DELAY                       0x00F0
#define MASK_ANA_DCDC_6MCLKOUT_GATE_SW                      0x0008
#define MASK_ANA_DCDC_6MCLKOUT_AUTOGATE_EN                  0x0004
#define MASK_ANA_DCDC_CLK_SP_SEL                            0x0002
#define MASK_ANA_DCDC_CLK_SP_EN                             0x0001
#define MASK_ANA_LDO_AVDD18_V                               0x003F
#define MASK_ANA_LDO_AVDD18_SHPT_PD                         0x0020
#define MASK_ANA_LDO_AVDD18_REFTRIM                         0x001F
#define MASK_ANA_LDO_VDDRF1V8_PD                            0x0001
#define MASK_ANA_LDO_VDDRF1V8_V                             0x003F
#define MASK_ANA_LDO_VDDRF1V8_SHPT_PD                       0x0020
#define MASK_ANA_LDO_VDDRF1V8_REFTRIM                       0x001F
#define MASK_ANA_LDO_VDDCAMIO_PD                            0x0001
#define MASK_ANA_LDO_VDDWCN_PD                              0x0001
#define MASK_ANA_LDO_VDDWCN_V                               0x003F
#define MASK_ANA_LDO_VDDWCN_SHPT_PD                         0x0020
#define MASK_ANA_LDO_VDDWCN_REFTRIM                         0x001F
#define MASK_ANA_LDO_VDDCAMD1_PD                            0x0001
#define MASK_ANA_LDO_VDDCAMD1_V                             0x001F
#define MASK_ANA_LDO_VDDCAMD1_SHPT_PD                       0x0020
#define MASK_ANA_LDO_VDDCAMD1_REFTRIM                       0x001F
#define MASK_ANA_LDO_VDDCAMD0_PD                            0x0001
#define MASK_ANA_LDO_VDDCAMD0_V                             0x001F
#define MASK_ANA_LDO_VDDCAMD0_SHPT_PD                       0x0020
#define MASK_ANA_LDO_VDDCAMD0_REFTRIM                       0x001F
#define MASK_ANA_LDO_VDDCAMMOT1_PD                          0x0001
#define MASK_ANA_LDO_VDDCAMMOT1_V                           0x00FF
#define MASK_ANA_LDO_VDDCAMMOT1_SHPT_PD                     0x0040
#define MASK_ANA_LDO_VDDCAMMOT1_REFTRIM                     0x003E
#define MASK_ANA_LDO_AVDD12_PD                              0x0001
#define MASK_ANA_LDO_AVDD12_V                               0x001F
#define MASK_ANA_LDO_AVDD12_SHPT_PD                         0x0020
#define MASK_ANA_LDO_AVDD12_REFTRIM                         0x001F
#define MASK_ANA_LDO_VDDCAMA0_PD                            0x0001
#define MASK_ANA_LDO_VDDCAMA0_V                             0x00FF
#define MASK_ANA_LDO_VDDCAMA0_REFTRIM                       0x007C
#define MASK_ANA_LDO_VDDCAMA0_SHPT_PD                       0x0002
#define MASK_ANA_LDO_VDDCAMA1_PD                            0x0001
#define MASK_ANA_LDO_VDDCAMA1_V                             0x00FF
#define MASK_ANA_LDO_VDDCAMA1_REFTRIM                       0x007C
#define MASK_ANA_LDO_VDDCAMA1_SHPT_PD                       0x0002
#define MASK_ANA_LDO_VDDCAMMOT0_PD                          0x0001
#define MASK_ANA_LDO_VDDCAMMOT0_V                           0x00FF
#define MASK_ANA_LDO_VDDCAMMOT0_SHPT_PD                     0x0040
#define MASK_ANA_LDO_VDDCAMMOT0_REFTRIM                     0x003E
#define MASK_ANA_LDO_VDDSIM0_PD                             0x0001
#define MASK_ANA_LDO_VDDSIM0_V                              0x00FF
#define MASK_ANA_LDO_VDDSIM0_SHPT_PD                        0x0040
#define MASK_ANA_LDO_VDDSIM0_REFTRIM                        0x003E
#define MASK_ANA_LDO_VDDSIM1_PD                             0x0001
#define MASK_ANA_LDO_VDDSIM1_V                              0x00FF
#define MASK_ANA_LDO_VDDSIM1_SHPT_PD                        0x0040
#define MASK_ANA_LDO_VDDSIM1_REFTRIM                        0x003E
#define MASK_ANA_LDO_VDDSIM2_PD                             0x0001
#define MASK_ANA_LDO_VDDSIM2_V                              0x00FF
#define MASK_ANA_LDO_VDDSIM2_SHPT_PD                        0x0040
#define MASK_ANA_LDO_VDDSIM2_REFTRIM                        0x003E
#define MASK_ANA_LDO_VDDEMMCCORE_PD                         0x0001
#define MASK_ANA_LDO_VDDEMMCCORE_V                          0x00FF
#define MASK_ANA_LDO_VDDEMMCCORE_CL_ADJ                     0x0780
#define MASK_ANA_LDO_VDDEMMCCORE_SHPT_PD                    0x0040
#define MASK_ANA_LDO_VDDEMMCCORE_REFTRIM                    0x003E
#define MASK_ANA_LDO_VDDSDCORE_PD                           0x0001
#define MASK_ANA_LDO_VDDSDCORE_V                            0x00FF
#define MASK_ANA_LDO_VDDSDCORE_CL_ADJ                       0x0780
#define MASK_ANA_LDO_VDDSDCORE_SHPT_PD                      0x0040
#define MASK_ANA_LDO_VDDSDCORE_REFTRIM                      0x003E
#define MASK_ANA_LDO_VDDSDIO_PD                             0x0001
#define MASK_ANA_LDO_VDDSDIO_V                              0x00FF
#define MASK_ANA_LDO_VDDSDIO_SHPT_PD                        0x0040
#define MASK_ANA_LDO_VDDSDIO_REFTRIM                        0x003E
#define MASK_ANA_LDO_VDD28_V                                0x00FF
#define MASK_ANA_LDO_VDD28_SHPT_PD                          0x0040
#define MASK_ANA_LDO_VDD28_REFTRIM                          0x003E
#define MASK_ANA_LDO_VDDWIFIPA_PD                           0x0001
#define MASK_ANA_LDO_VDDWIFIPA_V                            0x00FF
#define MASK_ANA_LDO_VDDWIFIPA_CL_ADJ                       0x0780
#define MASK_ANA_LDO_VDDWIFIPA_SHPT_PD                      0x0040
#define MASK_ANA_LDO_VDDWIFIPA_REFTRIM                      0x003E
#define MASK_ANA_LDO_VDD18_DCXO_V                           0x00FF
#define MASK_ANA_LDO_VDD18_DCXO_REFTRIM_LP                  0x0780
#define MASK_ANA_LDO_VDD18_DCXO_SHPT_PD                     0x0040
#define MASK_ANA_LDO_VDD18_DCXO_REFTRIM                     0x003E
#define MASK_ANA_LDO_VDDUSB33_PD                            0x0001
#define MASK_ANA_LDO_VDDUSB33_V                             0x00FF
#define MASK_ANA_LDO_VDDUSB33_SHPT_PD                       0x0040
#define MASK_ANA_LDO_VDDUSB33_REFTRIM                       0x003E
#define MASK_ANA_LDO_VDDLDO0_PD                             0x0001
#define MASK_ANA_LDO_VDDLDO0_V                              0x00FF
#define MASK_ANA_LDO_VDDLDO0_SHPT_PD                        0x0040
#define MASK_ANA_LDO_VDDLDO0_REFTRIM                        0x003E
#define MASK_ANA_LDO_VDDLDO1_PD                             0x0001
#define MASK_ANA_LDO_VDDLDO1_V                              0x00FF
#define MASK_ANA_LDO_VDDLDO1_SHPT_PD                        0x0040
#define MASK_ANA_LDO_VDDLDO1_REFTRIM                        0x003E
#define MASK_ANA_LDO_VDDLDO2_PD                             0x0001
#define MASK_ANA_LDO_VDDLDO2_V                              0x00FF
#define MASK_ANA_LDO_VDDLDO2_CL_ADJ                         0x0780
#define MASK_ANA_LDO_VDDLDO2_SHPT_PD                        0x0040
#define MASK_ANA_LDO_VDDLDO2_REFTRIM                        0x003E
#define MASK_ANA_RC1M_CAL                                   0xFE00
#define MASK_ANA_LDO_RTC_CAL                                0x01F0
#define MASK_ANA_LDO_RTC_V                                  0x000C
#define MASK_ANA_VBATBK_V                                   0x0003
#define MASK_ANA_LDODCDC_CAL_SEL                            0x7800
#define MASK_ANA_LDOA_CAL_SEL                               0x0780
#define MASK_ANA_LDOB_CAL_SEL                               0x0070
#define MASK_ANA_LDO_XTL_EN                                 0x0004
#define MASK_ANA_SLP_IO_EN                                  0x0002
#define MASK_ANA_SLP_LDO_PD_EN                              0x0001
#define MASK_ANA_SLP_DCDCPUB_PD_EN                          0x0400
#define MASK_ANA_SLP_DCDCMEMQ_PD_EN                         0x0200
#define MASK_ANA_SLP_DCDCSRAM0_PD_EN                        0x0100
#define MASK_ANA_SLP_DCDCSRAM0_DROP_EN                      0x0080
#define MASK_ANA_SLP_DCDCPUB_DROP_EN                        0x0040
#define MASK_ANA_SLP_DCDCGPU_DROP_EN                        0x0020
#define MASK_ANA_SLP_DCDCCORE_DROP_EN                       0x0010
#define MASK_ANA_SLP_DCDCWPA_PD_EN                          0x0008
#define MASK_ANA_SLP_DCDCGPU_PD_EN                          0x0004
#define MASK_ANA_SLP_DCDCGEN1_PD_EN                         0x0001
#define MASK_ANA_SLP_LDO_VDDRF1V1_PD_EN                     0x8000
#define MASK_ANA_SLP_LDO_VDDRF1V8_PD_EN                     0x4000
#define MASK_ANA_SLP_LDO_VDDRF0V9_PD_EN                     0x2000
#define MASK_ANA_SLP_LDO_VDDEMMCCORE_PD_EN                  0x1000
#define MASK_ANA_SLP_LDO_VDD18_DCXO_PD_EN                   0x0800
#define MASK_ANA_SLP_LDO_VDDWIFIPA_PD_EN                    0x0400
#define MASK_ANA_SLP_LDO_VDD28_PD_EN                        0x0200
#define MASK_ANA_SLP_LDO_VDDSDCORE_PD_EN                    0x0100
#define MASK_ANA_SLP_LDO_VDDSDIO_PD_EN                      0x0080
#define MASK_ANA_SLP_LDO_VDDUSB33_PD_EN                     0x0040
#define MASK_ANA_SLP_LDO_VDDCAMMOT0_PD_EN                   0x0020
#define MASK_ANA_SLP_LDO_VDDCAMIO_PD_EN                     0x0010
#define MASK_ANA_SLP_LDO_VDDCAMD0_PD_EN                     0x0008
#define MASK_ANA_SLP_LDO_VDDCAMA0_PD_EN                     0x0004
#define MASK_ANA_SLP_LDO_VDDSIM2_PD_EN                      0x0002
#define MASK_ANA_SLP_LDO_VDDSIM1_PD_EN                      0x0001
#define MASK_ANA_SLP_LDO_VDDUFS1V2_PD_EN                    0x1000
#define MASK_ANA_SLP_LDO_VDDLDO4_PD_EN                      0x0800
#define MASK_ANA_SLP_LDO_VDDLDO3_PD_EN                      0x0400
#define MASK_ANA_SLP_LDO_VDDCAMMOT1_PD_EN                   0x0200
#define MASK_ANA_SLP_LDO_VDDLDO2_PD_EN                      0x0100
#define MASK_ANA_SLP_LDO_AVDD12_PD_EN                       0x0080
#define MASK_ANA_SLP_LDO_VDDWCN_PD_EN                       0x0040
#define MASK_ANA_SLP_LDO_VDDLDO0_PD_EN                      0x0020
#define MASK_ANA_SLP_LDO_VDDCAMD1_PD_EN                     0x0010
#define MASK_ANA_SLP_LDO_VDDCAMA1_PD_EN                     0x0008
#define MASK_ANA_SLP_LDO_VDDSIM0_PD_EN                      0x0004
#define MASK_ANA_SLP_LDO_AVDD18_PD_EN                       0x0002
#define MASK_ANA_SLP_LDO_VDDLDO1_PD_EN                      0x0001
#define MASK_ANA_SLP_DCDCSRAM0_LP_EN                        0x0200
#define MASK_ANA_SLP_DCDCPUB_LP_EN                          0x0100
#define MASK_ANA_SLP_DCDCMEMQ_LP_EN                         0x0080
#define MASK_ANA_SLP_DCDCMEM_LP_EN                          0x0040
#define MASK_ANA_SLP_DCDCGPU_LP_EN                          0x0020
#define MASK_ANA_SLP_DCDCCORE_LP_EN                         0x0010
#define MASK_ANA_SLP_DCDCGEN1_LP_EN                         0x0004
#define MASK_ANA_SLP_DCDCGEN0_LP_EN                         0x0002
#define MASK_ANA_SLP_DCDCWPA_LP_EN                          0x0001
#define MASK_ANA_SLP_LDO_VDDUFS1V2_LP_EN                    0x8000
#define MASK_ANA_SLP_LDO_VDDRF1V8_LP_EN                     0x4000
#define MASK_ANA_SLP_LDO_VDDRF0V9_LP_EN                     0x2000
#define MASK_ANA_SLP_LDO_VDDEMMCCORE_LP_EN                  0x1000
#define MASK_ANA_SLP_LDO_VDD18_DCXO_LP_EN                   0x0800
#define MASK_ANA_SLP_LDO_VDDWIFIPA_LP_EN                    0x0400
#define MASK_ANA_SLP_LDO_VDD28_LP_EN                        0x0200
#define MASK_ANA_SLP_LDO_VDDSDCORE_LP_EN                    0x0100
#define MASK_ANA_SLP_LDO_VDDSDIO_LP_EN                      0x0080
#define MASK_ANA_SLP_LDO_VDDUSB33_LP_EN                     0x0040
#define MASK_ANA_SLP_LDO_VDDCAMMOT0_LP_EN                   0x0020
#define MASK_ANA_SLP_LDO_VDDRF1V1_LP_EN                     0x0010
#define MASK_ANA_SLP_LDO_VDDCAMD0_LP_EN                     0x0008
#define MASK_ANA_SLP_LDO_VDDCAMA0_LP_EN                     0x0004
#define MASK_ANA_SLP_LDO_VDDSIM2_LP_EN                      0x0002
#define MASK_ANA_SLP_LDO_VDDSIM1_LP_EN                      0x0001
#define MASK_ANA_SLP_LDO_VDDLDO4_LP_EN                      0x0800
#define MASK_ANA_SLP_LDO_VDDLDO3_LP_EN                      0x0400
#define MASK_ANA_SLP_LDO_VDDCAMMOT1_LP_EN                   0x0200
#define MASK_ANA_SLP_LDO_VDDLDO2_LP_EN                      0x0100
#define MASK_ANA_SLP_LDO_AVDD12_LP_EN                       0x0080
#define MASK_ANA_SLP_LDO_VDDWCN_LP_EN                       0x0040
#define MASK_ANA_SLP_LDO_VDDCAMD1_LP_EN                     0x0020
#define MASK_ANA_SLP_LDO_VDDCAMA1_LP_EN                     0x0010
#define MASK_ANA_SLP_LDO_VDDLDO0_LP_EN                      0x0008
#define MASK_ANA_SLP_LDO_VDDSIM0_LP_EN                      0x0004
#define MASK_ANA_SLP_LDO_AVDD18_LP_EN                       0x0002
#define MASK_ANA_SLP_LDO_VDDLDO1_LP_EN                      0x0001
#define MASK_ANA_DCDC_CORE_SLP_STEP_DELAY                   0x3000
#define MASK_ANA_DCDC_CORE_SLP_STEP_VOL                     0x00F8
#define MASK_ANA_SLP_CORE_CLK6M_SW_EN                       0x0002
#define MASK_ANA_DCDC_CORE_SLP_STEP_EN                      0x0001
#define MASK_ANA_DCDC_CORE_CTRL_DS_SW                       0x01FF
#define MASK_ANA_DCDC_GPU_SLP_STEP_DELAY                    0x3000
#define MASK_ANA_DCDC_GPU_SLP_STEP_VOL                      0x00F8
#define MASK_ANA_SLP_GPU_CLK6M_SW_EN                        0x0002
#define MASK_ANA_DCDC_GPU_SLP_STEP_EN                       0x0001
#define MASK_ANA_DCDC_GPU_CTRL_DS_SW                        0x01FF
#define MASK_ANA_DCDC_PUB_SLP_STEP_DELAY                    0x3000
#define MASK_ANA_DCDC_PUB_SLP_STEP_VOL                      0x00F8
#define MASK_ANA_SLP_PUB_CLK6M_SW_EN                        0x0002
#define MASK_ANA_DCDC_PUB_SLP_STEP_EN                       0x0001
#define MASK_ANA_DCDC_PUB_CTRL_DS_SW                        0x01FF
#define MASK_ANA_DCDC_SRAM0_SLP_STEP_DELAY                  0x3000
#define MASK_ANA_DCDC_SRAM0_SLP_STEP_VOL                    0x00F8
#define MASK_ANA_SLP_SRAM0_CLK6M_SW_EN                      0x0002
#define MASK_ANA_DCDC_SRAM0_SLP_STEP_EN                     0x0001
#define MASK_ANA_DCDC_SRAM0_CTRL_DS_SW                      0x01FF
#define MASK_ANA_DCDC_CORE_EXT_XTL6_EN                      0x4000
#define MASK_ANA_DCDC_CORE_EXT_XTL5_EN                      0x2000
#define MASK_ANA_DCDC_CORE_EXT_XTL4_EN                      0x1000
#define MASK_ANA_DCDC_CORE_EXT_XTL3_EN                      0x0800
#define MASK_ANA_DCDC_CORE_EXT_XTL2_EN                      0x0400
#define MASK_ANA_DCDC_CORE_EXT_XTL1_EN                      0x0200
#define MASK_ANA_DCDC_CORE_EXT_XTL0_EN                      0x0100
#define MASK_ANA_DCDC_WPA_EXT_XTL6_EN                       0x0040
#define MASK_ANA_DCDC_WPA_EXT_XTL5_EN                       0x0020
#define MASK_ANA_DCDC_WPA_EXT_XTL4_EN                       0x0010
#define MASK_ANA_DCDC_WPA_EXT_XTL3_EN                       0x0008
#define MASK_ANA_DCDC_WPA_EXT_XTL2_EN                       0x0004
#define MASK_ANA_DCDC_WPA_EXT_XTL1_EN                       0x0002
#define MASK_ANA_DCDC_WPA_EXT_XTL0_EN                       0x0001
#define MASK_ANA_DCDC_GEN0_EXT_XTL6_EN                      0x4000
#define MASK_ANA_DCDC_GEN0_EXT_XTL5_EN                      0x2000
#define MASK_ANA_DCDC_GEN0_EXT_XTL4_EN                      0x1000
#define MASK_ANA_DCDC_GEN0_EXT_XTL3_EN                      0x0800
#define MASK_ANA_DCDC_GEN0_EXT_XTL2_EN                      0x0400
#define MASK_ANA_DCDC_GEN0_EXT_XTL1_EN                      0x0200
#define MASK_ANA_DCDC_GEN0_EXT_XTL0_EN                      0x0100
#define MASK_ANA_DCDC_SRAM0_EXT_XTL6_EN                     0x0040
#define MASK_ANA_DCDC_SRAM0_EXT_XTL5_EN                     0x0020
#define MASK_ANA_DCDC_SRAM0_EXT_XTL4_EN                     0x0010
#define MASK_ANA_DCDC_SRAM0_EXT_XTL3_EN                     0x0008
#define MASK_ANA_DCDC_SRAM0_EXT_XTL2_EN                     0x0004
#define MASK_ANA_DCDC_SRAM0_EXT_XTL1_EN                     0x0002
#define MASK_ANA_DCDC_SRAM0_EXT_XTL0_EN                     0x0001
#define MASK_ANA_DCDC_GPU_EXT_XTL6_EN                       0x0040
#define MASK_ANA_DCDC_GPU_EXT_XTL5_EN                       0x0020
#define MASK_ANA_DCDC_GPU_EXT_XTL4_EN                       0x0010
#define MASK_ANA_DCDC_GPU_EXT_XTL3_EN                       0x0008
#define MASK_ANA_DCDC_GPU_EXT_XTL2_EN                       0x0004
#define MASK_ANA_DCDC_GPU_EXT_XTL1_EN                       0x0002
#define MASK_ANA_DCDC_GPU_EXT_XTL0_EN                       0x0001
#define MASK_ANA_DCDC_MEM_EXT_XTL6_EN                       0x4000
#define MASK_ANA_DCDC_MEM_EXT_XTL5_EN                       0x2000
#define MASK_ANA_DCDC_MEM_EXT_XTL4_EN                       0x1000
#define MASK_ANA_DCDC_MEM_EXT_XTL3_EN                       0x0800
#define MASK_ANA_DCDC_MEM_EXT_XTL2_EN                       0x0400
#define MASK_ANA_DCDC_MEM_EXT_XTL1_EN                       0x0200
#define MASK_ANA_DCDC_MEM_EXT_XTL0_EN                       0x0100
#define MASK_ANA_DCDC_GEN1_EXT_XTL6_EN                      0x0040
#define MASK_ANA_DCDC_GEN1_EXT_XTL5_EN                      0x0020
#define MASK_ANA_DCDC_GEN1_EXT_XTL4_EN                      0x0010
#define MASK_ANA_DCDC_GEN1_EXT_XTL3_EN                      0x0008
#define MASK_ANA_DCDC_GEN1_EXT_XTL2_EN                      0x0004
#define MASK_ANA_DCDC_GEN1_EXT_XTL1_EN                      0x0002
#define MASK_ANA_DCDC_GEN1_EXT_XTL0_EN                      0x0001
#define MASK_ANA_DCDC_MEMQ_EXT_XTL6_EN                      0x4000
#define MASK_ANA_DCDC_MEMQ_EXT_XTL5_EN                      0x2000
#define MASK_ANA_DCDC_MEMQ_EXT_XTL4_EN                      0x1000
#define MASK_ANA_DCDC_MEMQ_EXT_XTL3_EN                      0x0800
#define MASK_ANA_DCDC_MEMQ_EXT_XTL2_EN                      0x0400
#define MASK_ANA_DCDC_MEMQ_EXT_XTL1_EN                      0x0200
#define MASK_ANA_DCDC_MEMQ_EXT_XTL0_EN                      0x0100
#define MASK_ANA_DCDC_PUB_EXT_XTL6_EN                       0x0040
#define MASK_ANA_DCDC_PUB_EXT_XTL5_EN                       0x0020
#define MASK_ANA_DCDC_PUB_EXT_XTL4_EN                       0x0010
#define MASK_ANA_DCDC_PUB_EXT_XTL3_EN                       0x0008
#define MASK_ANA_DCDC_PUB_EXT_XTL2_EN                       0x0004
#define MASK_ANA_DCDC_PUB_EXT_XTL1_EN                       0x0002
#define MASK_ANA_DCDC_PUB_EXT_XTL0_EN                       0x0001
#define MASK_ANA_LDO_VDDRF0V9_EXT_XTL6_EN                   0x4000
#define MASK_ANA_LDO_VDDRF0V9_EXT_XTL5_EN                   0x2000
#define MASK_ANA_LDO_VDDRF0V9_EXT_XTL4_EN                   0x1000
#define MASK_ANA_LDO_VDDRF0V9_EXT_XTL3_EN                   0x0800
#define MASK_ANA_LDO_VDDRF0V9_EXT_XTL2_EN                   0x0400
#define MASK_ANA_LDO_VDDRF0V9_EXT_XTL1_EN                   0x0200
#define MASK_ANA_LDO_VDDRF0V9_EXT_XTL0_EN                   0x0100
#define MASK_ANA_LDO_VDD28_EXT_XTL6_EN                      0x0040
#define MASK_ANA_LDO_VDD28_EXT_XTL5_EN                      0x0020
#define MASK_ANA_LDO_VDD28_EXT_XTL4_EN                      0x0010
#define MASK_ANA_LDO_VDD28_EXT_XTL3_EN                      0x0008
#define MASK_ANA_LDO_VDD28_EXT_XTL2_EN                      0x0004
#define MASK_ANA_LDO_VDD28_EXT_XTL1_EN                      0x0002
#define MASK_ANA_LDO_VDD28_EXT_XTL0_EN                      0x0001
#define MASK_ANA_LDO_VDDRF1V8_EXT_XTL6_EN                   0x4000
#define MASK_ANA_LDO_VDDRF1V8_EXT_XTL5_EN                   0x2000
#define MASK_ANA_LDO_VDDRF1V8_EXT_XTL4_EN                   0x1000
#define MASK_ANA_LDO_VDDRF1V8_EXT_XTL3_EN                   0x0800
#define MASK_ANA_LDO_VDDRF1V8_EXT_XTL2_EN                   0x0400
#define MASK_ANA_LDO_VDDRF1V8_EXT_XTL1_EN                   0x0200
#define MASK_ANA_LDO_VDDRF1V8_EXT_XTL0_EN                   0x0100
#define MASK_ANA_LDO_VDDRF1V1_EXT_XTL6_EN                   0x0040
#define MASK_ANA_LDO_VDDRF1V1_EXT_XTL5_EN                   0x0020
#define MASK_ANA_LDO_VDDRF1V1_EXT_XTL4_EN                   0x0010
#define MASK_ANA_LDO_VDDRF1V1_EXT_XTL3_EN                   0x0008
#define MASK_ANA_LDO_VDDRF1V1_EXT_XTL2_EN                   0x0004
#define MASK_ANA_LDO_VDDRF1V1_EXT_XTL1_EN                   0x0002
#define MASK_ANA_LDO_VDDRF1V1_EXT_XTL0_EN                   0x0001
#define MASK_ANA_LDO_VDDSIM0_EXT_XTL6_EN                    0x4000
#define MASK_ANA_LDO_VDDSIM0_EXT_XTL5_EN                    0x2000
#define MASK_ANA_LDO_VDDSIM0_EXT_XTL4_EN                    0x1000
#define MASK_ANA_LDO_VDDSIM0_EXT_XTL3_EN                    0x0800
#define MASK_ANA_LDO_VDDSIM0_EXT_XTL2_EN                    0x0400
#define MASK_ANA_LDO_VDDSIM0_EXT_XTL1_EN                    0x0200
#define MASK_ANA_LDO_VDDSIM0_EXT_XTL0_EN                    0x0100
#define MASK_ANA_LDO_VDDSIM1_EXT_XTL6_EN                    0x0040
#define MASK_ANA_LDO_VDDSIM1_EXT_XTL5_EN                    0x0020
#define MASK_ANA_LDO_VDDSIM1_EXT_XTL4_EN                    0x0010
#define MASK_ANA_LDO_VDDSIM1_EXT_XTL3_EN                    0x0008
#define MASK_ANA_LDO_VDDSIM1_EXT_XTL2_EN                    0x0004
#define MASK_ANA_LDO_VDDSIM1_EXT_XTL1_EN                    0x0002
#define MASK_ANA_LDO_VDDSIM1_EXT_XTL0_EN                    0x0001
#define MASK_ANA_LDO_VDDSIM2_EXT_XTL6_EN                    0x4000
#define MASK_ANA_LDO_VDDSIM2_EXT_XTL5_EN                    0x2000
#define MASK_ANA_LDO_VDDSIM2_EXT_XTL4_EN                    0x1000
#define MASK_ANA_LDO_VDDSIM2_EXT_XTL3_EN                    0x0800
#define MASK_ANA_LDO_VDDSIM2_EXT_XTL2_EN                    0x0400
#define MASK_ANA_LDO_VDDSIM2_EXT_XTL1_EN                    0x0200
#define MASK_ANA_LDO_VDDSIM2_EXT_XTL0_EN                    0x0100
#define MASK_ANA_LDO_AVDD12_EXT_XTL6_EN                     0x0040
#define MASK_ANA_LDO_AVDD12_EXT_XTL5_EN                     0x0020
#define MASK_ANA_LDO_AVDD12_EXT_XTL4_EN                     0x0010
#define MASK_ANA_LDO_AVDD12_EXT_XTL3_EN                     0x0008
#define MASK_ANA_LDO_AVDD12_EXT_XTL2_EN                     0x0004
#define MASK_ANA_LDO_AVDD12_EXT_XTL1_EN                     0x0002
#define MASK_ANA_LDO_AVDD12_EXT_XTL0_EN                     0x0001
#define MASK_ANA_LDO_VDDCAMMOT0_EXT_XTL6_EN                 0x4000
#define MASK_ANA_LDO_VDDCAMMOT0_EXT_XTL5_EN                 0x2000
#define MASK_ANA_LDO_VDDCAMMOT0_EXT_XTL4_EN                 0x1000
#define MASK_ANA_LDO_VDDCAMMOT0_EXT_XTL3_EN                 0x0800
#define MASK_ANA_LDO_VDDCAMMOT0_EXT_XTL2_EN                 0x0400
#define MASK_ANA_LDO_VDDCAMMOT0_EXT_XTL1_EN                 0x0200
#define MASK_ANA_LDO_VDDCAMMOT0_EXT_XTL0_EN                 0x0100
#define MASK_ANA_LDO_VDDCAMIO_EXT_XTL6_EN                   0x0040
#define MASK_ANA_LDO_VDDCAMIO_EXT_XTL5_EN                   0x0020
#define MASK_ANA_LDO_VDDCAMIO_EXT_XTL4_EN                   0x0010
#define MASK_ANA_LDO_VDDCAMIO_EXT_XTL3_EN                   0x0008
#define MASK_ANA_LDO_VDDCAMIO_EXT_XTL2_EN                   0x0004
#define MASK_ANA_LDO_VDDCAMIO_EXT_XTL1_EN                   0x0002
#define MASK_ANA_LDO_VDDCAMIO_EXT_XTL0_EN                   0x0001
#define MASK_ANA_LDO_VDDCAMA0_EXT_XTL6_EN                   0x4000
#define MASK_ANA_LDO_VDDCAMA0_EXT_XTL5_EN                   0x2000
#define MASK_ANA_LDO_VDDCAMA0_EXT_XTL4_EN                   0x1000
#define MASK_ANA_LDO_VDDCAMA0_EXT_XTL3_EN                   0x0800
#define MASK_ANA_LDO_VDDCAMA0_EXT_XTL2_EN                   0x0400
#define MASK_ANA_LDO_VDDCAMA0_EXT_XTL1_EN                   0x0200
#define MASK_ANA_LDO_VDDCAMA0_EXT_XTL0_EN                   0x0100
#define MASK_ANA_LDO_VDDCAMA1_EXT_XTL6_EN                   0x0040
#define MASK_ANA_LDO_VDDCAMA1_EXT_XTL5_EN                   0x0020
#define MASK_ANA_LDO_VDDCAMA1_EXT_XTL4_EN                   0x0010
#define MASK_ANA_LDO_VDDCAMA1_EXT_XTL3_EN                   0x0008
#define MASK_ANA_LDO_VDDCAMA1_EXT_XTL2_EN                   0x0004
#define MASK_ANA_LDO_VDDCAMA1_EXT_XTL1_EN                   0x0002
#define MASK_ANA_LDO_VDDCAMA1_EXT_XTL0_EN                   0x0001
#define MASK_ANA_LDO_VDDCAMD0_EXT_XTL6_EN                   0x4000
#define MASK_ANA_LDO_VDDCAMD0_EXT_XTL5_EN                   0x2000
#define MASK_ANA_LDO_VDDCAMD0_EXT_XTL4_EN                   0x1000
#define MASK_ANA_LDO_VDDCAMD0_EXT_XTL3_EN                   0x0800
#define MASK_ANA_LDO_VDDCAMD0_EXT_XTL2_EN                   0x0400
#define MASK_ANA_LDO_VDDCAMD0_EXT_XTL1_EN                   0x0200
#define MASK_ANA_LDO_VDDCAMD0_EXT_XTL0_EN                   0x0100
#define MASK_ANA_LDO_VDDCAMD1_EXT_XTL6_EN                   0x0040
#define MASK_ANA_LDO_VDDCAMD1_EXT_XTL5_EN                   0x0020
#define MASK_ANA_LDO_VDDCAMD1_EXT_XTL4_EN                   0x0010
#define MASK_ANA_LDO_VDDCAMD1_EXT_XTL3_EN                   0x0008
#define MASK_ANA_LDO_VDDCAMD1_EXT_XTL2_EN                   0x0004
#define MASK_ANA_LDO_VDDCAMD1_EXT_XTL1_EN                   0x0002
#define MASK_ANA_LDO_VDDCAMD1_EXT_XTL0_EN                   0x0001
#define MASK_ANA_LDO_VDDSDIO_EXT_XTL6_EN                    0x4000
#define MASK_ANA_LDO_VDDSDIO_EXT_XTL5_EN                    0x2000
#define MASK_ANA_LDO_VDDSDIO_EXT_XTL4_EN                    0x1000
#define MASK_ANA_LDO_VDDSDIO_EXT_XTL3_EN                    0x0800
#define MASK_ANA_LDO_VDDSDIO_EXT_XTL2_EN                    0x0400
#define MASK_ANA_LDO_VDDSDIO_EXT_XTL1_EN                    0x0200
#define MASK_ANA_LDO_VDDSDIO_EXT_XTL0_EN                    0x0100
#define MASK_ANA_LDO_VDDSDCORE_EXT_XTL6_EN                  0x0040
#define MASK_ANA_LDO_VDDSDCORE_EXT_XTL5_EN                  0x0020
#define MASK_ANA_LDO_VDDSDCORE_EXT_XTL4_EN                  0x0010
#define MASK_ANA_LDO_VDDSDCORE_EXT_XTL3_EN                  0x0008
#define MASK_ANA_LDO_VDDSDCORE_EXT_XTL2_EN                  0x0004
#define MASK_ANA_LDO_VDDSDCORE_EXT_XTL1_EN                  0x0002
#define MASK_ANA_LDO_VDDSDCORE_EXT_XTL0_EN                  0x0001
#define MASK_ANA_LDO_VDDEMMCCORE_EXT_XTL6_EN                0x4000
#define MASK_ANA_LDO_VDDEMMCCORE_EXT_XTL5_EN                0x2000
#define MASK_ANA_LDO_VDDEMMCCORE_EXT_XTL4_EN                0x1000
#define MASK_ANA_LDO_VDDEMMCCORE_EXT_XTL3_EN                0x0800
#define MASK_ANA_LDO_VDDEMMCCORE_EXT_XTL2_EN                0x0400
#define MASK_ANA_LDO_VDDEMMCCORE_EXT_XTL1_EN                0x0200
#define MASK_ANA_LDO_VDDEMMCCORE_EXT_XTL0_EN                0x0100
#define MASK_ANA_LDO_VDDUSB33_EXT_XTL6_EN                   0x0040
#define MASK_ANA_LDO_VDDUSB33_EXT_XTL5_EN                   0x0020
#define MASK_ANA_LDO_VDDUSB33_EXT_XTL4_EN                   0x0010
#define MASK_ANA_LDO_VDDUSB33_EXT_XTL3_EN                   0x0008
#define MASK_ANA_LDO_VDDUSB33_EXT_XTL2_EN                   0x0004
#define MASK_ANA_LDO_VDDUSB33_EXT_XTL1_EN                   0x0002
#define MASK_ANA_LDO_VDDUSB33_EXT_XTL0_EN                   0x0001
#define MASK_ANA_LDO_VDDKPLED_EXT_XTL6_EN                   0x4000
#define MASK_ANA_LDO_VDDKPLED_EXT_XTL5_EN                   0x2000
#define MASK_ANA_LDO_VDDKPLED_EXT_XTL4_EN                   0x1000
#define MASK_ANA_LDO_VDDKPLED_EXT_XTL3_EN                   0x0800
#define MASK_ANA_LDO_VDDKPLED_EXT_XTL2_EN                   0x0400
#define MASK_ANA_LDO_VDDKPLED_EXT_XTL1_EN                   0x0200
#define MASK_ANA_LDO_VDDKPLED_EXT_XTL0_EN                   0x0100
#define MASK_ANA_LDO_VDDVIB_EXT_XTL6_EN                     0x0040
#define MASK_ANA_LDO_VDDVIB_EXT_XTL5_EN                     0x0020
#define MASK_ANA_LDO_VDDVIB_EXT_XTL4_EN                     0x0010
#define MASK_ANA_LDO_VDDVIB_EXT_XTL3_EN                     0x0008
#define MASK_ANA_LDO_VDDVIB_EXT_XTL2_EN                     0x0004
#define MASK_ANA_LDO_VDDVIB_EXT_XTL1_EN                     0x0002
#define MASK_ANA_LDO_VDDVIB_EXT_XTL0_EN                     0x0001
#define MASK_ANA_LDO_VDDWCN_EXT_XTL6_EN                     0x4000
#define MASK_ANA_LDO_VDDWCN_EXT_XTL5_EN                     0x2000
#define MASK_ANA_LDO_VDDWCN_EXT_XTL4_EN                     0x1000
#define MASK_ANA_LDO_VDDWCN_EXT_XTL3_EN                     0x0800
#define MASK_ANA_LDO_VDDWCN_EXT_XTL2_EN                     0x0400
#define MASK_ANA_LDO_VDDWCN_EXT_XTL1_EN                     0x0200
#define MASK_ANA_LDO_VDDWCN_EXT_XTL0_EN                     0x0100
#define MASK_ANA_LDO_AVDD18_EXT_XTL6_EN                     0x0040
#define MASK_ANA_LDO_AVDD18_EXT_XTL5_EN                     0x0020
#define MASK_ANA_LDO_AVDD18_EXT_XTL4_EN                     0x0010
#define MASK_ANA_LDO_AVDD18_EXT_XTL3_EN                     0x0008
#define MASK_ANA_LDO_AVDD18_EXT_XTL2_EN                     0x0004
#define MASK_ANA_LDO_AVDD18_EXT_XTL1_EN                     0x0002
#define MASK_ANA_LDO_AVDD18_EXT_XTL0_EN                     0x0001
#define MASK_ANA_LDO_VDDLDO0_EXT_XTL6_EN                    0x4000
#define MASK_ANA_LDO_VDDLDO0_EXT_XTL5_EN                    0x2000
#define MASK_ANA_LDO_VDDLDO0_EXT_XTL4_EN                    0x1000
#define MASK_ANA_LDO_VDDLDO0_EXT_XTL3_EN                    0x0800
#define MASK_ANA_LDO_VDDLDO0_EXT_XTL2_EN                    0x0400
#define MASK_ANA_LDO_VDDLDO0_EXT_XTL1_EN                    0x0200
#define MASK_ANA_LDO_VDDLDO0_EXT_XTL0_EN                    0x0100
#define MASK_ANA_LDO_VDDWIFIPA_EXT_XTL6_EN                  0x0040
#define MASK_ANA_LDO_VDDWIFIPA_EXT_XTL5_EN                  0x0020
#define MASK_ANA_LDO_VDDWIFIPA_EXT_XTL4_EN                  0x0010
#define MASK_ANA_LDO_VDDWIFIPA_EXT_XTL3_EN                  0x0008
#define MASK_ANA_LDO_VDDWIFIPA_EXT_XTL2_EN                  0x0004
#define MASK_ANA_LDO_VDDWIFIPA_EXT_XTL1_EN                  0x0002
#define MASK_ANA_LDO_VDDWIFIPA_EXT_XTL0_EN                  0x0001
#define MASK_ANA_LDO_VDDLDO2_EXT_XTL6_EN                    0x4000
#define MASK_ANA_LDO_VDDLDO2_EXT_XTL5_EN                    0x2000
#define MASK_ANA_LDO_VDDLDO2_EXT_XTL4_EN                    0x1000
#define MASK_ANA_LDO_VDDLDO2_EXT_XTL3_EN                    0x0800
#define MASK_ANA_LDO_VDDLDO2_EXT_XTL2_EN                    0x0400
#define MASK_ANA_LDO_VDDLDO2_EXT_XTL1_EN                    0x0200
#define MASK_ANA_LDO_VDDLDO2_EXT_XTL0_EN                    0x0100
#define MASK_ANA_LDO_VDDLDO1_EXT_XTL6_EN                    0x0040
#define MASK_ANA_LDO_VDDLDO1_EXT_XTL5_EN                    0x0020
#define MASK_ANA_LDO_VDDLDO1_EXT_XTL4_EN                    0x0010
#define MASK_ANA_LDO_VDDLDO1_EXT_XTL3_EN                    0x0008
#define MASK_ANA_LDO_VDDLDO1_EXT_XTL2_EN                    0x0004
#define MASK_ANA_LDO_VDDLDO1_EXT_XTL1_EN                    0x0002
#define MASK_ANA_LDO_VDDLDO1_EXT_XTL0_EN                    0x0001
#define MASK_ANA_LDO_VDD18_DCXO_EXT_XTL6_EN                 0x0040
#define MASK_ANA_LDO_VDD18_DCXO_EXT_XTL5_EN                 0x0020
#define MASK_ANA_LDO_VDD18_DCXO_EXT_XTL4_EN                 0x0010
#define MASK_ANA_LDO_VDD18_DCXO_EXT_XTL3_EN                 0x0008
#define MASK_ANA_LDO_VDD18_DCXO_EXT_XTL2_EN                 0x0004
#define MASK_ANA_LDO_VDD18_DCXO_EXT_XTL1_EN                 0x0002
#define MASK_ANA_LDO_VDD18_DCXO_EXT_XTL0_EN                 0x0001
#define MASK_ANA_PWR_ON_DLY_SEL                             0x0007
#define MASK_ANA_UVLO_BATON_EN                              0x0001
#define MASK_ANA_LDO_EMM_AUTO_PD_SEL                        0x0001
#define MASK_ANA_SRAM0_STEP_CLK_SEL                         0x0008
#define MASK_ANA_PUB_STEP_CLK_SEL                           0x0004
#define MASK_ANA_CORE_STEP_CLK_SEL                          0x0002
#define MASK_ANA_GPU_STEP_CLK_SEL                           0x0001
#define MASK_ANA_DCXO_26M_REF_OUT3_EXT_XTL1_EN              0x0800
#define MASK_ANA_DCXO_26M_REF_OUT2_EXT_XTL1_EN              0x0400
#define MASK_ANA_DCXO_26M_REF_OUT1_EXT_XTL1_EN              0x0200
#define MASK_ANA_DCXO_26M_REF_OUT0_EXT_XTL1_EN              0x0100
#define MASK_ANA_DCXO_26M_REF_OUT3_EXT_XTL0_EN              0x0008
#define MASK_ANA_DCXO_26M_REF_OUT2_EXT_XTL0_EN              0x0004
#define MASK_ANA_DCXO_26M_REF_OUT1_EXT_XTL0_EN              0x0002
#define MASK_ANA_DCXO_26M_REF_OUT0_EXT_XTL0_EN              0x0001
#define MASK_ANA_DCXO_26M_REF_OUT3_EXT_XTL3_EN              0x0800
#define MASK_ANA_DCXO_26M_REF_OUT2_EXT_XTL3_EN              0x0400
#define MASK_ANA_DCXO_26M_REF_OUT1_EXT_XTL3_EN              0x0200
#define MASK_ANA_DCXO_26M_REF_OUT0_EXT_XTL3_EN              0x0100
#define MASK_ANA_DCXO_26M_REF_OUT3_EXT_XTL2_EN              0x0008
#define MASK_ANA_DCXO_26M_REF_OUT2_EXT_XTL2_EN              0x0004
#define MASK_ANA_DCXO_26M_REF_OUT1_EXT_XTL2_EN              0x0002
#define MASK_ANA_DCXO_26M_REF_OUT0_EXT_XTL2_EN              0x0001
#define MASK_ANA_DCXO_26M_REF_OUT3_EXT_XTL5_EN              0x0800
#define MASK_ANA_DCXO_26M_REF_OUT2_EXT_XTL5_EN              0x0400
#define MASK_ANA_DCXO_26M_REF_OUT1_EXT_XTL5_EN              0x0200
#define MASK_ANA_DCXO_26M_REF_OUT0_EXT_XTL5_EN              0x0100
#define MASK_ANA_DCXO_26M_REF_OUT3_EXT_XTL4_EN              0x0008
#define MASK_ANA_DCXO_26M_REF_OUT2_EXT_XTL4_EN              0x0004
#define MASK_ANA_DCXO_26M_REF_OUT1_EXT_XTL4_EN              0x0002
#define MASK_ANA_DCXO_26M_REF_OUT0_EXT_XTL4_EN              0x0001
#define MASK_ANA_DCXO_26M_REF_OUT3_EXT_XTL6_EN              0x0008
#define MASK_ANA_DCXO_26M_REF_OUT2_EXT_XTL6_EN              0x0004
#define MASK_ANA_DCXO_26M_REF_OUT1_EXT_XTL6_EN              0x0002
#define MASK_ANA_DCXO_26M_REF_OUT0_EXT_XTL6_EN              0x0001
#define MASK_ANA_TSX_XO_EXT_XTL6_EN                         0x0040
#define MASK_ANA_TSX_XO_EXT_XTL5_EN                         0x0020
#define MASK_ANA_TSX_XO_EXT_XTL4_EN                         0x0010
#define MASK_ANA_TSX_XO_EXT_XTL3_EN                         0x0008
#define MASK_ANA_TSX_XO_EXT_XTL2_EN                         0x0004
#define MASK_ANA_TSX_XO_EXT_XTL1_EN                         0x0002
#define MASK_ANA_TSX_XO_EXT_XTL0_EN                         0x0001
#define MASK_ANA_DCDC_AI_EXT_XTL6_EN                        0x4000
#define MASK_ANA_DCDC_AI_EXT_XTL5_EN                        0x2000
#define MASK_ANA_DCDC_AI_EXT_XTL4_EN                        0x1000
#define MASK_ANA_DCDC_AI_EXT_XTL3_EN                        0x0800
#define MASK_ANA_DCDC_AI_EXT_XTL2_EN                        0x0400
#define MASK_ANA_DCDC_AI_EXT_XTL1_EN                        0x0200
#define MASK_ANA_DCDC_AI_EXT_XTL0_EN                        0x0100
#define MASK_ANA_DCDC_MODEM_EXT_XTL6_EN                     0x0040
#define MASK_ANA_DCDC_MODEM_EXT_XTL5_EN                     0x0020
#define MASK_ANA_DCDC_MODEM_EXT_XTL4_EN                     0x0010
#define MASK_ANA_DCDC_MODEM_EXT_XTL3_EN                     0x0008
#define MASK_ANA_DCDC_MODEM_EXT_XTL2_EN                     0x0004
#define MASK_ANA_DCDC_MODEM_EXT_XTL1_EN                     0x0002
#define MASK_ANA_DCDC_MODEM_EXT_XTL0_EN                     0x0001
#define MASK_ANA_DCDC_MM_EXT_XTL6_EN                        0x4000
#define MASK_ANA_DCDC_MM_EXT_XTL5_EN                        0x2000
#define MASK_ANA_DCDC_MM_EXT_XTL4_EN                        0x1000
#define MASK_ANA_DCDC_MM_EXT_XTL3_EN                        0x0800
#define MASK_ANA_DCDC_MM_EXT_XTL2_EN                        0x0400
#define MASK_ANA_DCDC_MM_EXT_XTL1_EN                        0x0200
#define MASK_ANA_DCDC_MM_EXT_XTL0_EN                        0x0100
#define MASK_ANA_DCDC_SRAM2_EXT_XTL6_EN                     0x0040
#define MASK_ANA_DCDC_SRAM2_EXT_XTL5_EN                     0x0020
#define MASK_ANA_DCDC_SRAM2_EXT_XTL4_EN                     0x0010
#define MASK_ANA_DCDC_SRAM2_EXT_XTL3_EN                     0x0008
#define MASK_ANA_DCDC_SRAM2_EXT_XTL2_EN                     0x0004
#define MASK_ANA_DCDC_SRAM2_EXT_XTL1_EN                     0x0002
#define MASK_ANA_DCDC_SRAM2_EXT_XTL0_EN                     0x0001
#define MASK_ANA_DCDC_BUCKBOOST_EXT_XTL6_EN                 0x0040
#define MASK_ANA_DCDC_BUCKBOOST_EXT_XTL5_EN                 0x0020
#define MASK_ANA_DCDC_BUCKBOOST_EXT_XTL4_EN                 0x0010
#define MASK_ANA_DCDC_BUCKBOOST_EXT_XTL3_EN                 0x0008
#define MASK_ANA_DCDC_BUCKBOOST_EXT_XTL2_EN                 0x0004
#define MASK_ANA_DCDC_BUCKBOOST_EXT_XTL1_EN                 0x0002
#define MASK_ANA_DCDC_BUCKBOOST_EXT_XTL0_EN                 0x0001
#define MASK_ANA_WAKEUP_EXIT_LOCK_EN                        0x0002
#define MASK_ANA_XTL_WAKEUP_MODE                            0x0001
#define MASK_ANA_DEBUG_SEND                                 0x0800
#define MASK_ANA_DEBUG_DATA                                 0x07FC
#define MASK_ANA_DEBUG_MODE                                 0x0002
#define MASK_ANA_ODD_PARITY                                 0x0001
#define MASK_ANA_DCDC_GPU_ON_STEP_EN                        0x0040
#define MASK_ANA_DCDC_CPU1_ON_STEP_EN                       0x0020
#define MASK_ANA_DCDC_CPU2_ON_STEP_EN                       0x0010
#define MASK_ANA_DCDC_CPU1_ANASOFT_EN                       0x0008
#define MASK_ANA_DCDC_CPU2_ANASOFT_EN                       0x0004
#define MASK_ANA_DCDC_GPU_ANASOFT_EN                        0x0002
#define MASK_ANA_DCDC_SRAM0_ANASOFT_EN                      0x0001
#define MASK_ANA_SLP_LDO_VDDUSB33_PD                        0x8000
#define MASK_ANA_SLP_XTLBUF_PD                              0x4000
#define MASK_ANA_SLP_DCDCSRAM0_PD                           0x0020
#define MASK_ANA_SLP_DCDCPUB_PD                             0x0010
#define MASK_ANA_SLP_DCDCMEMQ_PD                            0x0008
#define MASK_ANA_SLP_DCDCGEN1_PD                            0x0004
#define MASK_ANA_SLP_DCDCWPA_PD                             0x0002
#define MASK_ANA_SLP_DCDCGPU_PD                             0x0001
#define MASK_ANA_SLP_LDO_AVDD12_PD                          0x8000
#define MASK_ANA_SLP_LDO_AVDD18_PD                          0x4000
#define MASK_ANA_SLP_LDO_VDD28_PD                           0x2000
#define MASK_ANA_SLP_LDO_VDDLDO4_PD                         0x1000
#define MASK_ANA_SLP_LDO_VDDLDO3_PD                         0x0800
#define MASK_ANA_SLP_LDO_VDDLDO2_PD                         0x0400
#define MASK_ANA_SLP_LDO_VDDLDO1_PD                         0x0200
#define MASK_ANA_SLP_LDO_VDDLDO0_PD                         0x0100
#define MASK_ANA_SLP_LDO_VDDCAMMOT1_PD                      0x0080
#define MASK_ANA_SLP_LDO_VDDCAMMOT0_PD                      0x0040
#define MASK_ANA_SLP_LDO_VDDCAMD2_PD                        0x0020
#define MASK_ANA_SLP_LDO_VDDCAMD1_PD                        0x0010
#define MASK_ANA_SLP_LDO_VDDCAMD0_PD                        0x0008
#define MASK_ANA_SLP_LDO_VDDCAMA2_PD                        0x0004
#define MASK_ANA_SLP_LDO_VDDCAMA1_PD                        0x0002
#define MASK_ANA_SLP_LDO_VDDCAMA0_PD                        0x0001
#define MASK_ANA_SLP_LDO_VDDWCN_PD                          0x8000
#define MASK_ANA_SLP_LDO_VDDUFS1V2_PD                       0x4000
#define MASK_ANA_SLP_LDO_VDDWIFIPA_PD                       0x2000
#define MASK_ANA_SLP_LDO_VDDEMMCCORE_PD                     0x1000
#define MASK_ANA_SLP_LDO_VDDCAMIO_PD                        0x0800
#define MASK_ANA_SLP_LDO_VDDVIB_PD                          0x0400
#define MASK_ANA_SLP_LDO_VDDKPLED_PD                        0x0200
#define MASK_ANA_SLP_LDO_VDD18_DCXO_PD                      0x0100
#define MASK_ANA_SLP_LDO_VDDRF0V9_PD                        0x0080
#define MASK_ANA_SLP_LDO_VDDRF1V1_PD                        0x0040
#define MASK_ANA_SLP_LDO_VDDRF1V8_PD                        0x0020
#define MASK_ANA_SLP_LDO_VDDSDCORE_PD                       0x0010
#define MASK_ANA_SLP_LDO_VDDSDIO_PD                         0x0008
#define MASK_ANA_SLP_LDO_VDDSIM2_PD                         0x0004
#define MASK_ANA_SLP_LDO_VDDSIM1_PD                         0x0002
#define MASK_ANA_SLP_LDO_VDDSIM0_PD                         0x0001
#define MASK_ANA_LDO_USB33_WAKEUP_N                         0x8000
#define MASK_ANA_TSX_XO_WAKEUP_N                            0x0800
#define MASK_ANA_DCDC_BUCKBOOST_WAKEUP_N                    0x0400
#define MASK_ANA_DCDC_AI_WAKEUP_N                           0x0200
#define MASK_ANA_DCDC_SRAM2_WAKEUP_N                        0x0100
#define MASK_ANA_DCDC_MM_WAKEUP_N                           0x0080
#define MASK_ANA_DCDC_MODEM_WAKEUP_N                        0x0040
#define MASK_ANA_DCDC_SRAM0_WAKEUP_N                        0x0020
#define MASK_ANA_DCDC_PUB_WAKEUP_N                          0x0010
#define MASK_ANA_DCDC_MEMQ_WAKEUP_N                         0x0008
#define MASK_ANA_DCDC_GEN1_WAKEUP_N                         0x0004
#define MASK_ANA_DCDC_WPA_WAKEUP_N                          0x0002
#define MASK_ANA_DCDC_GPU_WAKEUP_N                          0x0001
#define MASK_ANA_LDO_AVDD12_WAKEUP_N                        0x8000
#define MASK_ANA_LDO_AVDD18_WAKEUP_N                        0x4000
#define MASK_ANA_LDO_VDD28_WAKEUP_N                         0x2000
#define MASK_ANA_LDO4_WAKEUP_N                              0x1000
#define MASK_ANA_LDO3_WAKEUP_N                              0x0800
#define MASK_ANA_LDO2_WAKEUP_N                              0x0400
#define MASK_ANA_LDO1_WAKEUP_N                              0x0200
#define MASK_ANA_LDO0_WAKEUP_N                              0x0100
#define MASK_ANA_LDO_CAMMOT1_WAKEUP_N                       0x0080
#define MASK_ANA_LDO_CAMMOT0_WAKEUP_N                       0x0040
#define MASK_ANA_LDO_CAMD2_WAKEUP_N                         0x0020
#define MASK_ANA_LDO_CAMD1_WAKEUP_N                         0x0010
#define MASK_ANA_LDO_CAMD0_WAKEUP_N                         0x0008
#define MASK_ANA_LDO_CAMA2_WAKEUP_N                         0x0004
#define MASK_ANA_LDO_CAMA1_WAKEUP_N                         0x0002
#define MASK_ANA_LDO_CAMA0_WAKEUP_N                         0x0001
#define MASK_ANA_LDO_WCN_WAKEUP_N                           0x8000
#define MASK_ANA_LDO_VDDUFS1V2_WAKEUP_N                     0x4000
#define MASK_ANA_LDO_WIFIPA_WAKEUP_N                        0x2000
#define MASK_ANA_LDO_EMMCCORE_WAKEUP_N                      0x1000
#define MASK_ANA_LDO_CAMIO_WAKEUP_N                         0x0800
#define MASK_ANA_LDO_VIB_WAKEUP_N                           0x0400
#define MASK_ANA_LDO_KPLED_WAKEUP_N                         0x0200
#define MASK_ANA_LDO_DCXO_WAKEUP_N                          0x0100
#define MASK_ANA_LDO_RF0V9_WAKEUP_N                         0x0080
#define MASK_ANA_LDO_RF1V1_WAKEUP_N                         0x0040
#define MASK_ANA_LDO_RF1V8_WAKEUP_N                         0x0020
#define MASK_ANA_LDO_SDCORE_WAKEUP_N                        0x0010
#define MASK_ANA_LDO_SDIO_WAKEUP_N                          0x0008
#define MASK_ANA_LDO_SIM2_WAKEUP_N                          0x0004
#define MASK_ANA_LDO_SIM1_WAKEUP_N                          0x0002
#define MASK_ANA_LDO_SIM0_WAKEUP_N                          0x0001
#define MASK_ANA_LDO_VDDUSB33_LP_EN                         0x8000
#define MASK_ANA_DCDC_MEM_LP_EN                             0x0100
#define MASK_ANA_DCDC_GEN0_LP_EN                            0x0080
#define MASK_ANA_DCDC_CORE_LP_EN                            0x0040
#define MASK_ANA_DCDC_SRAM0_LP_EN                           0x0020
#define MASK_ANA_DCDC_PUB_LP_EN                             0x0010
#define MASK_ANA_DCDC_MEMQ_LP_EN                            0x0008
#define MASK_ANA_DCDC_GEN1_LP_EN                            0x0004
#define MASK_ANA_DCDC_WPA_LP_EN                             0x0002
#define MASK_ANA_DCDC_GPU_LP_EN                             0x0001
#define MASK_ANA_LDO_AVDD12_LP_EN                           0x8000
#define MASK_ANA_LDO_AVDD18_LP_EN                           0x4000
#define MASK_ANA_LDO_VDD28_LP_EN                            0x2000
#define MASK_ANA_LDO_VDDLDO4_LP_EN                          0x1000
#define MASK_ANA_LDO_VDDLDO3_LP_EN                          0x0800
#define MASK_ANA_LDO_VDDLDO2_LP_EN                          0x0400
#define MASK_ANA_LDO_VDDLDO1_LP_EN                          0x0200
#define MASK_ANA_LDO_VDDLDO0_LP_EN                          0x0100
#define MASK_ANA_LDO_VDDCAMMOT1_LP_EN                       0x0080
#define MASK_ANA_LDO_VDDCAMMOT0_LP_EN                       0x0040
#define MASK_ANA_LDO_VDDCAMD2_LP_EN                         0x0020
#define MASK_ANA_LDO_VDDCAMD1_LP_EN                         0x0010
#define MASK_ANA_LDO_VDDCAMD0_LP_EN                         0x0008
#define MASK_ANA_LDO_VDDCAMA2_LP_EN                         0x0004
#define MASK_ANA_LDO_VDDCAMA1_LP_EN                         0x0002
#define MASK_ANA_LDO_VDDCAMA0_LP_EN                         0x0001
#define MASK_ANA_LDO_VDDWCN_LP_EN                           0x8000
#define MASK_ANA_LDO_VDDUFS1V2_LP_EN                        0x4000
#define MASK_ANA_LDO_VDDWIFIPA_LP_EN                        0x2000
#define MASK_ANA_LDO_VDDEMMCCORE_LP_EN                      0x1000
#define MASK_ANA_LDO_VDD18_DCXO_LP_EN                       0x0100
#define MASK_ANA_LDO_VDDRF0V9_LP_EN                         0x0080
#define MASK_ANA_LDO_VDDRF1V1_LP_EN                         0x0040
#define MASK_ANA_LDO_VDDRF1V8_LP_EN                         0x0020
#define MASK_ANA_LDO_VDDSDCORE_LP_EN                        0x0010
#define MASK_ANA_LDO_VDDSDIO_LP_EN                          0x0008
#define MASK_ANA_LDO_VDDSIM2_LP_EN                          0x0004
#define MASK_ANA_LDO_VDDSIM1_LP_EN                          0x0002
#define MASK_ANA_LDO_VDDSIM0_LP_EN                          0x0001
#define MASK_ANA_DCXO_26M_REF_OUT3_WAKEUP                   0x0008
#define MASK_ANA_DCXO_26M_REF_OUT2_WAKEUP                   0x0004
#define MASK_ANA_DCXO_26M_REF_OUT1_WAKEUP                   0x0002
#define MASK_ANA_DCXO_26M_REF_OUT0_WAKEUP                   0x0001
#define MASK_ANA_RESERVED_CORE                              0xFFFF
#define MASK_ANA_RESERVED_RTC                               0x0FFF
#define MASK_ANA_BG_CHOP_EN                                 0x0001
#define MASK_ANA_DCDC_PUB_PFMAD_SW_SEL                      0x8000
#define MASK_ANA_DCDC_MEMQ_PFMAD_SW_SEL                     0x4000
#define MASK_ANA_DCDC_GPU_PFMAD_SW_SEL                      0x2000
#define MASK_ANA_DCDC_CPU2_PFMAD_SW_SEL                     0x1000
#define MASK_ANA_DCDC_CORE_PFMAD_SW_SEL                     0x0800
#define MASK_ANA_DCDC_GEN1_PFMAD_SW_SEL                     0x0400
#define MASK_ANA_DCDC_GEN0_PFMAD_SW_SEL                     0x0200
#define MASK_ANA_DCDC_MEM_PFMAD_SW_SEL                      0x0100
#define MASK_ANA_DCDC_WPA_PFMAD_SW_SEL                      0x0080
#define MASK_ANA_DCDC_6MFRECAL_SW_SEL                       0x0040
#define MASK_ANA_DCDC_WPA_VREF_CAL_SW_SEL                   0x0020
#define MASK_ANA_DCDC_MEMQ_SW_SEL                           0x0010
#define MASK_ANA_DCDC_GEN0_SW_SEL                           0x0008
#define MASK_ANA_DCDC_GEN1_SW_SEL                           0x0004
#define MASK_ANA_DCDC_CORE_NOR_SW_SEL                       0x0001
#define MASK_ANA_DCDC_CPU1_SW_SEL                           0x0040
#define MASK_ANA_DCDC_SRAM0_PFMAD_SW_SEL                    0x0020
#define MASK_ANA_DCDC_SRAM0_SW_SEL                          0x0010
#define MASK_ANA_DCDC_PUB_SW_SEL                            0x0008
#define MASK_ANA_DCDC_MEM_SW_SEL                            0x0004
#define MASK_ANA_DCDC_GPU_SW_SEL                            0x0002
#define MASK_ANA_DCDC_CPU2_SW_SEL                           0x0001
#define MASK_ANA_LDO_VDDSDCORE_CL_ADJ_SW_SEL                0x8000
#define MASK_ANA_LDO_VDDLDO1_SW_SEL                         0x4000
#define MASK_ANA_LDO_VDDLDO0_SW_SEL                         0x2000
#define MASK_ANA_LDO_VDDUSB33_SW_SEL                        0x1000
#define MASK_ANA_LDO_VDD18_DCXO_SW_SEL                      0x0800
#define MASK_ANA_LDO_VDDWIFIPA_SW_SEL                       0x0400
#define MASK_ANA_LDO_VDD28_SW_SEL                           0x0200
#define MASK_ANA_LDO_VDDSDIO_SW_SEL                         0x0100
#define MASK_ANA_LDO_VDDSDCORE_SW_SEL                       0x0080
#define MASK_ANA_LDO_VDDEMMCCORE_SW_SEL                     0x0040
#define MASK_ANA_LDO_VDDSIM2_SW_SEL                         0x0020
#define MASK_ANA_LDO_VDDSIM1_SW_SEL                         0x0010
#define MASK_ANA_LDO_VDDSIM0_SW_SEL                         0x0008
#define MASK_ANA_LDO_VDD18_DCXO_LP_SW_SEL                   0x0004
#define MASK_ANA_LDO_VDDLDO4_SW_SEL                         0x8000
#define MASK_ANA_LDO_VDDUFS1V2_SW_SEL                       0x4000
#define MASK_ANA_LDO_VDDRF0V9_SW_SEL                        0x2000
#define MASK_ANA_LDO_VDDLDO3_SW_SEL                         0x1000
#define MASK_ANA_LDO_VDDLDO2_SW_SEL                         0x0800
#define MASK_ANA_LDO_RTC_CAL_SW_SEL                         0x0400
#define MASK_ANA_LDO_VDDKPLED_SW_SEL                        0x0200
#define MASK_ANA_LDO_VDDVIBR_SW_SEL                         0x0100
#define MASK_ANA_LDO_AVDD12_SW_SEL                          0x0080
#define MASK_ANA_LDO_VDDRF1V1_SW_SEL                        0x0040
#define MASK_ANA_LDO_VDDCAMD2_SW_SEL                        0x0020
#define MASK_ANA_LDO_VDDCAMD1_SW_SEL                        0x0010
#define MASK_ANA_LDO_VDDCAMD0_SW_SEL                        0x0008
#define MASK_ANA_LDO_VDDWCN_SW_SEL                          0x0004
#define MASK_ANA_LDO_VDDRF1V8_SW_SEL                        0x0002
#define MASK_ANA_LDO_AVDD18_SW_SEL                          0x0001
#define MASK_ANA_RTC_MODE                                   0x0040
#define MASK_ANA_RC_MODE_WR_ACK_FLAG                        0x0020
#define MASK_ANA_RC_MODE_WR_ACK_FLAG_CLR                    0x0010
#define MASK_ANA_LDO_VDD18_DCXO_LP_EN_RTCSET                0x0008
#define MASK_ANA_LDO_VDD18_DCXO_LP_EN_RTCCLR                0x0004
#define MASK_ANA_RC_32K_SEL                                 0x0002
#define MASK_ANA_RC_32K_EN                                  0x0001
#define MASK_ANA_RC_MODE                                    0xFFFF
#define MASK_ANA_RC1M_CAL_SW_SEL                            0x0008
#define MASK_ANA_LDO_VDDLDO2_CL_ADJ_SW_SEL                  0x0004
#define MASK_ANA_LDO_VDDWIFIPA_CL_ADJ_SW_SEL                0x0002
#define MASK_ANA_LDO_VDDEMMCCORE_CL_ADJ_SW_SEL              0x0001
#define MASK_ANA_SLP_XTLBUF_PD_EN                           0x0200
#define MASK_ANA_XTL_EN                                     0x0100
#define MASK_ANA_XTL_WAIT                                   0x00FF
#define MASK_ANA_CLK_26M_SOURCE_SEL                         0x0001
#define MASK_ANA_SLP_RGB_PD_EN                              0x0004
#define MASK_ANA_BATDET_CUR_EN                              0x2000
#define MASK_ANA_BATDET_CUR_I                               0x0E00
#define MASK_ANA_IB_TRIM                                    0x01FC
#define MASK_ANA_IB_TRIM_EM_SEL                             0x0002
#define MASK_ANA_IB_REX_EN                                  0x0001
#define MASK_ANA_KPLED_V                                    0xF000
#define MASK_ANA_KPLED_PD                                   0x0800
#define MASK_ANA_KPLED_PULLDOWN_EN                          0x0400
#define MASK_ANA_LDO_VDDKPLED_PD                            0x8000
#define MASK_ANA_LDO_VDDKPLED_V                             0x7F80
#define MASK_ANA_LDO_VDDKPLED_REFTRIM                       0x007C
#define MASK_ANA_SLP_LDO_VDDKPLED_PD_EN                     0x0002
#define MASK_ANA_LDO_VDDKPLED_SHPT_PD                       0x0001
#define MASK_ANA_SLP_LDO_VDDVIB_PD_EN                       0x4000
#define MASK_ANA_LDO_VDDVIB_PD                              0x2000
#define MASK_ANA_LDO_VDDVIB_REFTRIM                         0x1F00
#define MASK_ANA_LDO_VDDVIB_V                               0x00FF
#define MASK_ANA_CLK_AUD_IF_TX_INV_EN                       0x0008
#define MASK_ANA_CLK_AUD_IF_RX_INV_EN                       0x0004
#define MASK_ANA_CLK_AUD_IF_6P5M_TX_INV_EN                  0x0002
#define MASK_ANA_CLK_AUD_IF_6P5M_RX_INV_EN                  0x0001
#define MASK_ANA_CHGR_PD                                    0x0001
#define MASK_ANA_CHGR_INT_EN                                0x2000
#define MASK_ANA_NON_DCP_INT                                0x1000
#define MASK_ANA_CHG_DET_DONE                               0x0800
#define MASK_ANA_DP_LOW                                     0x0400
#define MASK_ANA_DCP_DET                                    0x0200
#define MASK_ANA_CHG_DET                                    0x0100
#define MASK_ANA_SDP_INT                                    0x0080
#define MASK_ANA_DCP_INT                                    0x0040
#define MASK_ANA_CDP_INT                                    0x0020
#define MASK_ANA_CHGR_INT                                   0x0004
#define MASK_ANA_DCP_SWITCH_EN                              0x0002
#define MASK_ANA_DP_DM_FC_ENB                               0x4000
#define MASK_ANA_FGUA_SOFT_RST                              0x2000
#define MASK_ANA_LDO_FGU_PD                                 0x1000
#define MASK_ANA_CHG_INT_DELAY                              0x0F00
#define MASK_ANA_REDET_DELAY                                0x00F0
#define MASK_ANA_DP_DM_AUX_EN                               0x0002
#define MASK_ANA_DP_DM_BC_ENB                               0x0001
#define MASK_ANA_VBAT_CRASH_V                               0x0C00
#define MASK_ANA_OVLO_EN                                    0x0200
#define MASK_ANA_OVLO_V                                     0x000C
#define MASK_ANA_OVLO_T                                     0x0003
#define MASK_ANA_XOSC32K_CTL                                0x1000
#define MASK_ANA_BATON_T                                    0x0C00
#define MASK_ANA_DPDM_DET_VTHSEL                            0x0200
#define MASK_ANA_BATDET_OK                                  0x0100
#define MASK_ANA_VBAT_OK                                    0x0010
#define MASK_ANA_ALL_GPI_DEB                                0x0008
#define MASK_ANA_GPI_DEBUG_EN                               0x0004
#define MASK_ANA_ALL_INT_DEB                                0x0002
#define MASK_ANA_INT_DEBUG_EN                               0x0001
#define MASK_ANA_POR_RST_MONITOR                            0xFFFF
#define MASK_ANA_WDG_RST_MONITOR                            0xFFFF
#define MASK_ANA_POR_SW_FORCE_ON                            0x8000
#define MASK_ANA_REG_SOFT_RST_FLG_CLR                       0x4000
#define MASK_ANA_POR_SRC_FLAG                               0x3FFF
#define MASK_ANA_POR_CHIP_PD_FLAG                           0x2000
#define MASK_ANA_POR_CHIP_PD_FLAG_CLR                       0x1000
#define MASK_ANA_UVLO_CHIP_PD_FLAG                          0x0800
#define MASK_ANA_UVLO_CHIP_PD_FLAG_CLR                      0x0400
#define MASK_ANA_HARD_7S_CHIP_PD_FLAG                       0x0200
#define MASK_ANA_HARD_7S_CHIP_PD_FLAG_CLR                   0x0100
#define MASK_ANA_SW_CHIP_PD_FLAG                            0x0080
#define MASK_ANA_SW_CHIP_PD_FLAG_CLR                        0x0040
#define MASK_ANA_HW_CHIP_PD_FLAG                            0x0020
#define MASK_ANA_HW_CHIP_PD_FLAG_CLR                        0x0010
#define MASK_ANA_OTP_CHIP_PD_FLAG                           0x0008
#define MASK_ANA_OTP_CHIP_PD_FLAG_CLR                       0x0004
#define MASK_ANA_PBINT_7S_FLAG_CLR                          0x8000
#define MASK_ANA_EXT_RSTN_FLAG_CLR                          0x4000
#define MASK_ANA_CHGR_INT_FLAG_CLR                          0x2000
#define MASK_ANA_PBINT2_FLAG_CLR                            0x1000
#define MASK_ANA_PBINT_FLAG_CLR                             0x0800
#define MASK_ANA_KEY2_7S_RST_EN                             0x0200
#define MASK_ANA_PBINT_7S_RST_SWMODE                        0x0100
#define MASK_ANA_PBINT_7S_RST_THRESHOLD                     0x00F0
#define MASK_ANA_EXT_RSTN_MODE                              0x0008
#define MASK_ANA_PBINT_7S_AUTO_ON_EN                        0x0004
#define MASK_ANA_PBINT_7S_RST_DISABLE                       0x0002
#define MASK_ANA_PBINT_7S_RST_MODE                          0x0001
#define MASK_ANA_HWRST_RTC_REG_STS                          0xFF00
#define MASK_ANA_HWRST_RTC_REG_SET                          0x00FF
#define MASK_ANA_ARCH_EN                                    0x0001
#define MASK_ANA_MCU_WR_PROT                                0x8000
#define MASK_ANA_MCU_WR_PROT_VALUE                          0x7FFF
#define MASK_ANA_PWR_WR_PROT                                0x8000
#define MASK_ANA_PWR_WR_PROT_VALUE                          0x7FFF
#define MASK_ANA_DCDC_WR_PROT                               0x8000
#define MASK_ANA_DCDC_WR_PROT_VALUE                         0x7FFF
#define MASK_ANA_POR_WR_PROT                                0x8000
#define MASK_ANA_POR_WR_PROT_VALUE                          0x7FFF
#define MASK_ANA_SMPL_MODE                                  0xFFFF
#define MASK_ANA_SMPL_PWR_ON_FLAG                           0x8000
#define MASK_ANA_SMPL_MODE_WR_ACK_FLAG                      0x4000
#define MASK_ANA_SMPL_PWR_ON_FLAG_CLR                       0x2000
#define MASK_ANA_SMPL_MODE_WR_ACK_FLAG_CLR                  0x1000
#define MASK_ANA_SMPL_PWR_ON_SET                            0x0800
#define MASK_ANA_SMPL_EN                                    0x0001
#define MASK_ANA_RTC_CLK_FLAG_SET                           0xFFFF
#define MASK_ANA_RTC_CLK_FLAG_CLR                           0xFFFF
#define MASK_ANA_RTC_CLK_FLAG_RTC                           0xFFFF
#define MASK_ANA_RTC_CLK_STOP_FLAG                          0x0080
#define MASK_ANA_RTC_CLK_STOP_THRESHOLD                     0x007F
#define MASK_ANA_VBAT_DROP_CNT                              0x0FFF
#define MASK_ANA_SW_RST_LDO_UFS1V2_PD_EN                    0x1000
#define MASK_ANA_SW_RST_LDOVDD_LDO1_PD_EN                   0x0800
#define MASK_ANA_SW_RST_DCDCSRAM0_PD_EN                     0x0200
#define MASK_ANA_EXT_RSTN_PD_EN                             0x0100
#define MASK_ANA_PB_7S_RST_PD_EN                            0x0080
#define MASK_ANA_REG_RST_PD_EN                              0x0040
#define MASK_ANA_WDG_RST_PD_EN                              0x0020
#define MASK_ANA_REG_RST_EN                                 0x0010
#define MASK_ANA_SW_RST_PD_THRESHOLD                        0x000F
#define MASK_ANA_HW_OFF_RST_EN                              0x0001
#define MASK_ANA_SW_RST_DCDCGPU_PD_EN                       0x8000
#define MASK_ANA_SW_RST_DCDCPUB_PD_EN                       0x4000
#define MASK_ANA_SW_RST_DCDCMEMQ_PD_EN                      0x2000
#define MASK_ANA_SW_RST_DCDCMEM_PD_EN                       0x1000
#define MASK_ANA_SW_RST_DCDCGEN1_PD_EN                      0x0800
#define MASK_ANA_SW_RST_DCDCGEN0_PD_EN                      0x0400
#define MASK_ANA_SW_RST_DCDCCORE_PD_EN                      0x0200
#define MASK_ANA_SW_RST_LDO_AVDD12_PD_EN                    0x0100
#define MASK_ANA_SW_RST_LDOVDD18_DCXO_PD_EN                 0x0080
#define MASK_ANA_SW_RST_LDO_VDD28_PD_EN                     0x0040
#define MASK_ANA_SW_RST_LDO_AVDD18_PD_EN                    0x0020
#define MASK_ANA_SW_RST_LDOVDD_RF1V8_PD_EN                  0x0010
#define MASK_ANA_SW_RST_LDOVDD_USB33_PD_EN                  0x0008
#define MASK_ANA_SW_RST_LDOVDD_EMMCCORE_PD_EN               0x0004
#define MASK_ANA_SW_RST_LDOVDD_SDIO_PD_EN                   0x0002
#define MASK_ANA_SW_RST_LDOVDD_SDCORE_PD_EN                 0x0001
#define MASK_ANA_EXT_OTP_EN                                 0x0008
#define MASK_ANA_OTP_OP                                     0x0006
#define MASK_ANA_OTP_EN                                     0x0001
#define MASK_ANA_TIMER_LOW                                  0xFFFF
#define MASK_ANA_TIMER_HIGH                                 0xFFFF
#define MASK_ANA_LOW_PWR_CLK32K_EN                          0x0001
#define MASK_ANA_CORE_CLK_SEL                               0x4000
#define MASK_ANA_CPU2_STEP_DELAY                            0x3000
#define MASK_ANA_CPU2_STEP_NUM                              0x0F00
#define MASK_ANA_CPU2_STEP_VOL                              0x00F8
#define MASK_ANA_CPU2_VOL_TUNE_START                        0x0004
#define MASK_ANA_CPU2_VOL_TUNE_FLAG                         0x0002
#define MASK_ANA_CPU2_VOL_TUNE_EN                           0x0001
#define MASK_ANA_GPU_STEP_DELAY                             0x3000
#define MASK_ANA_GPU_STEP_NUM                               0x0F00
#define MASK_ANA_GPU_STEP_VOL                               0x00F8
#define MASK_ANA_GPU_VOL_TUNE_START                         0x0004
#define MASK_ANA_GPU_VOL_TUNE_FLAG                          0x0002
#define MASK_ANA_GPU_VOL_TUNE_EN                            0x0001
#define MASK_ANA_PUB_STEP_DELAY                             0x3000
#define MASK_ANA_PUB_STEP_NUM                               0x0F00
#define MASK_ANA_PUB_STEP_VOL                               0x00F8
#define MASK_ANA_PUB_VOL_TUNE_START                         0x0004
#define MASK_ANA_PUB_VOL_TUNE_FLAG                          0x0002
#define MASK_ANA_PUB_VOL_TUNE_EN                            0x0001
#define MASK_ANA_DVFS_CPU1_CLK6M_SW_EN                      0x0100
#define MASK_ANA_DVFS_CPU2_CLK6M_SW_EN                      0x0080
#define MASK_ANA_DVFS_GPU_CLK6M_SW_EN                       0x0040
#define MASK_ANA_DVFS_PUB_CLK6M_SW_EN                       0x0020
#define MASK_ANA_DCDC_CPU1_DVFS_EN                          0x0010
#define MASK_ANA_DCDC_CPU2_DVFS_EN                          0x0008
#define MASK_ANA_DCDC_GPU_DVFS_EN                           0x0004
#define MASK_ANA_DCDC_PUB_DVFS_EN                           0x0001
#define MASK_ANA_BC1P2_SW_MODE                              0x0080
#define MASK_ANA_BC1P2_VDP_SRC_EN                           0x0040
#define MASK_ANA_BC1P2_IDP_SRC_EN                           0x0020
#define MASK_ANA_BC1P2_IDM_SINK_EN                          0x0010
#define MASK_ANA_BC1P2_DCP_DET_EN                           0x0008
#define MASK_ANA_BC1P2_CHG_DET_EN                           0x0004
#define MASK_ANA_BC1P2_VDM_SRC_EN                           0x0002
#define MASK_ANA_BC1P2_RDM_DWN_EN                           0x0001
#define MASK_ANA_BC1P2_REDET                                0x0001
#define MASK_ANA_DCDC_CPU1_DEADTIME                         0xC000
#define MASK_ANA_DCDC_CPU1_PDRSLOW                          0x00F0
#define MASK_ANA_DCDC_CPU1_PFMB                             0x0004
#define MASK_ANA_DCDC_CPU1_DCMB                             0x0002
#define MASK_ANA_DCDC_CPU1_CF                               0x0030
#define MASK_ANA_DCDC_CPU1_CL_CTRL                          0x0003
#define MASK_ANA_DCDC_CPU1_STBOP                            0x1FC0
#define MASK_ANA_DCDC_CPU1_ZCD                              0x0030
#define MASK_ANA_DCDC_CPU1_PFMAD                            0x000F
#define MASK_ANA_FRACTION_DIV_CPU1                          0x7800
#define MASK_ANA_INTEGER_DIV_CPU1                           0x0600
#define MASK_ANA_DCDC_CPU1_CTRL                             0x01FF
#define MASK_ANA_DCDC_CPU1_PFMAD_SW_SEL                     0x0001
#define MASK_ANA_EXT_XTL6_FOR_26M_EN                        0x0040
#define MASK_ANA_EXT_XTL5_FOR_26M_EN                        0x0020
#define MASK_ANA_EXT_XTL4_FOR_26M_EN                        0x0010
#define MASK_ANA_EXT_XTL3_FOR_26M_EN                        0x0008
#define MASK_ANA_EXT_XTL2_FOR_26M_EN                        0x0004
#define MASK_ANA_EXT_XTL1_FOR_26M_EN                        0x0002
#define MASK_ANA_EXT_XTL0_FOR_26M_EN                        0x0001
#define MASK_ANA_LDO_VDDCAMA2_REFTRIM                       0x007C
#define MASK_ANA_LDO_VDDCAMA2_SHPT_PD                       0x0002
#define MASK_ANA_LDO_VDDCAMA2_PD                            0x0001
#define MASK_ANA_LDO_VDDCAMA2_V                             0x00FF
#define MASK_ANA_LDO_VDDCAMMOT1_EXT_XTL6_EN                 0x4000
#define MASK_ANA_LDO_VDDCAMMOT1_EXT_XTL5_EN                 0x2000
#define MASK_ANA_LDO_VDDCAMMOT1_EXT_XTL4_EN                 0x1000
#define MASK_ANA_LDO_VDDCAMMOT1_EXT_XTL3_EN                 0x0800
#define MASK_ANA_LDO_VDDCAMMOT1_EXT_XTL2_EN                 0x0400
#define MASK_ANA_LDO_VDDCAMMOT1_EXT_XTL1_EN                 0x0200
#define MASK_ANA_LDO_VDDCAMMOT1_EXT_XTL0_EN                 0x0100
#define MASK_ANA_LDO_VDDCAMA2_EXT_XTL6_EN                   0x0040
#define MASK_ANA_LDO_VDDCAMA2_EXT_XTL5_EN                   0x0020
#define MASK_ANA_LDO_VDDCAMA2_EXT_XTL4_EN                   0x0010
#define MASK_ANA_LDO_VDDCAMA2_EXT_XTL3_EN                   0x0008
#define MASK_ANA_LDO_VDDCAMA2_EXT_XTL2_EN                   0x0004
#define MASK_ANA_LDO_VDDCAMA2_EXT_XTL1_EN                   0x0002
#define MASK_ANA_LDO_VDDCAMA2_EXT_XTL0_EN                   0x0001
#define MASK_ANA_LDO_VDDCAMD2_EXT_XTL6_EN                   0x4000
#define MASK_ANA_LDO_VDDCAMD2_EXT_XTL5_EN                   0x2000
#define MASK_ANA_LDO_VDDCAMD2_EXT_XTL4_EN                   0x1000
#define MASK_ANA_LDO_VDDCAMD2_EXT_XTL3_EN                   0x0800
#define MASK_ANA_LDO_VDDCAMD2_EXT_XTL2_EN                   0x0400
#define MASK_ANA_LDO_VDDCAMD2_EXT_XTL1_EN                   0x0200
#define MASK_ANA_LDO_VDDCAMD2_EXT_XTL0_EN                   0x0100
#define MASK_ANA_LDO_VDDLDO3_EXT_XTL6_EN                    0x0040
#define MASK_ANA_LDO_VDDLDO3_EXT_XTL5_EN                    0x0020
#define MASK_ANA_LDO_VDDLDO3_EXT_XTL4_EN                    0x0010
#define MASK_ANA_LDO_VDDLDO3_EXT_XTL3_EN                    0x0008
#define MASK_ANA_LDO_VDDLDO3_EXT_XTL2_EN                    0x0004
#define MASK_ANA_LDO_VDDLDO3_EXT_XTL1_EN                    0x0002
#define MASK_ANA_LDO_VDDLDO3_EXT_XTL0_EN                    0x0001
#define MASK_ANA_LDO_VDDCAMA2_SW_SEL                        0x0010
#define MASK_ANA_LDO_VDDCAMA1_SW_SEL                        0x0008
#define MASK_ANA_LDO_VDDCAMA0_SW_SEL                        0x0004
#define MASK_ANA_LDO_VDDCAMMOT1_SW_SEL                      0x0002
#define MASK_ANA_LDO_VDDCAMMOT0_SW_SEL                      0x0001
#define MASK_ANA_SLP_LDO_VDDCAMD2_PD_EN                     0x0010
#define MASK_ANA_SLP_LDO_VDDCAMA2_PD_EN                     0x0008
#define MASK_ANA_SLP_LDO_VDDCAMD2_LP_EN                     0x0020
#define MASK_ANA_SLP_LDO_VDDCAMA2_LP_EN                     0x0010
#define MASK_ANA_LDO_VDDLDO3_SHPT_PD                        0x0040
#define MASK_ANA_LDO_VDDLDO3_REFTRIM                        0x003E
#define MASK_ANA_LDO_VDDLDO3_PD                             0x0001
#define MASK_ANA_LDO_VDDLDO3_V                              0x00FF
#define MASK_ANA_LDO_VDDCAMD2_SHPT_PD                       0x0040
#define MASK_ANA_LDO_VDDCAMD2_REFTRIM                       0x003E
#define MASK_ANA_LDO_VDDCAMD2_PD                            0x0001
#define MASK_ANA_LDO_VDDCAMD2_V                             0x001F
#define MASK_ANA_LDO_VDDRF1V1_SHPT_PD                       0x0040
#define MASK_ANA_LDO_VDDRF1V1_REFTRIM                       0x003E
#define MASK_ANA_LDO_VDDRF1V1_PD                            0x0001
#define MASK_ANA_LDO_VDDRF1V1_V                             0x001F
#define MASK_ANA_LDO_VDDRF0V9_SHPT_PD                       0x0040
#define MASK_ANA_LDO_VDDRF0V9_REFTRIM                       0x003E
#define MASK_ANA_LDO_VDDRF0V9_PD                            0x0001
#define MASK_ANA_LDO_VDDRF0V9_V                             0x001F
#define MASK_ANA_LDO_VDDUFS1V2_SHPT_PD                      0x0040
#define MASK_ANA_LDO_VDDUFS1V2_REFTRIM                      0x003E
#define MASK_ANA_LDO_VDDUFS1V2_PD                           0x0001
#define MASK_ANA_LDO_VDDUFS1V2_V                            0x001F
#define MASK_ANA_LDO_VDDLDO4_EXT_XTL6_EN                    0x4000
#define MASK_ANA_LDO_VDDLDO4_EXT_XTL5_EN                    0x2000
#define MASK_ANA_LDO_VDDLDO4_EXT_XTL4_EN                    0x1000
#define MASK_ANA_LDO_VDDLDO4_EXT_XTL3_EN                    0x0800
#define MASK_ANA_LDO_VDDLDO4_EXT_XTL2_EN                    0x0400
#define MASK_ANA_LDO_VDDLDO4_EXT_XTL1_EN                    0x0200
#define MASK_ANA_LDO_VDDLDO4_EXT_XTL0_EN                    0x0100
#define MASK_ANA_LDO_VDDUFS1V2_EXT_XTL6_EN                  0x0040
#define MASK_ANA_LDO_VDDUFS1V2_EXT_XTL5_EN                  0x0020
#define MASK_ANA_LDO_VDDUFS1V2_EXT_XTL4_EN                  0x0010
#define MASK_ANA_LDO_VDDUFS1V2_EXT_XTL3_EN                  0x0008
#define MASK_ANA_LDO_VDDUFS1V2_EXT_XTL2_EN                  0x0004
#define MASK_ANA_LDO_VDDUFS1V2_EXT_XTL1_EN                  0x0002
#define MASK_ANA_LDO_VDDUFS1V2_EXT_XTL0_EN                  0x0001
#define MASK_ANA_CHG_INT_CLR_ST                             0x0002
#define MASK_ANA_CHG_IRQ_CLR                                0x0001
#define MASK_ANA_CPU1_STEP_DELAY                            0x3000
#define MASK_ANA_CPU1_STEP_NUM                              0x0F00
#define MASK_ANA_CPU1_STEP_VOL                              0x00F8
#define MASK_ANA_CPU1_VOL_TUNE_START                        0x0004
#define MASK_ANA_CPU1_VOL_TUNE_FLAG                         0x0002
#define MASK_ANA_CPU1_VOL_TUNE_EN                           0x0001
#define MASK_ANA_DCDC_CPU1_INDP_CTRL                        0x0600
#define MASK_ANA_DCDC_CPU1_INSP_CTRL                        0x0180
#define MASK_ANA_DCDC_CPU1_DP_EN                            0x0040
#define MASK_ANA_DCDC_CPU1_REV                              0x0003
#define MASK_ANA_LDO_VDDLDO4_SHPT_PD                        0x0040
#define MASK_ANA_LDO_VDDLDO4_REFTRIM                        0x003E
#define MASK_ANA_LDO_VDDLDO4_PD                             0x0001
#define MASK_ANA_LDO_VDDLDO4_V                              0x001F

#endif /* __DT_BINDINGS_UNISOC_UMP9620_MASK_H */
