include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(srctree)/drivers/misc/mediatek/hdmi/inc

obj-y	+= hdmi_drv.o mhl_linux_tx.o mhl_rcp_inputdev.o mhl_supp.o platform.o si_8348_drv.o si_mdt_inputdev.o si_mhl2_edid_3d.o smartbook.o

