ccflags-y += -Idrivers/media/platform/msm/ais/cam_utils
ccflags-y += -Idrivers/media/platform/msm/ais/cam_core
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/ais/cam_cpas

obj-$(CONFIG_MSM_AIS) += cam_cpastop_hw.o
